### ISSUE TITLE
Nice to have: metadata import/export functions

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#10]
Within the iOMEGA project I had do the following a few times:
- Overwrite and/or complete spectrum metadata based on a metadata collection I got (as a json file). 
- Export my cleaned-up metadata as json file.

It would hence be nice to have function like ``import_metadata()`` or ``import_metadata_json()``.
For instance something like this:
``` 
from matchms.importing import import_metadata

import_metadata(spectrums, metadata_json, 
                match_field_original='spectrumid', 
                match_field_json='gnpsid',
                replace_fields=['inchi', 'smiles', 'inchikey'])
```

And for exporting it could be something like this:
```
from matchms.exporting import export_metadata

export_metadata(spectrums, metadata_filename,
                fields_to_export=['name', 'spectrumid', 'inchi', 'smiles', 'inchikey'])
```

**Comment by fdiblen** [comment]
Refs #52

**Comment by hechth** [comment]
Hi, would it be possible to expand this metadata export with a CSV option, that simply outputs all the metadata of the spectra inside the MSP file with one column per field? This would be a nice way of interfacing to other services that perform operations on metadata in tabular format.

**Comment by florian-huber** [comment]
Currently this is not implemented (not even for json).
But yes, good that you reactivate this issue :)

Having both json and csv seems easy to do, since most function parts will be the same.

**Comment by florian-huber** [comment]
Hi @hechth , I had a first look at it and realized that a few thing need further discussion first.

Most of all, how should such an metadata export look like if it is for a list of spectra.
When collecting metadata from multiple spectra, I imagine we want to define a `spectrum_identifier` which will look different for different data sources. As a backup, the function could simply number the spectra in the order they are given.

`export_metadata_as_csv([spectrum_1, spectrum_2])` would give:  
| spectrum identifier | precursor_mz | inchikey |
|---------------------|--------------|----------|
| 0                   | 145.22       | XXXXXXXX |
| 1                   | 287.01       | None     |

`export_metadata_as_csv([spectrum_1, spectrum_2], identifier="name")` would give:  
| spectrum identifier | precursor_mz | inchikey |
|---------------------|--------------|----------|
| compound name X                  | 145.22       | XXXXXXXX |
| compound name Y                  | 287.01       | None     |  

(if spectrum_1.get("name") is "compound name X" etc.)

Is that about what you were looking for?

**Comment by hechth** [comment]
Yeah, I think that looks good. I was mainly thinking about the MSP where a name is included, but this get's difficult with the mzml etc., so I think having an identifier is good. Thinking of a CSV file, these would be sort of the row names.

About the JSON, it could be added as an additional key?

**Comment by sdrogers** [comment]
Bit wary of chemical name as an identifier - will very often not be unique. No better suggestion.

in mzml, filename and scan number combined is the best identifier

**Comment by sdrogers** [comment]
Feels like this is something that should be decided when the spectra are loaded rather than saved though

**Comment by florian-huber** [comment]
@hechth 
>Thinking of a CSV file, these would be sort of the row names.  

and

> About the JSON, it could be added as an additional key?

Yes, I would agree with those suggestions.

Also agree with you @sdrogers: compound names are not ideal as identifiers. But I guess that what people chose as identifier might depend a lot on the field, type of data, etc. There is a related issue on that --> #106 where we discussed adding a hash to each Spectrum object.

We could add a function (maybe a method of  `Spectrum` or a function in matchms.filtering) to add an identifier?
Possible options could be to add a metadata-fieldname (e.g. "name") or even multiple ones that will then be combined. Such as Simon's example: ["file_name", "scan_number"] which will then be combined into one string ?

**Comment by florian-huber** [comment]
Here's a sketch:
```python
add_id_to_spectrums(spectrums, identifier_fields=["name"]):
    ids_set = set()
    for i, spectrum in enumerate(spectrums):
        identifier = "-".join([spectrum.get(x, str(i)) for x in identifier_fields])  # i is only the backup-option
        assert identifier not in ids_set, f"Non-unique identifier found: {identifier}"
        ids_set.add(identifier)
        spectrum.set("identifier", identifier)

**Comment by hechth** [comment]
That sounds like a great idea! Also using SMILES as identifiers or IDs from specific databases might be a use case and this could be served with this solution.

**Comment by sdrogers** [comment]
Looks sensible to me

**Comment by sdrogers** [comment]
@florian-huber there is a library around for adding a spectrum hash (SPLASH) - that would be really neat. It’s computed from the spectrum itself. Maybe that’s already what you meant..

We had some issue in the usi code with two libraries giving inconsistent hashes - could check that code base and see what it uses

**Comment by florian-huber** [comment]
This is a bit outdated. And too long. Will close it for now.
