### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by bittremieux** [matchms/matchms#101]
The documentation should contain the following information:

- The version(s) of Python that are supported, or at least the minimum version.
- There is no link to the documentation on readthedocs from GitHub.
- [`is not`](https://docs.python.org/3/reference/expressions.html#is) should be used to check whether the reference and query are the same spectrum when iterating over the scores. Instead `==` is used in the readme, on readthedocs, and in the manuscript at the moment.

**Comment by florian-huber** [comment]
Many thanks for the good hints!
- First two items were addressed in PR #108 .
- And ``!=`` was changed to ``is not`` in code examples (PR #109 and ongoing PR #105 ).

**Comment by florian-huber** [comment]
This has been fixed, see above comment.
