### ISSUE TITLE
Additional filtering methods

### ISSUE THREAD

**Issue by kiaashour** [matchms/matchms#107]
Hey! I've been working on estimating FDRs in metabolomics and I've been using some new filtering methods that currently aren't in the matchms package. Here are the filtering methods I propose:

remove_peaks_within_window: Keep peaks only if they are in the top k intense peaks within a desired mz (Da) window.
remove_spectra_above_intensity: Returns none if the number of peaks above a certain threshold relative intensity is less than desired.
remove_spectra_below: Returns none if the precursor mz of a spectrum is above a maximum mz value.
remove_spectra_within_tolerance: Remove peaks that are within an mz tolerance (in Da) of the precursor mz, excluding the precursor peak.

**Comment by florian-huber** [comment]
Hi Kia, 
sounds good!
Do you have some code on this already that you could make into a pull request?
(best to fork matchms first and then send a PR our way)

**Comment by kiaashour** [comment]
Hi Florian,

Yes, I do indeed have have some code. I will send a PR soon. Let me know if any tests need to be written.

**Comment by florian-huber** [comment]
This was now added with PR #119 .
