### ISSUE TITLE
should coverage be calculated only on unit tests?

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#11]
(I think so)

**Comment by fdiblen** [comment]
Refs #64

**Comment by florian-huber** [comment]
Just pragmatically speaking: to me it looks fine as it is now. SonarCloud coverage does what it is supposed to do (I think), namely enforcing unit test coverage.
Can we close this @sverhoeven ?

**Comment by sverhoeven** [comment]
Indeed it is a nice to have coverage measured separately, but with the current high number of tests seems unnecessary
