### ISSUE TITLE
Add support for import of MoNa json files 

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#111]
As raised in #95, we should extend import options to data sources other than GNPS.
To some extend this has been done/is in the making (mzML, mzXML, msp support). But we should also make sure that we can parse json files from both MoNa AND GNPS.

**Comment by hechth** [comment]
@florian-huber is this still valid?

**Comment by florian-huber** [comment]
Outdated. Please re-open or create new issue if this becomes an issue.
