### ISSUE TITLE
Expand exporting module

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#114]
Currently we expand our importing module (msp, mzML, mzXML files).
In a next step it would be nice to also add respective exporting formats (not necessarily for all formats).

**Comment by sverhoeven** [comment]
For specific issue for msp see #166

**Comment by florian-huber** [comment]
`.msp` export was added in #215 . 
`.mzml` and `.mzxml` is still missing.

**Comment by florian-huber** [comment]
overlaps with #201, so this one will be closed
