### ISSUE TITLE
Sphinx build fails

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#116]
We suddenly get an documentation build error:
``Extension error:
Handler <function _process_docstring at 0x7fd1db87b0e0> for event 'autodoc-process-docstring' threw an exception (exception: module, class, method, function, traceback, frame, or code object was expected, got CPUDispatcher)
Makefile:20: recipe for target 'coverage' failed
make: *** [coverage] Error 2``

**Comment by florian-huber** [comment]
Seems related to this: https://github.com/numpy/numpydoc/issues/268 ?

**Comment by florian-huber** [comment]
Seems to come from recent sphinx change from ``sphinx 3.1.2 `` to ``sphinx 3.2.0``.

**Comment by florian-huber** [comment]
Fixed by setting ``sphinx<3.2.0``  in PR #117 . 
Should be checked again in some time to see if sphinx >3.2.0 would also work.

**Comment by sverhoeven** [comment]
I think it is https://github.com/sphinx-doc/sphinx/issues/8074

**Comment by florian-huber** [comment]
I am still a bit confused here: Why is the readthedocs build failing while the tests using sphinx 3.2.0 all pass?

**Comment by sverhoeven** [comment]
I enabled harmonize_docstrings branch in https://readthedocs.org/projects/matchms/versions/, its [build](https://readthedocs.org/projects/matchms/builds/11661362/) installs our conda/environent-dev.yml and then installs the latest sphinx with `conda install --yes --quiet --name harmonize_docstrings mock pillow sphinx sphinx_rtd_theme` which causes 3.2.0 to be installed.

**Comment by sverhoeven** [comment]
Readthedocs [build](https://readthedocs.org/projects/matchms/builds/11676926/) is green, as it is using Sphinx v3.2.1

**Comment by florian-huber** [comment]
Nice!
In principle we can close this now. Should we also change the version in ``environment-dev.yml``, from ``sphinx>=3.0.0,<3.2.0`` to ``sphinx>3.2.0`` ?

**Comment by sverhoeven** [comment]
Yes lets update conda env file. We could also use `sphinx>=3.0.0,!=3.2.0,<4.0.0`, so we keep the lowest version, but exclude the bad version (3.2.0) and dont get burned by a new incompatible major version.
