### ISSUE TITLE
splitting off spec2vec

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#12]
We should consider splitting off ``matchms/similarity/spec2vec/*`` into its own repo. If we choose to do so, we may want to use the same method I used for splitting off ``notebooks`` and ``old-iomega-spec2vec``.

Also, we should decide on which repository (if any) should be a fork of ``iomega/spec2vec``.

**Comment by fdiblen** [comment]
- anaconda package was published see https://anaconda.org/nlesc/spec2vec
- made a spec2vec [0.1.0 release](https://github.com/iomega/spec2vec/releases/tag/0.1.0)

**Comment by fdiblen** [comment]
Notebook repository is [here](https://github.com/matchms/notebooks)
