### ISSUE TITLE
Consistent docstring style

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms#120]
Docstrings use different styles, some use google and some use numpy style.

Using `Parameters` header is [numpy style](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard). 
Using `args:` header is [google style](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods), the args themselves need to be indented though.

The [napoleon](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) Sphinx extension can parse both styles.
We should standardize on one style and make it part of the CONTRIBUTING.md.md and enforce it by disabling the other style in napoleon.

**Comment by florian-huber** [comment]
In PR #118 we switched to ``Parameters``, so I would make that the default.

**Comment by florian-huber** [comment]
Dealt with in PR #125
