### ISSUE TITLE
Latest release did not end up on zenodo or RSD

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#129]
The latest release found on zenodo is 0.4.0 (0.5.0 hence wasn't added).
In the RSD I also only found an older version (0.3.1). 

I guess that usually should be done automatically when a release is done, so not sure what went wrong here.

**Comment by sverhoeven** [comment]
In https://github.com/matchms/matchms/settings/hooks/215264519 I can see that Zenodo received the 0.5.0 release events.

Can you check on Zenodo the GitHub integration is turned on?
You can also check https://zenodo.org/deposit?page=1&size=20 do you see 0.5.0 release there?

**Comment by florian-huber** [comment]
Looks like the GitHub link was not turned on for my account (although it showed a link with the matchms organization).
And I can't see it on the linked site.

**Comment by sverhoeven** [comment]
Found https://zenodo.org/account/settings/github/repository/matchms/matchms# it has a "The metadata file is not valid JSON." error processing 0.5.0. On GH hook page you can resend the event.

As you are creating the releases you should be the GH<>Zenodo hook owner. Can you check https://github.com/organizations/matchms/settings/audit-log?q=action%3Ahook to see who created the hook?

**Comment by florian-huber** [comment]
Just fixed the json (which was, of course, missing a comma).

And it looks like you created the webhook.

**Comment by florian-huber** [comment]
I resend the request to zenodo.

**Comment by sverhoeven** [comment]
Hmm, on Zenodo I get `This repository is managed by another user of your GitHub organization.` message and disable switch. I cannot see audit log myself because I am not a org owner. 

In https://github.com/matchms/matchms/issues/12#issuecomment-627943692 @jspaaks marked Zenodo as done, so maybe he is current owner of Zendo webhook?

**Comment by florian-huber** [comment]
Sorry, it indeed is Jurriaan. I mixed it up with the create, delete, push webhook (which is from you).

**Comment by jspaaks** [comment]
I just put the toggle to off, if @florian-huber toggles it back on, I think that makes him the owner.

refs: https://zenodo.org/account/settings/github/

**Comment by florian-huber** [comment]
Yes, that seems to work and make me owner. Thanks.

Can I trigger another webhook event for the last release? Or do I have to make another release?

**Comment by jspaaks** [comment]
> Can I trigger another webhook event for the last release

I think that might work, as Zenodo doesn't seem to be aware of this release. If it doesn't work, it's because you can't overwrite releases on Zenodo. Just make a patch release 0.5.1, that should trigger a new release. (You can optionally remove 0.5.0 from the GitHub releases).

**Comment by sverhoeven** [comment]
Great, is see 0.5.1 on [Zenodo](https://zenodo.org/record/3991671).

**Comment by florian-huber** [comment]
Thanks Stefan and Jurriaan!

(I'll close this issue.)
