### ISSUE TITLE
API - which options to keep

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#138]
This is a bit of a breakout issue of #135, but with a bit more hurry since it affects our matchms JOSS paper.

Currently matchms has multiple ways to compute scores. Some might change, some might go, so better to make some decisions on that.
```python
# Option 1
from matchms import calculate_scores
from matchms.similarity import CosineGreedy

similarity_measure = CosineGreedy(tolerance=0.01)
scores = calculate_scores(spectrums, spectrums, similarity_measure)

# Option 1b (here would fail because CosineGreedy is not parallel)
from matchms import calculate_scores_parallel
from matchms.similarity import CosineGreedy

similarity_measure = CosineGreedy(tolerance=0.01)
scores = calculate_scores_parallel(spectrums, spectrums, similarity_measure)

# Option 2
from matchms import Scores
from matchms.similarity import CosineGreedy

similarity_measure = CosineGreedy(tolerance=0.01)
scores = Scores(spectrums, spectrums, similarity_measure).calculate()

# Option 3 - scores here is actually the same as scores._scores in the other examples
from matchms.similarity import CosineGreedy

similarity_measure = CosineGreedy(tolerance=0.01)
scores = similarity_measure(spectrums, spectrums)
```

**Comment by florian-huber** [comment]
To me the ``calculate_scores`` and ``calculate_scores_parallel`` felt like an unnecessary additional wrapper. The only thing they do is call what above is done in Option 2, so ``calculate_scores --> Scores --> CosineGreedy``. Which is probably also the reason that -in practice- I have never used any of them.

**On the other hand:** The planed redesign, discussed in #59 and (from now on) in #135 would remove the unclear aspect of  ``calculate_scores`` vs ``calculate_scores_parallel``, because ``Scores.calculate()`` (and hence also ``calculate_scores``) will cover both. And the code in Option 1 above looks nicer than the other options (I think).

**Comment by florian-huber** [comment]
- **Option 3** above is fine, but should not be the proposed way to use matchms. It is also likely to change soon if we indeed integrate both sequential and parallel implementations in one class (see #135). --> ``scores = similarity_measure.compute_score_matrix(spectrums, spectrums)``
- **Option 1b** will soon become obsolete (see comment above).

Now the question is:
Do we prefer **Option 1** or **Option 2** to be the default ?
The code example in the manuscript is Option 1, which is why I want to make sure...

Any thoughts @sverhoeven and @jspaaks ?

**Comment by sverhoeven** [comment]
Option 3 is for a single spectrum pair returning a single score. It is more for someone developing a new similarity function.

For me having the Scores class calculated its own scores is weird. I expect something else than Scores class to calculate the 
scores for me. Removing Scores.calculate and keeping calculate_scores(), to have a single calculate method would make me happy.

So I prefer option 1.

**Comment by florian-huber** [comment]
Thanks Stefan. That's perfect. Because than the example in the paper would also keep working, no matter if we change what happens under the hood.

(and you are right, Option 3 is for a single score, I was accidentally thinking of the parallel scores we have)

**Comment by florian-huber** [comment]
I will close this. The general design discussion stays open (#135 ), but regarding the matchms paper I will keep Option 1, which we should also maintain.
