### ISSUE TITLE
Spectra mergin as pre-processing step

### ISSUE THREAD

**Issue by bachi55** [matchms/matchms#140]
**Is your feature request related to a problem? Please describe.**
Spectra databases such as Massbank provide MS/MS of single compounds for multiple collision energies. See for example: [AU203901 @10ev](https://massbank.eu/MassBank/RecordDisplay?id=AU203901&dsn=Athens_Univ), [AU203902 @10ev](https://massbank.eu/MassBank/RecordDisplay?id=AU203902&dsn=Athens_Univ) and [AU203903 @30ev](https://massbank.eu/MassBank/RecordDisplay?id=AU203903&dsn=Athens_Univ). If we want to compute the spectrum similarity of this compound to another one, we would like to use all available information. One way to do that, is to merge all the spectra of all collision energies and use the merged spectrum for further analysis. 

This requests relates to #9.

**Describe the solution you'd like**
It would be nice to have a method, as part of your pre-processing pipeline, that merges spectra of the same compound into a single one. The determination, which spectra should be merged, can be left to the user. 

**Any good starting points?**
In principle one could use some function like:
```python
def merge_spectra(list_of_spectra, ppm=5):
    mz_out = []  # m/z
    int_out = []  # intensities
    for s in list_of_spectra:
        mz_out += s.get_mzs()
        int_out += s.get_ints()

    sout = Spectra(mz_out, int_out)
    # merge peaks that are very close (see code in #9)
    sout.merge_close_peaks(ppm)
    return sout
```

Best,
Eric

**Comment by florian-huber** [comment]
Thanks for starting this issu @bachi55 .
To me this seems clearly useful to include into matchms.

**A few further questions, first the practical one:**
Would you be interested in implementing this? 
Or work on a PR together?
I think we can also implement it from our side, but that could take some time.

**And some more technical things as well:**
The function you sketch above seems a good starting point to me.
Two things that crossed my mind:
- How to best merge the metadata? In principle that is possible of course but we might get into quiet some parsing issues (inconsistent field names or entries, set default decisions on which version to keep if metadata conflicts occur etc).
- Not sure about adding the merging function to the ``Spectrum`` class (``.merge_close_peaks``). I would probably prefer to simply add (or import) the necessary sub-function to the above sketched one.
