### ISSUE TITLE
conflicting instructions on how you want to be cited

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#146]
``README.rst`` says _cite the paper_, ``CITATION.cff`` says _cite the software_.

Note the CFF standard allows for writing down what it says in the README, see for example https://github.com/benvanwerkhoven/kernel_tuner/blob/af9101760dadaf7b64ac037df3bdef0ef9609bb2/CITATION.cff

**Comment by florian-huber** [comment]
Will be solved by PR #147
