### ISSUE TITLE
Add import and export for json files

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#15]
I tried using ``save_as_mgf`` on the actual data. 
**The good part:** it seems to work even for large lists of spectrums. 
**The bad part:** it is pretty slow. Writing the entire dataset (147,000 spectra) to a mgf file of about 1GB took >20 minutes.  I slightly changed ``save_as_mgf`` (#152) but that didn't improve things much, so it is mostly likely due to the way pyteomics writes it to an mgf file.

I ran a quickly made json function for comparison, which was at least 5 times faster.
```python
import json

def save_as_json(spectrums, filename):
    """Save spectrum(s) as json file.

    Args:
    ----
    spectrums: list of Spectrum() objects, Spectrum() object
        Expected input are match.Spectrum.Spectrum() objects.
    filename: str
        Provide filename to save spectrum(s).
    """
    if not isinstance(spectrums, list):
        # Assume that input was single Spectrum
        spectrums = [spectrums]

    # Convert matchms.Spectrum() into dictionaries
    spectrum_dicts = []
    for spectrum in spectrums:
        spec = spectrum.clone()
        spectrum_dict = {"intensities": spec.peaks.intensities.tolist(),
                         "mz": spec.peaks.mz.tolist(),
                         "metadata": spec.metadata}
        spectrum_dicts.append(spectrum_dict)

    # Write to json file
    with open(filename, 'w') as fout:
        json.dump(spectrum_dicts, fout)
```
**Question:** Does it make sense to add such a function? 
We still need the ``save_to_mgf`` function because that is how the data can be shared within the community. But to create safe points, store data during the processing pipeline etc. one could still switch to a different (better?) format.

By the way: 
Json was just what first crossed my mind. It could of course be any other suited file format!

**Comment by florian-huber** [comment]
Hi @sverhoeven , sorry, bit late response. They only give an example of how their files look like, here: https://ccms-ucsd.github.io/GNPSDocumentation/api/
So I think we should maybe define our own schema, or what do you think?

**Comment by sverhoeven** [comment]
I am not in favor of defining a schema based on their data. I would like them to specify which fields are optional or required . Then we can use their schema to validate during json load. 

The [current load_from_json()](https://github.com/matchms/matchms/blob/eb5b1c25d617ee6725f2e25438100e4af9a9fc14/matchms/importing/load_from_json.py) implementation only cares about peaks, inchiaux and ionmode properties the rest are taken as unmodified metadata. So until we get a schema this is the minimal and correct implementation.

**Comment by florian-huber** [comment]
We currently have a minimal implementation that allows to import and export jsons. Those might be refined in the future, but I think this issue can be closed.
