### ISSUE TITLE
Example scripts or notebooks

### ISSUE THREAD

**Issue by Adafede** [matchms/matchms#154]
**Is your feature request related to a problem? Please describe.**
No, it is not a problem, just a kind request/suggestion :)

**Describe the solution you'd like**
A (multiple) notebook(s) or example script(s)

**Any good starting points?**
At the moment no, but happy to help in case!

**Additional context**
Context is untargeted LC-MS/MS experiment. Feature list out of whatever tool, usually submitted to GNPS to get an edge list / spectrum similarity score. In other words, do you already have such "GNPS like output" scripts in the pocket? 😄 

Very great work btw

**Comment by florian-huber** [comment]
Thanks @Adafede.
We were already thinking about adding a tutorial that would indeed also go this direction.
(I may still take a bit of time to be done, but it's fairly high on my agenda ;) )

In the meantime you could also have a look at our notebooks here: https://github.com/iomega/spec2vec_gnps_data_analysis

In particular a notebook where we create a network using ``matchms`` and ``spec2vec``: https://github.com/iomega/spec2vec_gnps_data_analysis/blob/master/notebooks/iomega-10-spectra-networking.ipynb

And please let me know if you run into any issues when running those notebooks!

**Comment by Adafede** [comment]
Wonderful! 

Will have a look at it and come back... btw, if using both spec2vec and matchms, which environment do you recommend?

**Comment by florian-huber** [comment]
We have a pip version now, but if possible the best is to install it using conda. 
```
conda create --name spec2vec_analysis python=3.7  # or 3.8 if you prefer
conda activate spec2vec_analysis
conda install --channel nlesc --channel bioconda --channel conda-forge spec2vec
```

**Comment by florian-huber** [comment]
short update: I will wait until the current PRs, mostly #159 since that will slightly change the API at a few points.
Then I hope to provide a blog post and a notebook.

**Comment by florian-huber** [comment]
There is now a first tutorial notebook here: https://github.com/matchms/matchms/blob/tutorial/tutorial/matchms_tutorial_01_building_analysis_pipeline.ipynb
And there will be a blog post very soon!

**Comment by Adafede** [comment]
Really nice! Thank you!

**Comment by florian-huber** [comment]
I just added an extensive introduction tutorial: https://blog.esciencecenter.nl/build-your-own-mass-spectrometry-analysis-pipeline-in-python-using-matchms-part-i-d96c718c68ee
This will (in the next days) be extended to also include a part on Spec2Vec, and later one on building networks as well.
I will close this issue for now, but feel free to make a new one for follow-up issues related to the tutorial!
