### ISSUE TITLE
KNIME workflow

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms#16]
For users who don't like Python we could create [KNIME](https://knime.com) nodes for matchms which can be used in a KNIME workflow.

The workflow can be based on the integration tests.
The first prototype could use [Python nodes](https://hub.knime.com/knime/extensions/org.knime.features.python2/latest/org.knime.python2.nodes.script.Python2ScriptNodeFactory) with code snippets written by us.
Later we could write proper nodes with the [archetype]( https://github.com/3D-e-Chem/knime-python-node-archetype)

**Comment by florian-huber** [comment]
Outdated, reopen when needed.
