### ISSUE TITLE
Question/Recommendations

### ISSUE THREAD

**Issue by benbowen** [matchms/matchms#160]
Hi, I'm just getting started using your package and was hoping you could take a look at my initial implementation.  I have attempted to follow along some of the docs, but am mashing it up to emulate an existing workflow.

My goal is to load existing spectra, calculate a dotproduct, calculate a dotproduct where spectra are shifted by precursor m/z.  

I haven't looked into normalization yet, but that is next.  I typically normalize by sqrt and L2 norm; so I will likely do this without the package.

My main question is if there is a tool for calculating the dot prod and shifted dot prod as a hybrid approach and I just can't find it in the docs.  

Data looks like this:

```
{'key1': 23870,
 'key2': 17951,
 'msv1': array([[ 82.0652,  84.0809,  99.0919, 137.0156, 159.972 , 164.0266,
         222.9832, 265.0534, 275.0272, 281.9648, 293.0484, 299.0147,
         300.0224, 307.9806, 319.968 , 328.0175, 333.9836, 334.9915,
         337.0072, 362.9864, 363.9897, 377.9976, 380.9968, 381.9996,
         382.992 , 383.0014, 463.0867],
        [  3.6   , 101.5   ,  21.58  ,   2.1   ,   1.2   ,  23.78  ,
           1.3   ,   7.59  ,   1.3   ,   4.9   ,   1.3   ,  13.99  ,
          27.47  ,   1.4   ,   1.2   ,   9.19  ,   1.2   ,   2.3   ,
          25.27  , 696.2   ,   2.3   ,   1.9   , 999.    ,   7.79  ,
           1.2   ,   1.3   ,   3.4   ]]),
 'pmz1': 463.0854,
 'collision_energy_1': 41.0,
 'adduct_1': '[M+H]+',
 'msv2': array([[ 55.018 ,  55.0544,  61.0286,  67.0544,  69.0337,  69.07  ,
          71.0494,  77.0388,  79.0544,  81.0701,  83.0493,  85.0649,
          91.0545,  93.0702,  95.0494,  95.0858,  97.0651,  99.0444,
         101.0237, 101.06  , 103.0392, 103.0547, 105.0451, 105.0703,
         107.0496, 107.086 , 109.0652, 109.1016, 111.0446, 111.0809,
         115.0546, 117.0704, 119.0861, 121.0654, 121.1018, 123.081 ,
         125.0603, 128.0626, 129.0705, 131.0862, 133.0655, 133.1018,
         135.0811, 135.1176, 137.0603, 137.0968, 139.0759, 141.0705,
         142.0784, 143.0863, 145.0655, 145.1019, 147.0812, 147.1176,
         149.0968, 149.133 , 151.0761, 153.0709, 153.0917, 154.0784,
         155.0863, 157.0658, 157.102 , 159.0812, 159.1176, 161.0969,
         161.1333, 163.0765, 163.1125, 165.0707, 165.0918, 166.0786,
         167.0863, 168.0943, 169.102 , 171.0813, 171.1177, 173.097 ,
         173.1334, 175.1126, 177.0918, 177.1284, 178.0785, 179.0864,
         180.0943, 181.1021, 182.1103, 183.0815, 183.1177, 185.0971,
         185.1335, 187.1127, 187.1493, 189.1283, 191.0863, 191.1077,
         192.0947, 193.1022, 194.1104, 195.1179, 197.0972, 197.1335,
         198.1051, 199.1128, 199.1492, 201.1285, 203.1084, 205.1233,
         207.1179, 208.1256, 209.1335, 211.113 , 211.1493, 213.1286,
         213.1651, 221.1339, 223.1132, 223.1494, 225.1291, 225.1652,
         226.1367, 227.1445, 229.1604, 231.1398, 233.1339, 235.1498,
         237.1287, 237.1656, 239.1443, 239.1808, 241.16  , 243.1397,
         243.1758, 247.1497, 249.129 , 249.1652, 251.1445, 251.1812,
         253.1602, 263.1447, 263.1814, 265.1605, 266.168 , 267.1397,
         267.1757, 268.1838, 269.1555, 269.1915, 273.1654, 276.1526,
         279.1765, 281.1555, 281.1913, 283.1713, 285.1867, 286.1946,
         291.1758, 294.1636, 297.187 , 299.2031, 301.1816, 309.1864,
         312.1745, 327.1971, 345.2089],
        [ 15.18  ,  18.88  ,  37.76  ,  60.84  ,  34.27  ,  47.35  ,
          27.77  ,  10.89  ,  89.51  , 129.57  , 130.47  ,   5.    ,
         113.39  , 183.02  ,  31.77  , 116.18  , 637.16  , 104.2   ,
         112.69  ,   6.19  ,  31.67  ,   5.09  ,  18.28  , 228.67  ,
          44.96  , 163.34  , 337.36  ,  31.67  ,  11.19  ,  28.67  ,
          11.49  ,  78.32  , 411.79  , 999.    ,  62.24  , 342.36  ,
          30.17  ,  21.08  ,  86.21  , 201.7   ,  57.04  , 152.45  ,
         203.    ,  30.87  ,  13.79  ,  56.94  ,  24.28  ,  78.52  ,
          16.38  , 251.05  ,  45.95  , 321.98  , 159.84  , 149.35  ,
          81.32  ,   7.39  ,  36.96  ,   7.39  ,   7.39  ,  11.19  ,
         125.37  ,   8.99  , 237.96  , 120.98  , 240.36  , 142.46  ,
          34.07  ,  10.89  , 311.39  ,  28.77  ,  13.89  ,   4.1   ,
          71.13  ,  15.48  , 226.97  ,  66.23  , 170.03  , 166.83  ,
          63.74  , 123.18  ,   8.69  ,  22.98  ,   8.99  ,  37.16  ,
          13.79  ,  95.6   ,  10.29  ,   8.79  , 196.    , 113.09  ,
         152.25  , 174.53  ,  13.89  ,  76.32  ,  10.49  ,   8.69  ,
          10.19  ,  54.55  ,  14.49  , 107.89  ,  46.95  ,  89.21  ,
           6.69  ,  85.41  ,  64.54  ,  56.54  ,   7.89  ,   9.79  ,
          48.05  ,   7.79  ,  70.63  ,  26.37  ,  20.58  ,  46.25  ,
           5.69  ,  13.09  ,   8.89  ,  35.66  ,  26.57  ,  10.39  ,
           5.79  ,  28.97  ,   9.39  ,   8.59  ,  21.58  ,  17.98  ,
          12.89  ,   5.79  , 166.43  ,   8.99  , 431.87  ,  16.18  ,
          22.68  ,  16.18  ,  13.39  ,  72.03  ,  78.42  ,  21.18  ,
          63.24  ,  32.97  ,  29.17  ,  27.77  ,  15.18  ,  11.49  ,
         164.04  ,  57.14  ,  26.57  ,  67.43  ,  13.79  ,   6.69  ,
          17.68  ,  32.57  ,  86.31  ,   7.29  ,  20.48  ,  22.48  ,
          96.1   ,  10.49  ,  41.06  ,  18.88  ,   9.39  , 168.83  ,
          19.08  , 157.14  ,  31.57  ]]),
 'pmz2': 405.2272,
 'collision_energy_2': 40.0,
 'adduct_2': '[M+H]+'}
```

My script operates on these like this:

```
cosine_greedy = CosineGreedy(tolerance=0.01)
hits = []
for c in comparisons:
    spectrum1 = Spectrum(mz=c['msv1'][0],
                      intensities=c['msv1'][1],
                      metadata={'id': c['key1']})
    spectrum2 = Spectrum(mz=c['msv2'][0],
                  intensities=c['msv2'][1],
                  metadata={'id': c['key2']})
    spectrum1_s = Spectrum(mz=c['msv1'][0]-c['pmz1'],
                      intensities=c['msv1'][1],
                      metadata={'id': c['key1']})
    spectrum2_s = Spectrum(mz=c['msv2'][0]-c['pmz2'],
                  intensities=c['msv2'][1],
                  metadata={'id': c['key2']})
    score, n_matches = cosine_greedy.pair(spectrum1, spectrum2)
    score_s, n_matches_s = cosine_greedy.pair(spectrum1_s, spectrum2_s)
    hits.append({'score':score,'matched_peaks':n_matches,
               'score_s':score_s,'matched_peaks_s':n_matches_s,
               'key1':c['key1'],'key2':c['key2']})
```

Just an FYI, your docs are great.  I got up and running in just a few minutes.  Also the speed of the scoring algorithm is very impressive.  20 seconds to score 42k comparisons without additional parallelization. Thanks for putting this together!

Any advice on how you think I should implement this scoring efficiently is much appreciated.

**Comment by sdrogers** [comment]
Hi Ben
Not sure what you mean by a hybrid approach?
The modified cosine in this implementation follows that used in gnps. That is, any fragment from spectrum 2 (say; it’s symmetric) can either be matched directly to a fragment in spectrum 1 or matched after shifting by the difference in precursor mz, but not both. If it can do both, the matching that has highest intensity wins.
Maybe that’s already what you mean by hybrid?
Simon

**Comment by sdrogers** [comment]
Phrased badly: if it matches something with and without shifting, the highest intensity one wins....each fragment can ultimately only contribute once to the score.

**Comment by benbowen** [comment]
Thanks @sdrogers! Just to confirm for exact similarity, I should use the "cosine_greedy" like how it is implemented in my example above, and for hybrid/modified cosine I should use this? https://github.com/matchms/matchms/blob/master/tests/test_modified_cosine.py#L46

**Comment by florian-huber** [comment]
Hi @benbowen. Yes, that will be the one: ``ModifiedCosine`` 
ModifiedCosine will set the shift between spectra to the difference in the ``precursor_mz`` fields between two input spectra.

**Comment by benbowen** [comment]
Thanks all!

**Comment by sdrogers** [comment]
Great!
Just for my clarity - is our modified cosine what you call “hybrid”?
If so, I guess we don’t have a similarity that does _only_ shifted peaks. Is that a common use case?

**Comment by benbowen** [comment]
@sdrogers when I say hybrid I generally mean scoring that can score similarity both by exact spectral similarity and spectral similarity shifted by precursor mz. I don't know when I started calling it that, but probably from this paper: https://pubs.acs.org/doi/10.1021/acs.analchem.9b03415

Using what you call modifiedcosine is perfect for my needs.  I just ran it on a block of ~40k comparisons on exact, shifted, and modified.  There are probably lots of little differences, but in general modified seems to snags exact similarity or shifted similarity appropriately; so all is good.

**Comment by sdrogers** [comment]
Ah, yes, I remember that paper. As far as I remember it’s basically modified cosine.

**Comment by sdrogers** [comment]
Are you doing shifted by just manually altering the m/z values? I wonder if we should add that - would be very easy.

**Comment by benbowen** [comment]
Yep, I just did this:

```
spectrum1_s = Spectrum(mz=c['msv1'][0]-c['pmz1'],
                      intensities=c['msv1'][1],
                      metadata={'id': c['key1']})
spectrum2_s = Spectrum(mz=c['msv2'][0]-c['pmz2'],
                  intensities=c['msv2'][1],
                  metadata={'id': c['key2']})
score_s, n_matches_s = cosine_greedy.pair(spectrum1_s, spectrum2_s)
```

where c['pmz1'] and c['pmz2'] are precursor m/zs and c['msv1'] and c['msv2'] are 2d numpy array of spectra, but I wouldn't add this to matchms.

My 2 cents is that you can better preserve your sanity and effectiveness by keeping the number of scoring functions to a useful minimum, and shifted dot prod is already solved by matchms where users can either shift it themselves or use modifiedcosine. If the precursor m/zs match then modifiedcosine used exact dotprod if not then it got shifted.

**Comment by sdrogers** [comment]
Agree that simplicity is good, but they are not quite the same I don’t think. Shifted can only match shifted ions whereas modified cosine will decide whether or not to shift individual ions to greedily maximise the score. In other words, modified should never be lower than normal cosine for a pair of spectra (although the greedy algorithm means it sometimes might be). Conversely, you could have a pair of spectra for which cosine was 1 and shifted was zero (all fragment ions match, precursors don’t).

Happy not to add a shifted only score, but if it would get used, it would be very easy.

**Comment by benbowen** [comment]
Interesting! so then by doing all 3 and looking at num matched peaks you can get an idea of the relative frequency of ions between two spectra shifting by neutral loss (e.g. glycosylation) vs common fragment (e.g. choline).  That probably has useful information.
