### ISSUE TITLE
Question on combining PrecursorMzMatch with CosineGreedy

### ISSUE THREAD

**Issue by benbowen** [matchms/matchms#163]
Do you have a simple way for performing MSMS similarity for experiment vs reference where precursor m/z match within tolerance?  I can see running PrecursorMzMatch and then scoring only where True, but I am predicting that there is a builtin wrapper for this in matchms that I haven't found.

**Comment by florian-huber** [comment]
Usually I would run this like this
```python
from matchms import calculate_scores
from matchms.similarity import PrecursorMzMatch

similarity_measure = PrecursorMzMatch(tolerance=1.0, tolerance_type="ppm")  # chose between "Dalton" and "ppm"
scores = calculate_scores(reference_spectra, query_spectra, similarity_measure)
```
Where ``reference_spectra``, ``query_spectra`` are lists of matchms ``Spectrum``.
The actual scores are stored in ``scores.scores``

**Comment by benbowen** [comment]
but then how would you follow on by doing msms similarity only where scores==True?

**Comment by benbowen** [comment]
This is how I'm doing it now

```
from matchms.similarity import PrecursorMzMatch
similarity_score = PrecursorMzMatch(tolerance=0.01, tolerance_type="Dalton")
scores = calculate_scores(exp_spectra, exp_spectra, similarity_score)
indices = np.where(np.asarray(scores.scores))
idx_row, idx_col = indices
cosine_greedy = CosineGreedy(tolerance=0.01)
data = []
for (x,y) in zip(idx_row,idx_col):
    if x<y:
        msms_score, n_matches = cosine_greedy.pair(exp_spectra[x], exp_spectra[y])
        if (msms_score>0.7) & (n_matches>3):
            data.append({'msms_score':msms_score,
                         'matched_peaks':n_matches,
                         'experiment_id':x,
                         'reference_id':y})
df = pd.DataFrame(data) 
```

**Comment by florian-huber** [comment]
Oh sorry, I was reading too fast and was missing the point about *combining* the two scores.
We are currently working on better ways to query such things, but for now your solution seems like a decent option!

Another option could also be something like this:
```python
from matchms import calculate_scores
from matchms.similarity import PrecursorMzMatch, CosineGreedy

precursor_match = PrecursorMzMatch(tolerance=0.01, tolerance_type="Dalton")
cosine_greedy = CosineGreedy(tolerance=0.01)
scores = calculate_scores(exp_spectra, exp_spectra, precursor_match)

scores_combined = []
for score in scores:
    if score[2]:
        cosine_score, cosine_matches = cosine_greedy.pair(score[0], score[1])
        scores_combined.append(list(score) + [cosine_score, cosine_matches])
```
The ``cores_combined`` will then contain the spectra and scores, but you would need another step to bring it into a nice DataFrame...

**Comment by benbowen** [comment]
Thanks, I'll run it both ways an play around with it.  It actually went quite fast even with all the looping and condition statements to deal with.  In your way, keeping the spectra intact would be handy for non-duplicated metadata management.

**Comment by florian-huber** [comment]
Cool. Enjoy playing around!
