### ISSUE TITLE
Parallelize score calculations

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#165]
While we optimized all key scores quiet a bit, many scores currently just do Python loops when comparing large arrays of spectra (most importantly: ``CosineGreedy`` and ``ModifiedCosine``).

Seems only natural to add a parallel implementation of the basic double-loop --> Check with Johan?

**Comment by Adafede** [comment]
Hi there! Was about to post this...new year, new resolutions? Clearly upvoted! 👍🏼

**Comment by florian-huber** [comment]
I spend a bit of time to check if I could implement this using `numba` but that didn't work out because of too many non-numba style functions being invovled. Could maybe be fixed, but I won't have the time for doing this.

Other options might be to use `joblib` or `asyncio`, but I probably won't be able to work on that anytime soon.

**Comment by hechth** [comment]
This is something that might become of interest also for our work, so it might get addressed in the next couple of months.

**Comment by florian-huber** [comment]
Sound great! Let me know if I can help with anything.

Just a minor comment regarding expectations: 
we optimized the indivual pair-wise score computation quite a bit. But the double-for-loop remains and can certainly be parallelized. However, unless run on a bigger infrastructure my expectations on speed gain are modest, maybe about 2-fold on a normal computer with 4-8 cores.
(due to the extra overhead you create by parallelizing)

In practice I expect a much bigger impact will come from smarter pipelines: that means only computing those scores that seem interesting enoug (e.g. within a certain precusor m/z). That would be #268

**Comment by florian-huber** [comment]
More recent issued on that is #325, so this will be closed.
