### ISSUE TITLE
Pathlib support

### ISSUE THREAD

**Issue by LourensVeen** [matchms/matchms#168]
**Is your feature request related to a problem? Please describe.**
In the [recently published blog post](https://blog.esciencecenter.nl/build-your-own-mass-spectrometry-analysis-pipeline-in-python-using-matchms-part-i-d96c718c68ee), there's an example of reading an MGF file:
```
import os
from matchms.importing import load_from_mgf

path_data = os.path.join(os.path.dirname(os.getcwd()), "data") 
file_mgf = os.path.join(path_data, 
                        "GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf")
spectrums = list(load_from_mgf(file_mgf))
```
Those lines where the path is built look really ugly, and probably scary to someone who's never done Python, which is the audience you're targeting.

**Describe the solution you'd like**
Python has a nice `pathlib` library, which allows you to make this look much more natural:
```
from pathlib import Path
from matchms.importing import load_from_mgf

path_data = Path.cwd() / "data"
file_mgf = path_data / "GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf"
spectrums = list(load_from_mgf(file_mgf))
```
(Or you could merge the two lines and build `file_mgf` directly.) In order for that to work, `load_from_mgf` needs to support `pathlib.Path` as an argument. (or the user could convert manually, by calling `load_from_mgf(str(file_mgf))`, but that's one more thing you have to explain.

**Any good starting points?**
```
if isinstance(path, Path):
    path = str(path)
```

**Comment by florian-huber** [comment]
I like the idea and think we can soon pick this up!

In the meantime I already changed the tutorial code example from 
```
path_data = os.path.join(os.path.dirname(os.getcwd()), "data") 
```
to
```
path_data = "..."  # enter path to downloaded mgf file
```
That is probably easier to understand (in particular to people relatively new to Python). Plus, people might have downloaded the file to another folder anyway.

**Comment by florian-huber** [comment]
Stale for too long. Will be closed. Feel free to re-open when needed.
