### ISSUE TITLE
Extend and improve adduct handling

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#171]
Currently matchms has an OK basic adduct handling (in `derive_adduct_from_name()` and `derive_ionmode()` filters).

This could be improved by:
- updating the list of `known_adducts`
- Expand the `looks_like_adduct()` function --> in progress: PR #170 
- Consider using more information from adducts, e.g. by following mass formulas such as found here: https://fiehnlab.ucdavis.edu/staff/kind/metabolomics/ms-adduct-calculator/
- make consistent choice: `[M+H]+` OR `M+H+` (currently both exist)

**Comment by florian-huber** [comment]
I would now go for `[M+H]+` instead of `M+H+`. This seems a bit clearer, think for instance of cases like: `M-H-NH3+` where it is not clear (without further chemical understanding) if this refers to `[...]+` or `[...]3+`.

@justinjjvanderhooft let me know if you have a different opinion here!

**Comment by justinjjvanderhooft** [comment]
I would go for [M+H]+ as well as it is more clear than the other one.

**Comment by justinjjvanderhooft** [comment]
Also, I think we will be able to get some nicely annotated data from a collaborator in terms of adducts (thousands of annotated adducts)

**Comment by florian-huber** [comment]
Sounds good! The motivation for to work on this now also comes from working with the newest GNPS_all dataset (>210,000 spectra). And there I realized that a bit better adduct handling should help us to get even more fully annotated spectra out of it (with inchi+inchikey etc.).

**Comment by justinjjvanderhooft** [comment]
Great! That has been growing nicely. Wonder how many unique compounds there are in pos and neg mode. It might help our negative model as well! And it improves our chances to separate training and test data :-)

**Comment by florian-huber** [comment]
I am now changing the `parent_mass` estimation to also include the masses and charges of known adduct, following https://fiehnlab.ucdavis.edu/downloads/staff/kind/Metabolomics/MS-Adduct-Calculator/mass-of-electron-error.xls

In addition I plan to add other adducts that we found in the GNPS_all data:
| adduct | charge | mass_multiplier | correction_mass |
| ------------- | ------------- | ------------- | ------------- |
| [M-H2O+H]+ | 1  | 1 | -17.003289 |
| [M-2H2O+H]+ | 1  | 1 | -35.013854 |
| [M+H-NH3]+| 1| 1 | -16.019273|

**Comment by justinjjvanderhooft** [comment]
Which adducts are you planning to add? I don't see the list in the excel file (yet).... Good idea to add some of the ones we can expect that we hadn't included yet. Perhaps the ion identity networking preprint still has some mentioned?

**Comment by florian-huber** [comment]
The ones I now have are here: https://github.com/matchms/matchms/blob/expand_adducts/matchms/data/known_adducts_table.csv
(except the two mentioned above, all are taken from: https://fiehnlab.ucdavis.edu/staff/kind/metabolomics/ms-adduct-calculator/)

**Comment by justinjjvanderhooft** [comment]
Ok, thanks! From the IIN preprint: In positive ion mode, most mass spectrometrists routinely consider H and Na adducts, but rarely NH4, Ca, and K adducts and in-source fragments that were commonly observed in the 24 datasets. Perhaps adding the Ca makes sense as they might end up in GNPS libraries as well....

**Comment by florian-huber** [comment]
Do you mean we should check what's in the GNPS all dataset?
The .xls file from the FiehnLab also contains a statistic from NIST12 listing the frequency of different adducts.

Here's their top-30:
| Ranking  | Adduct name | Count | Cumulative | Percent | Cumulative | 
 |-- | -- | -- | -- | -- | -- |
| 1 | [M+H]+ | 98521 | 108368 | 62.55381 | 62.55381 |  
| 2 | [M+2H]2+ | 18025 | 154084 | 11.44459 | 73.9984 |  
| 3 | [M+H-H2O]+ | 13822 | 122190 | 8.77598 | 82.7744 |  
| 4 | [M-H]- | 9847 | 9847 | 6.25214 | 89.0265 |  
| 5 | [M+Na]+ | 8679 | 132030 | 5.51055 | 94.5371 |  
| 6 | [M+H-NH3]+ | 1882 | 134785 | 1.19494 | 95.7320 |  
| 7 | [M+NH4]+ | 1161 | 123351 | 0.73715 | 96.4692 |  
| 8 | [M-H-H2O]- | 545 | 132860 | 0.34604 | 96.8152 |  
| 9 | [M-H+2Na]+ | 519 | 136059 | 0.32953 | 97.1447 |  
| 10 | [M-H+H2O]- | 386 | 135220 | 0.24508 | 97.3898 |  
| 11 | [M+NH4-H2O]+ | 362 | 155654 | 0.22984 | 97.6197 |  
| 12 | [M+H+H2O]+ | 306 | 135536 | 0.19429 | 97.8139 |  
| 13 | [M+H+Na]2+ | 288 | 156878 | 0.18286 | 97.9968 |  
| 14 | [M+H+K]2+ | 276 | 156590 | 0.17524 | 98.1720 |  
| 15 | [M-2H]2- | 220 | 132315 | 0.13968 | 98.3117 |  
| 16 | [M+2Na]2+ | 217 | 156314 | 0.13778 | 98.4495 |  
| 17 | [M+2H-NH3]2+ | 216 | 155995 | 0.13714 | 98.5866 |  
| 18 | [M+K]+ | 215 | 154452 | 0.13651 | 98.7232 |  
| 19 | [M+H-2H2O]+ | 186 | 154751 | 0.11810 | 98.8413 |  
| 20 | [M+3H]3+ | 105 | 155779 | 0.06667 | 98.9079 |  
| 21 | [M+2H-H2O]2+ | 102 | 156097 | 0.06476 | 98.9727 |  
| 22 | [M]+. | 93 | 154177 | 0.05905 | 99.0317 |  
| 23 | [M+2Na-H]+ | 81 | 154868 | 0.05143 | 99.0832 |  
| 24 | [M-H+2K]+ | 80 | 157078 | 0.05079 | 99.1340 |  
| 25 | [M+H-CO]+ | 73 | 155128 | 0.04635 | 99.1803 |  
| 26 | [M+H-CO2]+ | 68 | 157179 | 0.04318 | 99.2235 |  
| 27 | [M+H-CH2O2]+ | 60 | 155193 | 0.03810 | 99.2616 |  
| 28 | [M-H-NH3]- | 59 | 154237 | 0.03746 | 99.2990 |  
| 29 | [M.Cl]- | 56 | 132086 | 0.03556 | 99.3346 |  
| 30 | [M+Li]+ | 49 | 134834 | 0.03111 | 99.3657 |

**Comment by justinjjvanderhooft** [comment]
The issue is that not all adducts are accurately recorded in the GNPS libraries (it relies on manual reporting) and there is of course a difference between what is present in actual datasets and in the spectral libraries, as naturally there is a bias toward the [M+H]+ and [M-H]- in the libraries. In the coming years, we may expect more adducts to make it into the libraries, but I think we currently capture a wide range of "naturally" occurring adducts with Ca and Fe as possible additions in positive mode to the list as they appear as well in some GNPS datasets and are likely to be added to GNPS spectral libraries. In the future, once Ion Identity Networking is more widely used, we could do another check once the adduct recording became more accurate as a result thereof?

**Comment by florian-huber** [comment]
Thanks, that's what I expected from the data as well. Most are indeed just `[M]+`, `[M+H]+` for positive ionmode. But at least with the additional functionality we should be able to better make use of the instances that do have a specific adduct in the metadata.

And for the Ca or Fe additions: Should we just wait and see what the data contains and add more adducts while we go (and of course when the data changes in the future)?

**Comment by justinjjvanderhooft** [comment]
Yes, good plan @florian-huber. I am curious about how many unique molecules we will get from the 210,000 GNPS spectra! 😎

**Comment by florian-huber** [comment]
Done with #170 .
@justinjjvanderhooft --> using matchms we go to about 150,000 annotated spectra. With further pubchem matching (making use of parent masses deduced from adducts as well) I could get to nearly 185,000 annotated spectra.

```
Inchis: 184755 -- 22494 unique
Smiles: 184718 -- 29919 unique
Inchikeys: 184698 -- 17738 unique (first 14 characters)
```
