### ISSUE TITLE
Fix bioconda recipe

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#178]
Nice to see that `matchms` has been added to Bioconda (https://github.com/bioconda/bioconda-recipes/pull/25425)!
Thanks @martenson.

The recipe takes the package from pypi's `.tar.gz` which we just realized does not contain the package data.
--> @sverhoeven suggested removing the `include_package_data=True` from `setup.py`

In addition I started a PR to update the dependencies: https://github.com/bioconda/bioconda-recipes/pull/26909

**Comment by florian-huber** [comment]
Once done, update badge (see https://anaconda.org/bioconda/matchms/badges).

**Comment by florian-huber** [comment]
With #179 the package_data is now in the bioconda package and it no longer fails.
I started a PR with bioconda to update the dependencies, but tests there are currently still failing...
See: https://github.com/bioconda/bioconda-recipes/pull/26909

**Comment by florian-huber** [comment]
Recipe changes for bioconda have been merged (https://github.com/bioconda/bioconda-recipes/pull/26909). 
That should correctly add rdkit.
However, for `matchms 0.8.1` there is now two builds (https://anaconda.org/bioconda/matchms/files), so running
```
conda create --name matchms python=3.8
conda activate matchms
conda install --channel bioconda matchms
```
...in my case used the build number 0 (without rdkit). This should be fixed with the next release I guess.

**Comment by sverhoeven** [comment]
I am trying to install the `matchms-0.8.1-pyh3252c3a_1.tar.bz2` from bioconda, but it is failing with

```shell
conda install -c bioconda matchms=0.8.1=pyh3252c3a_1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound: 
  - rdkit[version='>=2020.03.1']

```

I guess that is why it is installing build number=0.

Looking at https://anaconda.org/bioconda/rdkit/files there has not been an update since 4 years and is missing version 2020.03.1, while on conda-forge rdkit is much more recent.
Using `conda install -c conda-forge  -c bioconda matchms` made it install build=1.

**Comment by florian-huber** [comment]
added badge to readme and installation instructions (in the readme) are now `conda install -c conda-forge -c bioconda matchms`

**Comment by florian-huber** [comment]
Should work now, if not please reopen.
