### ISSUE TITLE
Remove Sonarcloud run from first CI test

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#182]
When refactoring the CI I didn't think of PR from forks. For those sonarcloud will not work (secret token can only be used from within the main repo). So we should remove sonarcloud from the first checks to not have them fail for external PRs! (e.g. #181)

**Comment by sverhoeven** [comment]
Weird at https://github.com/matchms/matchms/blob/a1896f8ffc26d2a4c8e2975c05081c8f808aae92/.github/workflows/CI_build.yml#L39 
you already check if PR comes from a fork. Seems PR #181 is using an old version.

**Comment by florian-huber** [comment]
Yes, I also just checked that, but found that `if: github.repository == 'matchms/matchms'` is correctly present (and it is up to date with our repo).

**Comment by florian-huber** [comment]
In #194 the test runs didn't trigger, not sure why. But seems our CI is not working smoothly with PRs from forks...
(this time not Sonarcloud was the issue, but the workflow wasn't running at all for the last commit)

**Comment by florian-huber** [comment]
Fixed in #378
