### ISSUE TITLE
MSP file with tabstopps causes error.

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#192]
**Describe the bug**
If the m/z and intensity value in a spectrum's peak are separated via a tabstop, `load_from_msp(...)` fails.
Tested with version 0.6.1 and 0.8.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download msp file from [here](https://www.recetox.muni.cz/media/3271419/recetox_gc-ei_ms_20201028.msp)
2. Run the following line to get the error
`spectra = [x for x in load_from_msp("...\\recetox_gc-ei_ms_20201028.msp")]`
3. Error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "C:\Users\473355\Miniconda3\envs\matchms\lib\site-packages\matchms\importing\load_from_msp.py", line 87, in load_from_msp
    for spectrum in parse_msp_file(filename):
  File "C:\Users\473355\Miniconda3\envs\matchms\lib\site-packages\matchms\importing\load_from_msp.py", line 43, in parse_msp_file
    masses.append(float(splitted_line[0]))
ValueError: could not convert string to float: '116.05576\t29277'
```

**Expected behavior**
The file is parsed correctly

**Desktop (please complete the following information):**
 - OS: Windows 10 64 Bit
 - Conda:
 ```
  active environment : matchms
    active env location : C:\Users\473355\Miniconda3\envs\matchms
            shell level : 2
       user config file : C:\Users\473355\.condarc
 populated config files : C:\Users\473355\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\473355\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\473355\Miniconda3\pkgs
                          C:\Users\473355\.conda\pkgs
                          C:\Users\473355\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\473355\Miniconda3\envs
                          C:\Users\473355\.conda\envs
                          C:\Users\473355\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

Thank you very much and feel free to reach out in case you need any further details - I'll be also happy to contribute.

**Comment by florian-huber** [comment]
I could reproduce the bug (using matchms 0.8.1).

@hechth would you be interested in doing a pull request?
A quick fix could be to change `splitted_line = rline.split(" ")` to `splitted_line = rline.split()` in `load_from_msp`, but that needs to be tested.

**Comment by hechth** [comment]
Yes, I will take care of it and pose it as a PR.

**Comment by hechth** [comment]
Should I also add tests for comparing read mz and intensity values? The current tests only check for correct inchi key which doesn't really reflect the actually tested scenario.

**Comment by florian-huber** [comment]
That would be great!
The current test is indeed too simple. And we should add another `.msp` file (ideally small, only containing few spectra) that used tab instead of spaces between m/z and intensities.

**Comment by hechth** [comment]
> That would be great!
> The current test is indeed too simple. And we should add another `.msp` file (ideally small, only containing few spectra) that used tab instead of spaces between m/z and intensities.

I already added a file containing that.

Okay, I will extend the tests a bit.
