### ISSUE TITLE
Discussion: adding networking tools to matchms

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#196]
In its current form, matchms has capabilities for
- importing data
- processing metadata
- processing spectrum data (peaks, losses)
- computing spectrum similarities
- basic score-based querying

In the `Spec2Vec` work we also created networks based on the matchms computed similarity scores. The functionalities are currently available as [`matchmsextras`](https://github.com/matchms/matchmsextras) to give them an accessible home without at the same time having to meet the higher code quality standards of matchms.

Many functions from `matchmsextras` do clearly not belong into matchms, such as many plotting functions we used for the article etc. But I do think that `molecular networking` (or GNPS-style molecular networking) has become such a common procedure that matchms would benefit from adding -at least basic- networking functionality. By basic I mean:
- creating a graph based on a list of spectrums and a similarity score
- export the graph to file (so that it can be imported in `Cytoscape` or other tools) 
- very basic python network plot
All of this is already available in matchmsextras (all based on `networkx` package) and would mostly just need refactoring.

It could look like this:
```python
# spectrums =[spectrum0, ... ]

from matchms.similarity import ModifiedCosine
from matchms.networking import SimilarityNetwork

similarity_measure = ModifiedCosine(tolerance=0.01)
spectral_network = SimilarityNetwork(spectrums, similarity_measure, cutoff=0.7)

# Export for later work in Cytoscape
spectral_network.graph_to_graphml("spectral_network.graphml")
spectral_network.metadata_to_csv("spectral_network_metadata.csv")
```

@sverhoeven @ridderl @justinjjvanderhooft @sdrogers what is your opinion on this?

**Comment by florian-huber** [comment]
Two other things: 
- Obviously that could be extended over time if there is interest and time (or even better: people taking it up!).
For instance adding network pruning functions etc.

- The aim here would of course not be to copy GNPS. It is more to close the gap for people that start working with Python and matchms but do not necessarily know how to get from the scores to a network. As with matchms, I think it all aims more towards researchers that want to build there own analysis workflows.

**Comment by justinjjvanderhooft** [comment]
Thanks for bringing this up here @florian-huber! My take is (as you can guess from earlier communications) that it would be a very useful extension to matchms (also because the items you mention are more or less there already) - and also because there is still so much to explore in mass spectral networking, especially in terms of the use of similarity scores, and also network topology filtering (dilation step, topK, pruning, etc.) which would be supported by matchms then. The collaboration we started with the alkaloid data could be nice opportunity to report the matchms upgrade.

Re extensions: yes, the matchms package is already being used by others and I expect that networking options will be a welcoming addition. I am trying to get funding to get to expand on this as well....fingers crossed!!

Re GNPS clone: I would rather see this as a nice way of examining how to obtain even more useful networks, and given that GNPS already has matchms up and running as well, if any novel scores or settings are produced through matchms, GNPS could make them available to their users.... 

By the way: this is also great for teaching purposes! :-)

**Comment by florian-huber** [comment]
Thanks for the feedback Justin!
(I indeed guessed that you would be in favor of adding some networking functionality 😉 )

Good point regarding GNPS and teaching purposes, there too some networking functions would indeed be very nice to have (ending a tutorial with a first network is much nicer than only having an array of scores).

I also had the same thought with respect to the collaboration we started with the alkaloid data. There we anyway wanted to explore/compare different "recipes" to build a molecular network. We could then at least add the most robust/promising functions to matchms as well.

**Comment by sverhoeven** [comment]
Looking at what matchms library does well now, preparing spectrums and calculating scores between them. I don't object to doing something with those scores in the library as well by adding network functionalities. 

We should be careful not to make a `networkms` library called `matchms`. Having the name of the package is not covering its core functionality that well anymore is something we should try to avoid.

**Comment by justinjjvanderhooft** [comment]
Also a good point @sverhoeven! I would suggest to only provide the basic functionality mentioned above in matchms - and when we feel we have enough momentum, we could create/branch off a separate package (networkms ?!) just like Spec2Vec is also built on top of matchms.

**Comment by florian-huber** [comment]
Thanks Stefan and Justin!
Keeping the focus somewhat clear (and in line with expectation based on the name) is indeed a good point.
And it looks like we will soon expand the similarity measures quiet a bit, which would be in line with keeping the spectrum processing and similarity score calculation the core focus.

Luckily "matchms" is also a bit open to interpretation ... networks are also a way of "matching" ms 😃...
As Justin suggested we can hence start within matchms, but should re-consider once we expand the networking functionality beyond the basics!
(the basic functions alone also feel a bit too small to make a good independent package)

So I will soon start adding the most basic functions (could become `matchms 0.9.0`).

**Comment by florian-huber** [comment]
Started working on #198 
(but the next 2-3 weeks I will have limited time for this... so that will stall or move slowly for that time)

**Comment by florian-huber** [comment]
Outdatad, basic networking functions are now part of matchms!
