### ISSUE TITLE
Create a tutorial

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms#2]
Create a tutorial: Jupyter notebook with a lightweight dataset

**Comment by florian-huber** [comment]
We now have a first tutorial (with additional parts to come in the next few days).
It is on [medium here](https://blog.esciencecenter.nl/build-your-own-mass-spectrometry-analysis-pipeline-in-python-using-matchms-part-i-d96c718c68ee).

The respective notebooks are currently in a "tutorial" branch, maybe they should soon go to an own repo?
Now they are here: https://github.com/matchms/matchms/blob/tutorial/tutorial/matchms_tutorial_01_building_analysis_pipeline.ipynb

Anyway, I will close this issue with this.
