### ISSUE TITLE
Wasserstein distance

### ISSUE THREAD

**Issue by Adafede** [matchms/matchms#202]
**My request is a new feature**
As matchms package will probably soon be the reference for computing similarities among spectra, would it be easily feasible to add the Wasserstein distance (or Earth mover's distance) as an additional similarity calculation possibility? 

**Describe the solution you'd like**
from matchms.similarity import WassersteinDistance ?

**Any good starting points?**
https://github.com/mciach/masserstein

**Additional context**
None

**Scientific reference**
https://doi.org/10.1002/rcm.8956

**Comment by florian-huber** [comment]
Good idea. I think there's also a scipy implementation that could be adapted: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wasserstein_distance.html
