### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by Adafede** [matchms/matchms#203]
Hi,

As the doc is soo good, I thought it would be nice to give you a very small list of hiccups I saw:

https://matchms.readthedocs.io/en/latest/api/matchms.importing.html

- "_matchs_" instead of  "_matchms_"

Not very useful but as I simply c/ced your example and it didn't work, I think other lazy users will surely do the same!

Maybe having a template for reporting doc small fixes would be great! :)

**Comment by florian-huber** [comment]
Thanks for the matchms compliments :)
And thanks for spotting those errors in the code example. Should be solved after #204
