### ISSUE TITLE
Expanding matchms similarity module

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#205]
Based on discussions with @hechth and Elliot James Price (as well as @justinjjvanderhooft and @sdrogers prior to that) we think it makes sense to further expand the `matchms.similarity` module. This also connects to #202 recently added by @Adafede.

This issues is made to discuss the upcoming additions in more detail.

### Sketching
- Select most relevant scores for a full addition to matchms:
Each of those would become an own similarity score within `matchms.similarity` following the style of `ModifiedCosine`, `FingerprintSimilarity` and others. 
- Construct a `CustomSimilarity` class that allows user to simply pass a custom function for computing similarity scores. For instance using functions currently provided in [Daphnis](https://github.com/YuanyueLi/Daphnis).

The advantage of this is that we can keep a good balance between being very rigorous with what we add to matchms while allowing users to quickly adapt/prototype/use any function they like. Scores that become part of matchms will undergo quiet some reviewing and testing, and often also some performance improvements. So it still makes sense to add frequently used ones to matchms (can be done one-by-one) to make things more reliable.

**Comment by hechth** [comment]
@florian-huber As discussed, I would start implementing the [Fidelity](https://en.wikipedia.org/wiki/Fidelity_of_quantum_states) distance as a first step by adding it as a class to the list of similarity metrics in matchMS.

This can serve as an initial prototype for future metric additions from the [Daphnis](https://github.com/YuanyueLi/Daphnis) repository.

The implementations of similar metrics in [philentropy](https://www.rdocumentation.org/packages/philentropy/versions/0.4.0) R package could serve as reference for eventual tests.

**Comment by hechth** [comment]
I started working on the Fidelity distance and have the  [class](https://github.com/hechth/matchms/blob/fidelity/matchms/similarity/Fidelity.py) and a first [test](https://github.com/hechth/matchms/blob/fidelity/tests/test_fidelity.py) ready - there are still some ambiguities with the calculation of the score which I want to resolve but it gives an initial idea of how the score could be implemented.

Should I fill in an issue and pose a resulting draft PR and continue development there so things are clearly visible for discussion?

**Comment by florian-huber** [comment]
Yes, if you want some feedback on your first draft version that that sounds like a good plan to me!
