### ISSUE TITLE
Consider adding mass <-> formula consistency check

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#207]
#199 brought up that have a check between the mass and the known formula would be a nice feature to remove spectra that seem less trustworthy. 

I imagine that could be done by adding a new filter: `require_mass_formula_match(spectrum, tolerance_ppm=10.0)`
This would compare the `parent_mass` (which is estimated through `add_parent_mass`) with the given formula (if present).

**Comment by sverhoeven** [comment]
You could use `rdkit.Chem.Atom('C').GetMass()` to calculate mass or use https://pypi.org/project/molmass/

**Comment by sdrogers** [comment]
I suggest making the filter name more explicit as to what mass is being compared to what? Parent mz?

The vast majority of spectra in the universe don’t have a chemical formula, so although useful it’s a bit of a niche feature for library spectra.

**Comment by hechth** [comment]
I also think this would be a good addition - I think using rdkit chem would be good to not add more dependencies.

I think these are alůso 2 filters or so, basically `derice_mass_from_formula` and `require_mass_formula_consistency` I assume?

**Comment by florian-huber** [comment]
Was added in recent pull requests by @niekdejonge .
