### ISSUE TITLE
find_matches function expects 2d array with m/z and intensity, but uses only m/z

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#208]
**Describe the bug**
The function is being given/passed information which is not necessary and used.
See https://github.com/matchms/matchms/blob/5cf15bcc89128f1bffacd62a8688062edfd8d06e/matchms/similarity/spectrum_similarity_functions.py#L50-87

**Expected behavior**
The function should take only the m/z values of the peaks, or the spectrum objects.
It could also become a class function of the spectrum, which would then ensure the assumption that the arrays are sorted.

**Additional context**
This would make the code more easy to read and concise, given that the Spectrum class already has a sorted list of only m/z values.

**Comment by florian-huber** [comment]
Good point, thanks @hechth for pointing this out.
The function could indeed be changed to only take the m/z values as inputs. 
(Spectrum objects were difficult because numba is picky about datatypes)
