### ISSUE TITLE
Move get_peaks_array function to utils.py or to Spectrum class

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#214]
The function should be moved to general utility since it also makes sense in other places, for example, msp export.

https://github.com/matchms/matchms/blob/5497b7363af1d555b8d1ab0162e01458ac7fbf53/matchms/similarity/spectrum_similarity_functions.py#L90-L92

**Comment by florian-huber** [comment]
True!
We could move it to matchms/matchms/utils.py.
But I actually believe it would be even better to add a new method to the `Spikes` class. 
Maybe something pandas-like, such as `.to_numpy()` ?

Then one could call
```python
peaks_array = spectrum.peaks.to_numpy
```
