### ISSUE TITLE
Add error reporting to msp reader

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#219]
**Describe the bug**
If reading an msp file, in case of failure, there should be additional information reported with the error, i.e the number of the problematic line etc.

**To Reproduce**
1. call 'load_from_msp' with an erronoes msp file
2. Observe the example error output attached below

**Expected behavior**
The program terminates with an informative error message, giving the User information about what went wrong and where.

**Screenshots**
```
    def parse_msp_file(filename: str) -> Generator[dict, None, None]:
        """Read msp file and parse info in list of spectrum dictionaries."""
    
        # Lists/dicts that will contain all params, masses and intensities of each molecule
        params = {}
        masses = []
        intensities = []
    
        # Peaks counter. Used to track and count the number of peaks
        peakscount = 0
    
        with open(filename, 'r', encoding='utf-8') as f:
            for line in f:
                rline = line.rstrip()
    
                if len(rline) == 0:
                    continue
    
                if ':' in rline:
                    # Obtaining the params
                    splitted_line = rline.split(":", 1)
                    if splitted_line[0].lower() == 'comments':
                        # Obtaining the parameters inside the comments index
                        for s in splitted_line[1][2:-1].split('" "'):
                            splitted_line = s.split("=", 1)
                            if splitted_line[0].lower() in params.keys() and splitted_line[0].lower() == 'smiles':
                                params[splitted_line[0].lower()+"_2"] = splitted_line[1].strip()
                            else:
                                params[splitted_line[0].lower()] = splitted_line[1].strip()
                    else:
                        params[splitted_line[0].lower()] = splitted_line[1].strip()
                else:
                    # Obtaining the masses and intensities
                    peakscount += 1
    
                    splitted_line = rline.split()
    
>                   masses.append(float(splitted_line[0]))
E                   ValueError: could not convert string to float: 'CC'
```
**Desktop (please complete the following information):**
 - OS: Windows
 - Python: 3.8.8
 - Version 0.82

**Comment by florian-huber** [comment]
That's indeed a good observation, and I fully agree: there should be a more informative error message (e.g. pointing to the line of the file etc.)!
We might also find similar issues for our other importing functions, probably worth checking at some point.

For the example you show here we could probably simply add a `try: ... except:` construction which will include the full line (and ideally also the line number) in its error message.
Let me know if you want to work on this @hechth. Otherwise I'll see when I get the time to pick this up.

**Comment by hechth** [comment]
@florian-huber I also don't know when I will actually get to this, it was just an observation I made while reading some msp files. I will assign the issue to myself as soon as I start working on it to indicate that!

Yes, printing the line number etc. and putting things into a try catch block (and eventually continuing on reading the next spectrum) would be also my idea.

**Comment by hechth** [comment]
@florian-huber Just out of curiosity, does matchMS utilize some form of logging? Maybe it would make sense to then also introduce some logger if the issue of error reporting is already being addressed?

**Comment by florian-huber** [comment]
I would really like to add some better logging! I made #71 a while ago and at some point even started working on it (#175) but never got the time to get this moving.
So I totally agree, matchms should get its own logger.

**Comment by hechth** [comment]
@florian-huber Then now might be a good time! Do you already have some preferred python logger in mind?

**Comment by Adafede** [comment]
Hi,

I take advantage of this issue already opened...I downloaded your set (https://zenodo.org/record/4699300#.YRS2X8Y69B1) and wanted to open it:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from matchms.importing import load_from_msp

print("""Open latest cleaned GNPS version""")

file_msp = "data/interim/spectra.msp"
spectrums = list(load_from_msp(file_msp))

print(spectrums)
```

which leads to:

```
Traceback (most recent call last):
  File "src/prepare_spectra.py", line 9, in <module>
    spectrums = list(load_from_msp(file_msp))
  File "/opt/anaconda3/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 115, in load_from_msp
    for spectrum in parse_msp_file(filename):
  File "/opt/anaconda3/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 40, in parse_msp_file
    if int(params['num peaks']) == peakscount:
KeyError: 'num peaks'
```

Any idea? Could it be because of the MSP size?

**Comment by florian-huber** [comment]
Hi @Adafede,
I could reproduce the error so I moved this to a separate, new issue: https://github.com/matchms/matchms/issues/246
And I will have a look at it asap!

**Comment by florian-huber** [comment]
We added logging in #271 so I guess this can be closed.

**Comment by florian-huber** [comment]
Actually I missed the first part of this issue and will make a new one --> #308
