### ISSUE TITLE
mz values are out of order (load_from_mgf)

### ISSUE THREAD

**Issue by ekopylova** [matchms/matchms#235]
Hello,

I would like to read a ```mgf``` file using the following code:

```spectra = list(load_from_mgf(input_mgf_fp))```

However, I receive the error message:

```
  File "/miniconda/envs/matchms/lib/python3.8/site-packages/matchms/Spikes.py", line 18, in __init__
    assert self._is_sorted(), "mz values are out of order."
```

How should the ```mgf``` file be preprocessed to remove this error? The file was generated by mzMine2.

Thanks!

**Comment by florian-huber** [comment]
Thanks @ekopylova for making this issue!
I would imagine that the current matchms function wants the peaks of a spectrum to be sorted by m/z. If mzMine2 is returning files where this is not the case, than we could in principle add a sorting step to the importer function.
 
Could you share a .mgf file with me where you get this error? Then I could have a look and see what we can do about this.
(If it is data you don't want to share or which is very bug, then feel free to adapt/remove metadata or copy/past only a part of it)

**Comment by florian-huber** [comment]
I didn't get any files/examples to reproduce this. So I will close the issue.
Please feel free to re-open if this continues to be a problem!
