### ISSUE TITLE
Move release instructions to README

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms#24]
Move https://github.com/matchms/matchms/blob/master/CONTRIBUTING.md#you-want-to-make-a-new-release-of-the-code-base Under https://github.com/matchms/matchms/tree/fix-anaconda-build#documentation-for-developers

**Comment by florian-huber** [comment]
Did you mean moving the link to right after the readme header ``Documentation for developers`` ?
Or to also merge the documents?

**Comment by sverhoeven** [comment]
Keep the CONTRIBUTING guide it answers questions for potential developers. The release instructions are for a core matchms developer. Maybe README is also not the best place as release instructions can be distracting there, maybe move chapter to own RELEASE.md file.

**Comment by florian-huber** [comment]
Outdated, please reopen if this is is important to consider right now.
