### ISSUE TITLE
Import error for matchms.networking

### ISSUE THREAD

**Issue by ArnaudGaudry** [matchms/matchms#241]
Hi there!
I installed matchms using bioconda, everything works well, except the matchms.networking module that I can not import (from matchms.networking import SimilarityNetwork returns ModuleNotFoundError: No module named 'matchms.networking'). I have v0.9.1 of matchms.
Thanks for you help!

**Comment by florian-huber** [comment]
I will try to soon have a look at this!

One check I would be interested in is to see if `networkx` has been added to the environment. Maybe you can quickly check by running `pip list`?
If it hasn't been installed that might already explain why `matchms.networking` cannot be used/imported.

**Comment by ArnaudGaudry** [comment]
Thanks for the quick answer! Networkx is indeed installed.
In fact, when I copy/paste the different functions/class (get_top_hits, create_network, SimilarityNetwork) into the script directly it works like a charm.

**Comment by florian-huber** [comment]
OK, great, thanks!
I will check a few other things then. Could be that the `networking` module was just missing from `__init__.py` --> I'll test that in #243 .

**Comment by florian-huber** [comment]
I just checked, and our own tests (`conda_verify`) also fail. So I will do some changes to fix this.
- Adding the module to init.
- Adding `networkx` to bioconda --> https://github.com/bioconda/bioconda-recipes/pull/29405
- (if necessary): also add module to bioconda as well.

**Comment by ArnaudGaudry** [comment]
Great thanks!

**Comment by florian-huber** [comment]
The last verify run passed (https://github.com/matchms/matchms/actions/runs/1002233563), so I consider this issue fixed. Please re-open if the import of the networking module still does not work.
