### ISSUE TITLE
Error when loading msp file

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#246]
Reported by @Adafede:

> Hi,
> 
> I take advantage of this issue already opened...I downloaded your set (https://zenodo.org/record/4699300#.YRS2X8Y69B1) and wanted to open it:
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> from matchms.importing import load_from_msp
> 
> print("""Open latest cleaned GNPS version""")
> 
> file_msp = "data/interim/spectra.msp"
> spectrums = list(load_from_msp(file_msp))
> 
> print(spectrums)
> ```
> 
> which leads to:
> 
> ```
> Traceback (most recent call last):
>   File "src/prepare_spectra.py", line 9, in <module>
>     spectrums = list(load_from_msp(file_msp))
>   File "/opt/anaconda3/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 115, in load_from_msp
>     for spectrum in parse_msp_file(filename):
>   File "/opt/anaconda3/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 40, in parse_msp_file
>     if int(params['num peaks']) == peakscount:
> KeyError: 'num peaks'
> ```
> 
> Any idea? Could it be because of the MSP size?

**Comment by Adafede** [comment]
Sorry for not making a new issue directly, thought it could be somehow related...

**Comment by florian-huber** [comment]
The problem was that the `.msp` file on zenodo was created with an older version of matchms which did not write the parameter `NUM PEAKS:` into the file.

I will upload the repaired msp file.

**Comment by florian-huber** [comment]
The new file is now on zenodo --> https://doi.org/10.5281/zenodo.5186176

@Adafede please check if this works for you now.

Since loading is slow, you could also monitor the progress, e.g. by:
```python
import os
from tqdm.notebook import tqdm  # or from tqdm import tqdm if not running in a notebook
from matchms.importing import load_from_msp

print("""Open latest cleaned GNPS version""")

file_msp = os.path.join(os.getcwd(), "data", "interim", "ALL_GNPS_210125_matchms_pubchem_cleaned_v2.msp")
spectrums = []
for spec in tqdm(load_from_msp(file_msp)):
    spectrums.append(spec)
```

**Comment by Adafede** [comment]
Works like a charm, thanks a lot @florian-huber !

**Comment by florian-huber** [comment]
Thanks @Adafede! Great to see it work.
I'll hence close this issue.
