### ISSUE TITLE
Add handling MSP files with peak comments

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#249]
**Is your feature request related to a problem? Please describe.**
Currently, matchms doesn't handle comments in MSP files ([example file](https://github.com/matchms/matchms/blob/master/tests/rcx_gc-ei_ms_20201028_perylene.msp). This functionality could be added.

**Describe the solution you'd like**
Adding a `comments` attribute to the `Spikes` class which holds an array of all comments. Non-existing comments can be represented as `None`.

This option (unfortunately) would require quite substantial changes. One more option would be to add the optional comments as a `dict` or indexed list (index being the peak number to which the comment belongs) to the `Spectrum` class.

Another option would be to replace the complete `Spikes` classes internal data handling with a powerful framework like `pandas`, but I'm not sure whether this is intended (I myself am not sure if this is really necessary or the best solution, so I'm open to suggestions!).

**Comment by florian-huber** [comment]
Hi @hechth !
So far, we kept the `Spikes` class fairly minimal and only designed it for the peaks itself (m/z and intensities). So, we didn't add things like precursor m/z etc. explicitly either. I wonder why we would need to do this for `comments` (which seems less essential). 

In the current design, comments would be added to the `metadata` of `Spectrum` and we as far as I see we would only have to change the MSP exporting function. The importing function should already add the comments field to the metadata. Wouldn't that do? (maybe I'm overlooking things...)

A side not: `Spectrum` objects now store the metadata as a normal Python dictionary. If there's enough added bonus it might indeed be worth considering using DataFrames instead in the future.

**Comment by hechth** [comment]
@florian-huber thanks for the explanations and the quick response! Yeah, I've seen that the `Spikes` class is very minimal and only for the peaks. The problem I'm talking about are the comments which can be added to a peak as can be seen in the example below:

```
NAME: Perylene
SCANNUMBER: -1
RETENTIONTIME: -1
RETENTIONINDEX: 2886.9
PRECURSORMZ: 252.09323
PRECURSORTYPE: [M]+
IONMODE: Positive
SPECTRUMTYPE: Centroid
FORMULA: C20H12
INCHIKEY: CSHWQDPOILHKBI-UHFFFAOYSA-N
INCHI: 
SMILES: C1=CC2=C3C(=C1)C1=CC=CC4=C1C(=CC=C4)C3=CC=C2
AUTHORS: Price et al., RECETOX, Masaryk University (CZ)
COLLISIONENERGY: 70eV
INSTRUMENT: Q Exactive GC Orbitrap GC-MS/MS
INSTRUMENTTYPE: GC-EI-Orbitrap
IONIZATION: EI+
LICENSE: CC BY-NC
COMMENT: 
Num Peaks: 19
112.03071	49892
113.03854	87510	"Theoretical m/z 113.039125, Mass diff 0 (0 ppm), Formula C9H5"
124.03076	100146
124.53242	24923
125.03855	179254	"Theoretical m/z 125.039125, Mass diff 0 (0 ppm), Formula C10H5"
125.54019	49039
126.04636	131679
126.54804	36313
222.04645	28905
224.06192	55632
226.04175	37413
246.04646	23286
248.06204	140007
249.07072	62236	"Theoretical m/z 249.070425, Mass diff -0.001 (0 ppm), Formula C20H9"
250.07765	641789
251.07967	137600
252.09323	1955166	"Theoretical m/z 252.093354, Mass diff 0 (0.49 ppm), SMILES C1=CC=2C=CC=C3C4=CC=CC5=CC=CC(C(=C1)C23)=C54, Annotation [C20H12]+, Rule of HR False"
253.09656	402252
254.09985	39987
```

But I think adding it as an attribute to the spectrum class and then having an index to the reference peak might be the best solution for now, in order not to disturb the spike data structure and keep it separated from that. It is not the most elegant solution though - I might think about it a bit more before actually starting some implementation.

**Comment by florian-huber** [comment]
Ah, OK I see. (I didn't scroll down enough and only saw the `COMMENT:` field...)
That's indeed a bit more tricky.

**Comment by hechth** [comment]
No problem - I will post it here once I have more approaches how to implement it.

The reason why supporting this would be good is due to MS-DIAL and MS-FINDER, they are capable of adding these comments to the MSP to annotate individual peaks - this is especially useful for GC spectra since the SMILES for the suspected compound of the peak can be annotated, giving also improved visualizations in MS-LIMA.

**Comment by maximskorik** [comment]
Hi both, I'm trying to work out a solution to this issue. Is it safe to assume that the comments are always going to be enclosed in quotation marks?

**Comment by hechth** [comment]
> Hi both, I'm trying to work out a solution to this issue. Is it safe to assume that the comments are always going to be enclosed in quotation marks?

Yes, as they mostly come from MS-FINDER

**Comment by florian-huber** [comment]
Work in progress in #277

**Comment by florian-huber** [comment]
PR by @maximskorik looks fairly good now (#284). I added a few suggestions from my side here: #287
