### ISSUE TITLE
Missing logger for word2vec model training

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#25]
Depending on the number of epochs, the number of documents, and the size of the documents, model training can take a while. In my view, some type of logger is really needed to see that the process is working fine. For now I just used the following:
```python
from gensim.models.callbacks import CallbackAny2Vec


class EpochLogger(CallbackAny2Vec):
    """Callback to log information about training progress.
    Used to keep track of gensim model training"""

    def __init__(self, num_of_epochs):
        self.epoch = 0
        self.num_of_epochs = num_of_epochs
        self.loss = 0

    def on_epoch_end(self, model):
        """Return progress of model training"""
        loss = model.get_latest_training_loss()
        # loss_now = loss - self.loss_to_be_subed
        print('\r',
              ' Epoch ' + str(self.epoch+1) + ' of ' + str(self.num_of_epochs) + '.',
              end="")
        print('Change in loss after epoch {}: {}'.format(self.epoch+1, loss - self.loss))
        self.epoch += 1
        self.loss = loss
```
Maybe we can add something along those lines to spec2vec such that people could simply import it.
```python
from spec2vec import EpochLogger
...
```

**Comment by cwmeijer** [comment]
I used to use ProgressBar2 for this but it seems there are nicer ones out there now:
https://pypi.org/project/progress/
Or tqdm with more fancy options (even though build is failing at the moment) as showcased in:
https://stackoverflow.com/a/26761413

**Comment by cwmeijer** [comment]
I used to use ProgressBar2 for this but it seems there are nicer ones out there now:
https://pypi.org/project/progress/
Or tqdm with more fancy options (even though build is failing at the moment) as showcased in:
https://stackoverflow.com/a/26761413

**Comment by florian-huber** [comment]
Looks nice. For me it doesn't have to be fancier that the first option you mention :)
We could maybe also use them (as an option) for other lengthy calculation steps.

**Comment by sverhoeven** [comment]
I like https://tqdm.github.io/ as a progressbar.

**Comment by florian-huber** [comment]
Is now part of spec2vec (and was addressed there).
