### ISSUE TITLE
Add RI filtering to matching process

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#251]
**Is your feature request related to a problem? Please describe.**
The retention time/index of a mass spectrum is an additional source of information that can be used to find the best matches, as it is an orthogonal piece of information.

**Describe the solution you'd like**
To find the spectra which are to be matched to a compound, a simple RI filter based on a set threshold can be used to remove the compounds which don't fall into this range.

**Comment by florian-huber** [comment]
I agree, including the retention time would be nice!
Were you thinking of an additional filter function (under `matchms.filtering`) together with the retention time being added metadata of the spectra?

**Comment by hechth** [comment]
This is a tricky one: for the RI, we'd actually like to apply the filter for each spectrum while matching.

Example:
I want to match spectra A, B and C with RIs 1300, 1400 and 1450 to the reference library with spectra D, E and F with RI 1350, 1400 and 1500. I specify an RI tolerance of 60.

The filtering should therefore then only result in matches of A to D, B to D and E and C to E and F.
This means that the filter should act per spectrum, not per actual score matrix computation.

I imagine multiple options to implement this:
1. As a post-processing step -> but this takes away the performance benefit of having to compare less spectra
2. As a pre-processing step -> this removes the matrix-style operation, but might not be that bad performance-wise.

This actually means that it would be more a part of the matching than the filtering.

If it should only be inside the filtering, then one way would be to just match always a single spectrum to the reference library and iterate the filtering and matching step.

@florian-huber Any ideas or hints on that?

**Comment by sdrogers** [comment]
Hola
I wonder if it could still be done within the matrix world - it would be easy enough to make a spec by spec masking matrix (with 1 where the difference is within a limit) and then skip these in the loop to compute scores (or just multiply the score matrix in the end element wise with the mask, if vectorising still proves quicker?)
Is the precursor mass match filter done as a post-process? Because it’s basically the same operation…

**Comment by florian-huber** [comment]
OK, thanks @hechth! I think I now understand better what you meant.
And I basically would agree with @sdrogers . The RI matching is very similar to the `PrecursorMzMatch` which will simply output a matrix of 1 and 0 (True/False) for matches within tolerance or not. That's a very fast operation.

The way I see it we should indeed add some masking functionality to the score calculation. That would be nice for your RI matching, but it would also make sense for other piplines, say computing Cosine score, but only if the precursor-m/z are within a decent tolerance etc.

```python
from matchms import calculate_scores_pipeline, Spectrum
from matchms.similarity import CosineGreedy, MetadataMatch

spectrums_1 = [...]
spectrums_2 = [...]

scores = calculate_scores_pipeline(spectrums_1, spectrums_2,
                                   mask=MetadataMatch(field="retention_time", tolerance=60.0),
                                   score=CosineGreedy())
```
That would return `Scores` object where `Scores.scores` is a matrix with Cosine scores for all pairs for which the retention_time is within the tolerance. All other values would be zero.

**Comment by hechth** [comment]
@sdrogers thanks for the input, yes, this sounds like a very elegant solution!

@florian-huber This metadata match seems like a versatile solution. It requires quite some user knowledge on the data, but I think making this assumption is legit and it keeps the library versatile and flexible - and enables quite some sophisticated filtering or masking.

**Comment by sdrogers** [comment]
Re user knowledge - it would probably be easy enough to make wrappers that would make it straightforward for some standard use cases. Only worthwhile making those if we’re confident that the input data are actually standard enough? I recall previous frustrations with RT switching between seconds and minutes (!!) depending on which software had done the pre-processing.

**Comment by hechth** [comment]
@sdrogers I agree on the wrappers. I was also dealing with RT in different units (minutes/seconds) before, but without significant overhead there is no really nice solution, especially since it is usually not specified in an MSP which unit is present - it just has to be deduced, but doing that automatically isn't possible IMHO.

**Comment by sdrogers** [comment]
Then yes, I think @florian-huber’s suggestion is the best bet.

One q: do metadata values get parser to numeric types when loaded? If not, could have the user also pass a function for conversion to the MetadaMatch (default would float). So that, eg, someone could provide a bespoke method that converted eg minutes to seconds at the same time. Or, the user provides a method that will be passed two metadata dicts and returns true / false?

**Comment by hechth** [comment]
@sdrogers I think the filters are actually doing these things, making sure that a metadata field is in the right format and numerical types etc.

@florian-huber Is this correct?

If so, I'd also implement a filter that adds retention time (if that doesn't exist yet) and retention index to the spectra, so the user can be sure that these are in the correct format.

**Comment by florian-huber** [comment]
As far as I see it, we only parse values to numeric types for a few specific cases (precursor mz, charge).
For those we indeed have the filters that take care that the fields are consistent.

One problem with this is also that the different importers are not harmonized. Some use pyteomics (e.g. `load_from_mgf()`), others have our own parsers (e.g. `load_from_mzml()`).

**Comment by florian-huber** [comment]
With the currently added filters to harmonize RI and RT and the new `MetadataMatch` score (#315) this should be doable now. If not, please re-open or start a new issue.
