### ISSUE TITLE
Add retention data filters

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#260]
As discussed in #251 , adding RI and RT filters to clean the metadata in the spectrum object would be good.

One additional idea would be for the retention time filter to allow passing a conversion factor which converts the RT to seconds and use this as a canonical unit for RT?

**Comment by florian-huber** [comment]
Adding a filter for retention time seems a good idea to me!

If we get more and more of such filters, we could at some point also think about combining them into one wrapper function, e.g. `metadata_filtering()` or `metadata_harmonization()`.
For now, we can simply add the new filter to `default_filters()`.

**Comment by niekdejonge** [comment]
Wanted to create the same issue. 

Two retention time formats I came across are:
For MZXML
'retention_time': [0.057168]
For MZML
'scan_start_time': [0.629566666667]
Only checked a few instances of these file types so not sure if this is consistent for these file types, but these are for sure formats used.

**Comment by hechth** [comment]
@niekdejonge Thanks for the hint, so I think it would make sense to respect these keys in the metadata :)

**Comment by hechth** [comment]
@florian-huber Is there a canonical way of how to proceed if the value is not available in the spectrum? I can see that sometimes the input spectrum is returned as is? What should happen if the field is present, but in a form that can't be converted to the correct type, should it then be removed?

Maybe it would also make sense to pass a key in the function in case the user knows which key they want to add?

**Comment by florian-huber** [comment]
That's a very good point. To discuss this further I opened #263. 
If I remember correctly (please let me know if not) then all filters will simply return unchanged spectra if en entry is missing except for filters that are explicitely named `require_xyz()`.

To the second part of your question: for entries we can't handle/convert --> that indeed might be inconsistent. I know that some functions will replace that by `"n/a"`(e.g. `derive_ionmode()`) but in other cases the values might remain unchanged.
