### ISSUE TITLE
Make filter "strictness" more consistent (and revisit design)

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#263]
Over the time the number of filters in `matchms.filtering` has grown (and continues to grow).
It seems about time to revisit them and check consistency regarding missing or false entries: 

+ How do filters handle 1) missing and 2) incorrect (= not usable for the intendet purpose) entries?
Some will only do stuff when possible and return unchanged spectra otherwise (e.g. `add_fingerprint()`), others will print a warning (e.g. `add_parent_mass()`). 
--> Should be consistens (see also missing logging #71 )

+ Currently we have `add_xyz()` type of filters, or -very similer- `derive_xyz_from_abx()` type of filters to add field entries. Those won't fail if an entry is not found. Stricter processing can be achieved by combining with a second filter of type `require_xyz()`.
I wonder if adding a `strictness` parameter to the filters would make that workflow easier?

**Comment by hechth** [comment]
I agree with the requirement/strictness thing, since we eventually want to ensure everything has something, otherwise, fail, but sometimes we might also just reduce the input data and _filter_ the ones for which deriving/adding metadata can be done successfully.

**Comment by florian-huber** [comment]
While implemting the logging (#271) I will also try to make the filter outputs a bit more consistent.

**Comment by florian-huber** [comment]
Outdated.
