### ISSUE TITLE
Move to matchms 1.0.0

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#269]
Recently matchms got some nice additions and refactorings, which just got released -> `matchms 0.10.0`!
And more and more people seem to use it for their projects.

As far as I see it, the general API of matchms is not about to change anytime soon. And it is runnning stable for quite a while now. Which (to me) means we can soon release version 1.0.0.

Maybe we could collect the items we still want to add/change before doing that.
I could think of:
+ proper logging (#71) ?
+ masking-pipline (see #268) ?

What would you say @sverhoeven, @sdrogers, @hechth ?

**Comment by hechth** [comment]
I agree, this would be nice to implement and then move on to publishing version 1.0.0. Maybe we can also still include the test refactorings? It will take a bit of time but I think would be worth it.

So basically getting one more version on the functionality and then having some bug-fixing and cleanup and then publish :)
This might also include #263

**Comment by florian-huber** [comment]
This will essentially be what is described now in #376
