### ISSUE TITLE
Precursor m/z format issue

### ISSUE THREAD

**Issue by janusson** [matchms/matchms#273]
**Describe the bug**
get_matching_pairs() function in ModifiedCosine.py crashes when passed a precursor_mz which is a string.

**To Reproduce**
Pass an MGF with string m/z values ('234.97' vs 234.97).

**Expected behavior**
Handle an integer or string value from MGF source.

**Desktop (please complete the following information):**
 - OS: Windpws

** Suggested fix **
Draft pull request to submit:
https://github.com/matchms/matchms/pull/272

**Comment by florian-huber** [comment]
Thanks @janusson for raising this issue!

We already have a function to take care of handling string entries : [`filtering.add_precursor_mz()`](https://github.com/matchms/matchms/blob/5e0b03924dcee13d13b5504c52a539b2c1701d5d/matchms/filtering/add_precursor_mz.py)
But I see that the case in which this filter was not run and the entries are still of type string is currrently not handeled well.
- I will add better warnings/error messages
- we can discuss about including part of the transformation done in `add_precursor_mz`  to the function as well.

**Comment by janusson** [comment]
Thanks Florian, huge fan of your work.

**Comment by florian-huber** [comment]
#275 will now give a warning but handle strings which can be converted to float.

**Comment by florian-huber** [comment]
#275 was merged and should fix this issue. Please simply re-open if not.
