### ISSUE TITLE
File extension must be 'msp'

### ISSUE THREAD

**Issue by xtrojak** [matchms/matchms#274]
**Is your feature request related to a problem? Please describe.**
File extension must be `.msp` when [saving](https://github.com/matchms/matchms/blob/ebc3d622ba8bcf581c5ce36c951d68dee13937bd/matchms/exporting/save_as_msp.py#L8) spectrum(s) as `msp` file. 

**Describe the solution you'd like**
This is ensured by an [assertion](https://github.com/matchms/matchms/blob/ebc3d622ba8bcf581c5ce36c951d68dee13937bd/matchms/exporting/save_as_msp.py#L39), which could be removed.

**Additional context**
This requirement is strict to some external tools which use unified filename conventions (e.g. [Galaxy](https://galaxyproject.org/) is using `.dat` extensions). Moreover, such an extension is not required when [loading](https://github.com/matchms/matchms/blob/ebc3d622ba8bcf581c5ce36c951d68dee13937bd/matchms/importing/load_from_msp.py#L88) `msp` spectra files.

**Comment by florian-huber** [comment]
Hi @xtrojak, thanks for making this issue.
I agree that this assertion should go and will add the changes soon.

**Comment by florian-huber** [comment]
I (partly) removed the assertion in #276.
The function will now work for all file extensions (except if you use mzml, mzxml, json, or mgf).
It will add a logger warning though. Would that work for your use case @xtrojak ?

**Comment by florian-huber** [comment]
I would guess that #276 fixes this issue. If it does not, please simply re-open!

**Comment by xtrojak** [comment]
Yes, that looks good @florian-huber. Thank you!
