### ISSUE TITLE
Using matchms to perform library search.

### ISSUE THREAD

**Issue by adelabriere** [matchms/matchms#281]
Dear @florian-huber ,

I am currently developping a solution for annotation of metabolomics data, which notably includes results from MS-MS library matches as an input. As the tool is in python, I would like to have a python only solution to the problem, at the moment I use the GNPS library matches as examples. This would require, given a spectrum:

1. Find a set of MS2 spectra with matching precursors.
2. Compute all the similarities between the query and the references spectra,
3. Return the structure associated to each spectrum.

Looking at the doc and the code, it seems to me that matchms only allow to solve point 2. Is there a plan to expand it to allow to also perform 1. and eventually 3. ? Is there already a way to do this that I missed ? Or is this out-of-scope for matchms.

Thanks,
Alexis

**Comment by florian-huber** [comment]
Hi @adelabriere.

Thanks for raising this.
- If I get it right, then (1) is already part of matchms [similarity module](https://matchms.readthedocs.io/en/latest/api/matchms.similarity.html). You could simply use [`PrecursorMzMatch`](https://matchms.readthedocs.io/en/latest/api/matchms.similarity.PrecursorMzMatch.html#module-matchms.similarity.PrecursorMzMatch) which allows you to compare precursor_mz values based on a `tolerance` and tolerance-type such as `Dalton` or `ppm`.

- For (3) I am not sure. In what form would you like to get the structure. Many current matchms workflows will handle inchi and smiles as part of the metadata. But maybe you mean something else here?

**Comment by adelabriere** [comment]
Thanks for your reactivity.

Yes I missed 1. that should do it. For 3 I guess that is a solution. My only problem is that there is no standard way to incorporate inchi, so I can't include a generic example that a user can use on his data out-of-the-box. But that is definitely not a matchms problem. 

Thanks for your answer. I ll try include an example with the structure given as metadata in an MGF.

**Comment by Adafede** [comment]
Hi @adelabriere, 

Maybe worth giving a look at: https://github.com/mandelbrot-project/spectral_lib_matcher? 

(We are using matchms)

**Comment by hechth** [comment]
@Adafede and @adelabriere can this be closed?

**Comment by Adafede** [comment]
The issue can be closed for me, I was already in contact with @florian-huber on how to best replace https://github.com/mandelbrot-project/spectral_lib_matcher with an appropriate matchms `pipeline`. Work in progress 😊
