### ISSUE TITLE
Revisit spectrum plotting

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#282]
Currently, `Spectrum` objects have a simple plotting function. That could be improved in a number of ways:

- move the actual function out of the `Spectrum` class so that it can also be used elsewhere
- add option to visually compare spectra
- check for other libraries to visually plot/inspect spectra and see if we could use them
- revisit design/layout, for instance switch from pyplot to OO-style so that it returns an axes object which could be used for further plots elsewhere.

**Comment by florian-huber** [comment]
if peaks comments are included (see #277) , maybe those could (optionally) be added as well ?

**Comment by sdrogers** [comment]
The met spec resolver allows (I think) peak data to be passed straight into the url now. Not suggesting it as a complete replacement for local plotting, but would be a useful addition. Something like:

Spectrum.generate_usi_url()

**Comment by florian-huber** [comment]
Nice suggestion @sdrogers !

For the local plotting, I will look into using [spectrum_utils](https://github.com/bittremieux/spectrum_utils).

**Comment by florian-huber** [comment]
`spectrum_utils` is a nice small package. But it doesn't fully connect to matchms. I now started to build an updated visualization module within matchms using parts of their code. #303
