### ISSUE TITLE
Revisit Spectrum class

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#283]
A moving target, but it keeps coming back... the (nearly philosophical) question of what a spectrum is :smirk: 

In matchms we have the `Spectrum` class to contain everything that (for matchms workflows) belongs to a spectrum.
That is
- `peaks`: essentially mz/intensity pairs
- `metadata`: a dictionary containing all kind of things (compound name, precursor mz etc.)
Those are not very controversion I guess, except maybe for the formats and the fact that metadata is an undefined collection of things.

But we also have
- `losses`: which are mz differences between precursor and fragement peaks
Those are used by some algorithms and can be very useful (e.g. MS2LDA), but they are not a standard thing. Plus having those as part of the objects has a few issue, at least design wise:
(1) They are very cheap to compute so it could be an option to not store them in memory, but only compute them when required
(2) They are not yet included in the importing/exporting part (people don't read/write them to mzml or mgf files etc., and matchms doesn't do it either)

With #277 we are now considering to also add
- `peak_comments`: a dictionary containing annotations for individual peaks
Here, one question is if we should have it seperate or as part of ' metadata'

**Comment by florian-huber** [comment]
Few more ideas on that:

We could build `Spectrum` around 2 main other classes:

### `Spikes` 
(by the way: maybe `Fragments` would be a better name!)

- Contains the mz / intensitites pairs.
- `losses` will be a method to compute them on the fly

### `Metadata`
- That could be a new class around a dictionary or sorted dictionary
- It could do some operations which we now do in the filtering step automatically, per default, such as converting charge to int or run `add_precursor_my`. 
- Those filters could become default methods of `Metadata` which are combined in one wrapper (say `.harmonize()`). This is called in __init__() and in the setter method.
- The respective filter would have to be adapted a bit. And I think replaced values should also be removed.

Peak comments could be part of either `Metadata` or `Spikes`, but I would rather say metadata.

**Comment by florian-huber** [comment]
... Guess I have to start a developments branch soon.

**Comment by florian-huber** [comment]
Started working on it in developments branch: https://github.com/matchms/matchms/tree/development

**Comment by hechth** [comment]
I think the spikes and metadata classes are kind of clear and clean. The metadata can also by time be actually made more canonical and some dictionary keys could take the form of attributes, so that the remaining code can rely on using those, and they are initialized by the filters.

The peak comments are problematic though as they are somewhere in between. They are metadata but they need to know about the peaks.

**Comment by florian-huber** [comment]
Thanks for the feedback.
Where would you think attributes make sense? 
As
```python
spectrum.metadata.precursor_mz
```
Or implement them such that you can get them as
```python
spectrum.precursor_mz
```

I would guess that the later could be nice for the most common entries, such as `precursor_mz`, `compound_name`, `ionmode`, `charge`

**Comment by florian-huber** [comment]
Also coming back to your comment on the peak-comments: I agree that they are somewhat in-between. 
Right now in #287 I moved the peak-comments into `metadata`, but the `Spectrum` class will still contain a method to reiterate the comments whenever the peaks get updated. If the peak comments proof to become a very popular thing we can still make them a class on their own, but for now I would like to avoid making them too prominent.

**Comment by florian-huber** [comment]
A lot of this is now addressed in #293 .
What remains is: 

- remove the `add_losses()` filter and make `losses` a method rather than an attribute in the `Spectrum` class (losses don't have to be stored!).
- maybe: add properties for most frequently used metadata entries (e.g. `spectrum.precursor_mz`)

**Comment by florian-huber** [comment]
remaining part of this issue is now in #319
