### ISSUE TITLE
More user friendly = more defaults

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#294]
In the past, users of matchms frequently ran into issues because they did not completely follow the matchms protocols/examples. Usually that means skipping a few filters, because how should you -as a user- know which of those many functions to call from `matchms.filtering`.

Originally this came from the believe of "don't change any data unless it was decided by the user".
But seing how people use matchms most of the time, I now think it would be better to set a few defaults right away. Nothing really altering the quantitative parts of the data, but stuff to harmonize common fields.

For this I now implemented a new `Metadata` class (currently still [development](https://github.com/matchms/matchms/tree/development)). This internally uses [PickyDict](https://github.com/florian-huber/pickydict) which makes it much easier to harmonize keys/field names. Now the question is: **Which fields do we want to harmonize per default?**  
(such default field name changes can of course be switched of by the user if desired)

- all lower key
- "_" instead of spaces
- "precursor_mass", "precursormass", "pepmass", "precursor_mz"  --> "precursor_mz" 
- "compound_name", "title", "name"  --> "compound_name"
- "ionmode", "ion_mode" --> "ionmode"
- "retention_time", "retentiontime", "rt", "scan_start_time", "RT_Query" --> "retention_time"
- "retention_index", "retentionindex", "ri" --> "retention_index"

**Comment by florian-huber** [comment]
@hechth @niekdejonge @sdrogers @justinjjvanderhooft @ArnaudGaudry @oolonek @lfnothias let me know if you frequently encounter other inconsistently named fields.

**Comment by florian-huber** [comment]
Got some replies via twitter also mentioning:
- collision energy
- precursor intensity
- "points along the spectra should be standardized too ("x","y", "m/z-int", etc.)"
- m/z window
- lambda parameter of isotope intensity distribution
- optional: fine isotopic structure

also learned that 
- "precursorCharge", "precursor_charge" and "charge" should be harmonized

**Comment by florian-huber** [comment]
Further feedback I got was to align things with MSP MGF standards. Something that many people have worked on or are working on.

Some more information:
- https://github.com/MassBank/MassBank-web/blob/main/Documentation/MassBankRecordFormat.md
- https://github.com/HUPO-PSI/mzSpecLib
- https://github.com/HUPO-PSI/mzSpecLib/tree/master/specification

Based on such extensive lists I believe our task here is 2-fold:

1. Harmonize keys within matchms
2. Define mapping between matchms<->MSP and matchms<->MGF

--> See also #300

**Comment by justinjjvanderhooft** [comment]
Yeah, that is good way in going forward. I would also add:

3. define the scope of matchms (i.e., do we want to include isotope information?)

**Comment by florian-huber** [comment]
I started a table for matchms-internal conversions: https://github.com/matchms/matchms/blob/development/matchms/data/known_key_conversions.csv

Later, a next step would be to add additional tables for matchms<->MSP and matchms<->MGF mappings
Got great input for such tables from @meowcat (hope that's indeed the right github reference...).

**Comment by niekdejonge** [comment]
Sounds like a good plan! I could not think of any often inconsistently named fields that were not yet mentioned above. I think making the harmonization of the metadata fields automated is a good step for user friendliness. Related to the user friendliness, maybe restructuring the folder with all the filtering options might be a good step too. Now there are so many options that it is sometimes hard to find if matchms has these filtering steps already build in. So separating them in filtering steps related to cleaning the metadata and cleaning the peaks would be a good first step, making it easier to select filtering steps that are useful for the user. (but this might already happen with the creation of the metadata class)

**Comment by florian-huber** [comment]
Thanks Niek, that's a very good point. It was part of some discussions in the past but we (unfortunately) never seperated both types. Now the problem is that it will break the API and users that have scripts runing `from matchms.filtering import ...` will run into trouble if we do a complete split between `filtering_metadata` and `filtering_peaks`. We should still consider this way for version 1.0.0 (which could include some API breaks) #269 .

**Comment by niekdejonge** [comment]
Ah yes, having an active user base makes that a bit more complicated. Would be a nice step indeed for version 1.0.0

**Comment by florian-huber** [comment]
Except for the suggestion to split filters into metadata-filters and peak-filters (will become a new issue), the metadata field harmonization is now implemented with #293. Thanks all for the suggestions!
