### ISSUE TITLE
Improve MSP output keys

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#300]
We have a function `save_to_msp` which works, in principle.

But it will simply take all keys and make them upper-case which is usually *very* different from the msp-style at MoNA or MassBank.
Related to #294 we might want to define a mapping dictionary with the most common key and how we want matchms to translate them from internal style (e.g. `precursor_mz`) to external/MSP style (e.g. `PrecursorMZ`).

**Comment by hechth** [comment]
Also, currently metadata values which are `None` are exported as such.

**Comment by hechth** [comment]
I think the most required formats would be [RIKEN](http://prime.psc.riken.jp/compms/msdial/main.html) and NIST, an overview/comparison is also available [here](https://rformassspectrometry.github.io/metaRbolomics-book/9901-Appendices-Appendix_1_The_MSP_File_Format_and_package_support.html)

**Comment by florian-huber** [comment]
We should handle those styles by having one larger table, similar to the [known_key_conversions](https://github.com/matchms/matchms/blob/master/matchms/data/known_key_conversions.csv), for the different export formats and styles.

Our exporting functions will then get an additional flag with a certain default, say `keyword_style="nist"`, which users can change if needed.

**Comment by florian-huber** [comment]
Here is a start: https://github.com/matchms/matchms/blob/add_export_styles/matchms/data/export_key_conversions.csv

It contains keyword translations for
- massbank
- nist
- riken
- gnps

Feel free to add, edit, correct...

**Comment by florian-huber** [comment]
This was implemented with #398
