### ISSUE TITLE
USI import is broken

### ISSUE THREAD

**Issue by alexeigurevich** [matchms/matchms#307]
**Bug description and how to reproduce**
UCSD [metabolomics USI](https://metabolomics-usi.ucsd.edu/ ) resolver seems to change its web API at some point (as of 2022-01-20). While `matchms.importing.load_from_usi` requests a spectrum JSON from `https://metabolomics-usi.ucsd.edu/json/?usi=<USI>`, the correct request should go to `https://metabolomics-usi.ucsd.edu/json/?usi1=<USI>` (mind `usi=` vs `usi1=` difference). [Working example](https://metabolomics-usi.ucsd.edu/json/?usi1=mzspec%3AMASSBANK%3A%3Aaccession%3ASM858102).

As a result, the [documented example](https://matchms.readthedocs.io/en/latest/api/matchms.importing.load_from_usi.html#module-matchms.importing.load_from_usi) of `load_from_usi` is not working properly:

```
from matchms.importing import load_from_usi

spectrum = load_from_usi("mzspec:MASSBANK::accession:SM858102")
print(f"Found spectrum with precursor m/z of {spectrum.get("precursor_mz"):.2f}.")
```
Instead of the expected `Found spectrum with precursor m/z of 271.11.` output, it crashes with `AttributeError: 'NoneType' object has no attribute 'get'`. The underlying reason is that `spectrum = None` because the URL request results in the server error 500 response ([try it](https://metabolomics-usi.ucsd.edu/json/?usi=mzspec%3AMASSBANK%3A%3Aaccession%3ASM858102)).

**Suggested fix**
Replace [line 33 of load_from_usi.py](https://github.com/matchms/matchms/blob/master/matchms/importing/load_from_usi.py#L33) 
```
    url = server + "/json/?usi=" + usi
```
with
```
    url = server + "/json/?usi1=" + usi
```

**Possible caveats**
The fix doesn't seem generic. The suggested change might break requests not to default `server`. Are there any USI resolvers other than <https://metabolomics-usi.ucsd.edu>?
Also, the UCSD resolver might change the interface again. Shouldn't we make the `"/json/?usi1="` part of the request as a parameter of `load_from_usi`?

**Comment by florian-huber** [comment]
Thanks @alexeigurevich  for pointing this out!
For now the fix you suggest would probably do. 

Before implementing and releasing this: 
@mwang87 @sdrogers Do you expect that the link remains valid for a while or should we use a differnt URL ?

**Comment by mwang87** [comment]
@florian-huber @alexeigurevich thanks for pointing this out. This was totally our fault and we didnt intend for the usi param to stop working but we just didnt have the testing in place to catch it. Since it did change, it'll be safe to keep usi1 as the param as we intend to maintain that endpoint for the foreseeable future.

**Comment by florian-huber** [comment]
Perfect, thanks a lot @mwang87 !
Easy fix then.

**Comment by florian-huber** [comment]
@alexeigurevich this should be fixed now and will soon be part of a new matchms release (0.13.0). Thanks for pointing this out!

**Comment by alexeigurevich** [comment]
Thanks @florian-huber and @mwang87! A super quick fix ;)
