### ISSUE TITLE
safe_convert_to_float in add_retention raises error

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#313]
When safe_convert_to_float is run on an empty list it results in the error: 

TypeError: float() argument must be a string or a number, not 'list'

Value is within a try block. However the exception only accepts a value error, while this is a TypeError. 

Solution:
Also add TypeError to exception block.

**Comment by florian-huber** [comment]
Fixed with #314 . Will be part of matchms 0.13.0
