### ISSUE TITLE
New matchms pipeline

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#324]
After some discussion in #268 I want to make a new issue to further consolidate the design ideas.

As far as I imagine it now, the future matchms pipeline (e.g. `Pipeline` class) should cover the following:

### Import:
spectrum_data_1 --> required, filename or list of filenames
spectrum_data_2  --> optional, use spectrum_data_1 if None, else filename or list of filenames

Pipeline will automatically use the right importer function(s).

### Logging:
log_file --> optional, default is None
logging_level --> optional, default is Warning

Pipeline will adjust logger setting

### Filtering / Data processing
filters --> optional, default is `default_filters()`, list of filters with respective settings (where needed)
**Careful!** --> order of filters occationally matters. Known issues with this can be taken care of by Pipeline as well.

### Remove spectra
Is now part of our filters --> all the `require_xyz()` filters
(maybe set appart?)

### Score computations and masking
(Recommendation: Stack score computations form computationally cheap to expensive)
e.g.
```python
score_computation = [
    [PrecursorMzMatch(tolerance=10.0, tolerance_type="Dalton"), None]
    [MetadataMatch(field="charge"), filter_by_range(low=0)],
    [CosineGreedy(tolerance=0.01), filter_by_range(low=0.2)]
]
```
### Progress bar(s)
Pipelines can potentially take quite a while to run. So it should output the progress, e.g. in form of progress bars for the key steps (maybe even by default unless silenced by the user).

## API
The API is not yet designed/defined.
I think it is worth designing the pipeline such that it works for multiple purposes.

### 1) Python style interface
Run it from a notebook or editor or .py file, maybe use something like a scikit-learn pipeline or similar.
(that would also be the first to develop)

### 2) Use a pipeline script file
An alternative way that `Pipeline` should support is to read a config file (yaml or other). This has several advantages. Users can share, document, store their pipeline scripts easily. And it makes it easier to use for non-Python users. In particular if we then add (3) on top:

### 3) command-line interface
Since `Pipeline` is already a wrapper for the full matchms workflow, it will be simple to also add a simple command line interface. Easies maybe to simply take a config file as input an run matchms from there.

### 4) Streamlit-app
Once we have (1) or better: (1+2), one could relatively quickly build a simple streamlit app that would be more intuitive for non-programming users. Simple design with checkboxes and parameters fields where needed and when you click on "run" it will generate a `Pipeline` and execute it.

**Comment by florian-huber** [comment]
@hechth I started to experiment a bit. In #327 there's a first half-functional implementation using a `Pipeline` class and sparse scores. I probably won't work on it for the rest of the week, so feel free to check it out so that we can mabye re-iterate a bit more next week?
(see test_pipeline.py for a start)

Side note: It is not yet made pretty or fully optimized. It is more to experiment and see what the interface should/must do.

**Comment by hechth** [comment]
@florian-huber Regarding the user interface, maybe the version of the tool which we host on [Galaxy](https://umsa.cerit-sc.cz) might already cover the basic functionality?

**Comment by florian-huber** [comment]
You mean my point (4) above, right?
Yes that was just a thought for possible next steps to give access to users without Python/programming background. And indeed platforms like Galaxy could do that as well!

**Comment by florian-huber** [comment]
@hechth #327 now contains a functional pipeline implementation. 
The API now looks different from what I sketched above.
Running it currently looks like this:
```python
from matchms import Pipeline

pipeline = Pipeline("my_config_file.yaml")
pipeline.run()
```
An [example yaml file](https://github.com/matchms/matchms/blob/be840309e7927343d4d69b2beb2d47d4d5a7b3f6/tests/test_pipeline.yaml) is used for testing.
An alternative way to use it:
```python
pipeline = Pipeline()
pipeline.query_files = "spectrums_file.msp"
pipeline.filter_steps_queries = [
    ["default_filters"],
    ["add_parent_mass"],
    ["normalize_intensities"],
    ["select_by_relative_intensity", {"intensity_from": 0.0, "intensity_to": 1.0}],
    ["select_by_mz", {"mz_from": 0, "mz_to": 1000}],
    ["require_minimum_number_of_peaks", {"n_required": 5}]
]
pipeline.score_computations = [["precursormzmatch",  {"tolerance": 120.0}],
                               ["cosinegreedy", {"tolerance": 1.0}]
                               ["filter_by_range", {"name": "CosineGreedy_score", "low": 0.3}],
                               ["filter_by_range", {"name": "CosineGreedy_matches", "low": 5}],
                               ["modifiedcosine", {"tolerance": 1.0}]]

pipeline.run()
```
It would be great to get some feedback on the API. Would it work as it is now or should we change the design?


In addition, there are a few TODOs that need to be addressed:

## Must haves:
- [x]  Fill the **check_pipeline** method, something to check if all files exist and all named filters and scores exist before running the pipeline (to avoid running something for hours before discovering a stupid mistake).
- [ ] Add networking to Pipeline so that users can have a pipeline which also outputs a graph to be imported in Cytoscape or similar tools.

## Nice to have
- [ ] Add option to input list of Spectrum objects (instead of only import from file) to better combine the pipeline with other workflows.
- [ ]  Pipelines can take a while to compute, so **add progress information**: progress bars, but possibly also ways to pass the progress to external tools that want to make use of matchms
- [ ]  Add a sparse output option to the `-matrix()` method. Right not many pipelines might start with a quick check like `PrecursorMzMatch` or `MetadataMatch` to quickly remove many pairs. Still, those methods currently start by initializing an empty numpy array which can get huge if we run a pipeline on many-vs-many spectra.

**Comment by florian-huber** [comment]
This is a few steps further now, so will close this and continue with a fresh start in #376
