### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#325]
Picking up (again) a former issue (#165), but extending this more in general beyond the score computation.

Currently matchms does only provide parallelized solutions if those are explicitly coded into the scoring methods. It would be desirable to have a more general default solution, in particular because many processes are *embarrasingly parallel* such as 
- filtering of many spectra (filtering does not exchange information between spectra!)
- similarity computation (for most scores, each pair of spectra can be regarded seperately)

I experimented a bit with `multiprocessing` and `dask`, but both did not result in any significant performance increases. Mostly they even made things slower, arguable due to the large additional overhead.

One other tool to look at might be `ray`, see also: https://www.jennakwon.page/2021/03/benchmarks-dask-distributed-vs-ray-for.html

**Comment by florian-huber** [comment]
I ran a few more experiments using `joblib`, `dask`, `ray` and `mpire`. So far I only really got the first two to work.

Short summary:
- Individual score computations seem too small to send them to separate threads (overhead large compared to computation time).
- When dividing tasks into larger bites (say pieces of 100 pair calculations) then `joblib` seemed to work *in principle*.
- One issue (if I get this right) is the overhead from compiling the underlying numba functions. Numba by default compiles just-in-time. And it seems that the code I wrote will compile the functions again for every job (or thread)... ?
This might be solvable if we switch to [*ahead-of-time* compiling](https://numba.readthedocs.io/en/stable/user/pycc.html)!

My test code:
```python
# do some benchmarking
import numpy as np
import time
from matchms import Spectrum
from matchms.similarity import CosineGreedy

# Create fake spectra
np.random.seed(0)
n_peaks = 25
n_spectrums = 100
spectrums = []
for i in range(n_spectrums):
    mz = np.random.randint(0, 1000, size=(n_peaks)).astype("float")
    mz.sort()
    spectrum = Spectrum(mz=mz,
                        intensities=np.random.random(size=(n_peaks)),
                        metadata = {"precursor_mz": 100.0 + np.random.randint(0, 500)})
    spectrums.append(spectrum)


#%%
# Baseline: naive double for loop
similarity_score = CosineGreedy()

tstart = time.time()
scores = np.zeros((len(spectrums), len(spectrums)))
matches = np.zeros((len(spectrums), len(spectrums)))

for i, spec1 in enumerate(spectrums):
    for j, spec2 in enumerate(spectrums):
        score = similarity_score.pair(spec1, spec2)
        scores[i, j] = score["score"]
        matches[i, j] = score["matches"]
print(time.time() - tstart)  # => first run (incl. numba compile) 3.18s, then 0.47s


#%%
# Baseline 2: current matrix method
similarity_score = CosineGreedy()

tstart = time.time()
scores = similarity_score.matrix(spectrums, spectrums)
print(time.time() - tstart)  # => first run (incl. numba compile) 0.48s, then 0.4s

#%% parallel version 1 dask
import time
import dask

tstart = time.time()
lazy_results = []
for spec1 in spectrums:
    for spec2 in spectrums:
        lazy_result = dask.delayed(similarity_score.pair)(spec1, spec2)
        lazy_results.append(lazy_result)

futures = dask.persist(*lazy_results)
results = dask.compute(*futures)
print(time.time() - tstart)  # => first run (incl. numba compile) 15.8s, then 15.6s


#%%
# Dask - using bigger bites
import dask
similarity_score = CosineGreedy()

bins = 20
num_bins = int(np.ceil(len(spectrums)/bins))

spec_pairs = []

for i in range(num_bins):
    for j in range(num_bins):
        specs1 = spectrums[i*bins:(i+1)*bins]
        specs2 = spectrums[j*bins:(j+1)*bins]
        lazy_result = dask.delayed(similarity_score.matrix)(specs1, specs2)
        lazy_results.append(lazy_result)

tstart = time.time()
futures = dask.persist(*lazy_results)
results = dask.compute(*futures)       
print(time.time() - tstart)  # => first run (incl. numba compile) 15.8s, then 15.6s



#%% joblib
from joblib import Parallel, delayed
# from joblib.externals.loky import set_loky_pickler
# set_loky_pickler('pickle')

similarity_score = CosineGreedy()
indices = np.indices((len(spectrums), len(spectrums))).reshape((2, len(spectrums)**2))
indices_tuples = list(zip(indices[0], indices[1]))

spec_pairs = [(spectrums[i], spectrums[j]) for i, j in indices_tuples]

tstart = time.time()
results = Parallel(n_jobs=4)(delayed(similarity_score.pair)(x[0], x[1]) for x in spec_pairs)
print(time.time() - tstart) # => first run (incl. numba compile) 14.1s, then 0.7s


#%%
# joblib - using bigger bites
from joblib import Parallel, delayed
similarity_score = CosineGreedy()

bins = 20
num_bins = int(np.ceil(len(spectrums)/bins))
#scores = []
spec_pairs = []

for i in range(num_bins):
    for j in range(num_bins):
        specs1 = spectrums[i*bins:(i+1)*bins]
        specs2 = spectrums[j*bins:(j+1)*bins]
        spec_pairs.append((specs1, specs2))

tstart = time.time()
results = Parallel(n_jobs=4)(delayed(similarity_score.matrix)(x[0], x[1]) for x in spec_pairs)        
print(time.time() - tstart) # => first run (incl. numba compile) 10.1s, then 0.2s
```

**Comment by hechth** [comment]
@florian-huber that looks good - I think having 100 by 100 is already quite small, I'd maybe parallelize on the 10k by 10k scale, or 100 by 10k as there will typically be a larger reference library than the queries.

**Comment by florian-huber** [comment]
This could soon be revived based on the newly implemented `Pipeline` (#370) !

**Comment by Adafede** [comment]
Hi @florian-huber! I just updated https://github.com/mandelbrot-project/spectral_lib_matcher to follow new matchms 0.18.0 format and I think it is actually almost exactly what you mean with a `Pipeline`, right?

Shall we write pipelines instead? Is there be some doc about it? If not, could we collaborate to move our patchy work to a proper pipeline while helping with documentation?

**Comment by florian-huber** [comment]
Hi @Adafede.
I will soon try to look at your pipeline, but it seems to overlap quite a bit with what the new matchms `Pipeline` does (including the sparse handling of scores). Maybe we can also have a meeting together to look at the code?

The next few days I will be busy to also finish all the releases, matchms, spec2vec, ms2deepscore (and update the tutorials).

**Comment by florian-huber** [comment]
@julianpollmann here some dummy code that *might* be interesting as a starting point for the parallelization of our score computations.

(Issue itself is outdated, so will be closed)
