### ISSUE TITLE
Consider including neutral losses score

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#328]
This might be a good fitting addition to the matchms similarity scores: https://t.co/GeHM2wW0zG

**Comment by sdrogers** [comment]
One way to implement is to use modified cosine but don’t allow any unshifted matches. If you shift all peaks in one spec by the difference in m/z then things with the same loss match.

**Comment by florian-huber** [comment]
OK, that would indeed be simple to implement. We could simply make a clone of the `CosineGreedy` in which we add a shift by percursor-m/z difference, right?

**Comment by florian-huber** [comment]
I made a ModifiedCosine clone with the zero-shift pairs removed --> #329 
(needs further testing)

**Comment by florian-huber** [comment]
@sdrogers @justinjjvanderhooft, the score is now implemented in #329 (not yet part of master branch).
One thing to maybe still dicuss:
The score now shifts peaks by the difference in precusor-m/z. That was great hint form Simon and does the same thing as: computing losses + computing cosine using losses. The only difference I can imagine would be: peaks with m/z > precursor-m/z. If we explicitely compute losses those would be discarded (because they get <0 mz values). Will this be an issue? If so, we could add this to the score and discard all peaks with mz > precursor-m/z.

**Comment by justinjjvanderhooft** [comment]
Which score do you talk about here, the neutral loss score? Indeed, I would ignore m/z peaks larger than the parent mass, as they become negative. And indeed, rather than first calculating "NL spectra", we could also work with the parent mass differences when comparing two spectra, i.e., it becomes "modified cosine at larger scale where you only consider parent mass corrected matches"

**Comment by florian-huber** [comment]
Yes, I meant the neutral losses. I just added a default option to remove peaks with mz > precursor_mz.

**Comment by sdrogers** [comment]
Bit confused: mz > precursor - mz will be any peak that is lighter than its loss (potentially a lot).

but I think I didn’t explain well - no need to shift the peaks. The modified cosine is already doing exactly what we need - it attempts to match fragments with and without a shift of _the precursor differences_. This is exactly the same as attempting to match each peak as fragments and as losses.

So, say we have spec 1 with mz values a1 a2 and a3 and spec 2 with b1 b2. Modified cosine finds matches between the a and b masses and then also between the a’ masses where, eg a1’ = a1 + (p2-p1), p are the precursor masses.


Now, if a1’ matches with b2, it means they both have the same neutral loss wrt their precursor:

b2 = a1’ implies p2 - b2 = p2 - a1’ = p1 - a1

so, the matches on the a’ *are* NL matches.

which means that all that needs to be done is modified cosine, with the direct a <-> b matches switched off.

**Comment by sdrogers** [comment]
Peaks above the precursor are kind of weird anyway though, so I’m not arguing against removing them.

**Comment by florian-huber** [comment]
> but I think I didn’t explain well - no need to shift the peaks. The modified cosine is already doing exactly what we need - it attempts to match fragments with and without a shift of the precursor differences. This is exactly the same as attempting to match each peak as fragments and as losses.

You actually explained it well enough 😄 (though maybe I didn't). What you describe is exactly what I did in #329 . It is essentially the same as `ModifiedCosine` without direct peak matches!

> Peaks above the precursor are kind of weird anyway though, so I’m not arguing against removing them.

Great, so then we seem to agree on this one, too. [`NeutralLossesCosine`](https://github.com/matchms/matchms/blob/1a289cad6a7747eef7ccb762340d383ab10ce3bf/matchms/similarity/NeutralLossesCosine.py) by default ignores such peaks.

**Comment by justinjjvanderhooft** [comment]
Hoorray, we all agree about this rather confusing topic :-)
