### ISSUE TITLE
load_from_msp function issue in parsing metadata

### ISSUE THREAD

**Issue by jundahuang9123** [matchms/matchms#330]
I had a problem using load_from_msp function to load a msp format spectra file. 

Occured in the following error messages:
File "matchms_scoring.py", line 29, in matchms_score
    for r in load_from_msp(reference):
  File "/home/junda_ubuntu/miniconda3/envs/matchms/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 132, in load_from_msp
    for spectrum in parse_msp_file(filename):
  File "/home/junda_ubuntu/miniconda3/envs/matchms/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 29, in parse_msp_file
    parse_metadata(rline, params)
  File "/home/junda_ubuntu/miniconda3/envs/matchms/lib/python3.8/site-packages/matchms/importing/load_from_msp.py", line 95, in parse_metadata
    params[splitted_line[0].lower()] = splitted_line[1].strip()
IndexError: list index out of range

I have checked it happens during parsing one comment line of one spectrum:
Name: (2-AMINOETHYL)PHOSPHONATE
Synon: $:00in-source
DB#: CCMSLIB00000578169
InChIKey: QQVDJLLNRSOCEL-UHFFFAOYSA-N
Precursor_type: [M-H]-
Spectrum_type: MS2
PrecursorMZ: 124.016
Instrument: Q-Exactive Plus
Ion_mode: N
Formula: C2H8NO3P
MW: 125
ExactMass: 125.02417974599999
Comments: "cas number=2041-14-7" "pubmed id=339" "SMILES=O=P(O)(O)CCN" "computed SMILES=C(CP(=O)(O)O)N" "computed InChI=InChI=1S/C2H8NO3P/c3-1-2-7(4,5)6/h1-3H2,(H2,4,5,6)" "ion source=LC-ESI" "compound source=Commercial standard" "exact mass=125.024" "charge state=0" "source file=IROA_PLATE_neg_2_B.mzXML" "origin=GNPS-EMBL-MCF" "author=Alexandrov Theodore, pphapale, Prasad" "computed mass accuracy=7.287333892219113" "computed mass error=-9.037459999774455E-4" "SPLASH=splash10-00fr-5900000000-71241086c94c831eda97" "submitter=GNPS Team (University of California, San Diego)" "MoNA Rating=4.090909090909091"
Num Peaks: 24
55.649189 0.660602
67.693985 0.748710
72.791397 1.174059
...

I solved the problem by deleting the extra space in the parse_metadata function line 89.
Original: for s in splitted_line[1][2:-1].split('" "'):
Edited: for s in splitted_line[1][2:-1].split('""'):

Seems to work after the change.

**Comment by florian-huber** [comment]
Thanks for making this issue!

It looks like that the error you describe (and the fix) occurs with an older version of matchms.

Unfortunately, however, I still get an error when I try to import the spectrum you have here. With the current matchms version (0.14.0) the issue now is that exact_mass (which matchms will rename into `parent_mass`) occurs several times (one time as ExactMass and one time in the comments).

I will fix this very soon and have it in the next release (0.15.0).

**Comment by jundahuang9123** [comment]
I see, thank you for the response. 

Indeed I am using version 0.13.0. FYI, when I was using the function with the exact same dataset months ago (version 9), it did not have any issues.

**Comment by florian-huber** [comment]
Thanks @jundahuang9123. With #332 I can now import the spectrum you show above, so that should fix this issue.

One question: Is this spectrum a direct download from GNPS?
I am asking because we currently have automatic tests for different styles of `.msp` files, but were apparently missing the GNPS style. And I would than add this (or similar) spectra to our testing routine.

**Comment by jundahuang9123** [comment]
Great!!!

My spectra data is a direct download from Massbank library. 
https://mona.fiehnlab.ucdavis.edu/downloads

**Comment by florian-huber** [comment]
Issue should be fixed with #332 and will be part of next release (0.15.0).
