### ISSUE TITLE
[feature request] Easily filter an MGF (or other spectral file) according to a list

### ISSUE THREAD

**Issue by Adafede** [matchms/matchms#333]
**Is your feature request related to a problem? Please describe.**

It is not related to any problem, just a wish

**Describe the solution you'd like**

I would like to be able to take an MGF, a csv file containing a list of InChIKeys, and filter the MGF according to the InChIKeys present.
This would also possibly apply to other fields, for example with a list of masses instead of InChIKeys.

**Any good starting points?**

I think @ArnaudGaudry has already worked on it a bit

**Additional context**

None

**Scientific reference**
If this request is about adding a method to matchms (new similarity measure, new filter etc.), please point us to a scientific reference (if possible).

None

**Comment by florian-huber** [comment]
Always good to have some wishes on the list 🤩.

**Comment by florian-huber** [comment]
In principle this is not too complicated and could be a nice addition to the `Pipeline` class we are developing at the moment (#327). 
The only complications I see at the moment are that inchikey-matching is not 100% trivial and should account for a few variations:
- full inchikey match
- first-14 characters match (if we ignore stereochemistry, isotopes)

**Comment by Adafede** [comment]
@florian-huber Any news on the `Pipeline`?

**Comment by florian-huber** [comment]
`(under development) ................................................................. 92 %`
