### ISSUE TITLE
Is valid smiles functions filters out valid SMILES

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#334]
The code in the function below actually filters out valid smiles for small molecules - I suspect the regexp check which comes before the check based on RDKit to be behaving wrong. For example `C` or `CF` are valid SMILES but are filtered by the function.

https://github.com/matchms/matchms/blob/a7b687d08da50f4a08fa92483399d5ea96ba601c/matchms/metadata_utils.py#L109-L133

**Comment by florian-huber** [comment]
That's correct. When this was designed it was (and probably still mostly is) used for larger compounds. Are there actual use cases where such small compounds are of interest?

**Comment by hechth** [comment]
Well there are spectral libraries that have such small compounds where we would still like to use the SMILES.

How expensive is the actual expensive check? If we can rely on it to be correct, is it worth getting rid of the regexp?

**Comment by florian-huber** [comment]
Thanks. For most pipelines it should be fine to get rid of the regexp. It was an issue when running a large data cleaning on a big data set, but your solution in #337 seems like a good way to handle this!

Let me know (or make a new issue) if you think we should get rid of the regexp entirely which would involve doing a small performance test I guess.
