### ISSUE TITLE
Valid InChI filter fails for molecules with no Carbon or Hydrogen layer

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#335]
The regexp fails for things like molecular neon or chlorine as they don't have a carbon or hydrogen layer

https://github.com/matchms/matchms/blob/a7b687d08da50f4a08fa92483399d5ea96ba601c/matchms/metadata_utils.py#L99

**Comment by florian-huber** [comment]
We could add one or a few representative examples to the test and change the regex to make it work https://github.com/matchms/matchms/blob/a7b687d08da50f4a08fa92483399d5ea96ba601c/tests/test_metadata_utils.py#L103

Would you have time to do this?
Otherwise, you can mabye provide a few examples.

**Comment by hechth** [comment]
I can take care of this one and the SMILES check! :)
