### ISSUE TITLE
Add option to disable key mapping when loading Spectra

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#338]
**Describe the bug**
If loading a spectrum from msp, the metadata is always harmonized, no matter whether true or false is passed as the parameter.

**To Reproduce**
See attached ZIP folder with jupyter notebook.

**Expected behavior**
The metadata shouldn't get harmonized if the parameter is set to false.

I think it would be good to actually implement a unit test for this to check this and then fix the bug.

**Comment by florian-huber** [comment]
I didn't see the attached ZIP. Was this added?

One thing I imagine happens here is that we have two types of "harmonizations".
The first is the restrictions of key_words by pickydict in Metadata. This is currently always on and cannot be switched off (in the current implementation at least).

The keyword `metadata_harmonization` in the `Spectrum` class which is also used by the importer functions refers to wether or not to run `._apply_metadata_harmonization()` in `Spectrum`.

**Comment by florian-huber** [comment]
If that's indeed what happend than this would be a good occasion to discuss again what we mean by "harmonization". I suggest we could change it such that `metadata_harmonization=False` in `Spectrum` will then also trigger `matchms_key_style=False` in `Metadata`?

One thing that cannot be switched off easily is forcing lower-case keys, but I guess that is less of an issue?

**Comment by hechth** [comment]
I forgot to attach the zip - my apologies, I'll add it later.

But yes, I think what you say is exactly what is happening - I thought the keyword mechanism is tied to the harmonization.

Maybe let's first figure out the conversions between formats etc and then come back to this. I'll have a go on the conversions next week.

**Comment by hechth** [comment]
Now after some time it has become quite obvious what is happening and what I initially intended.

I think it would be great to have the feature of being able to read and store the spectra also in exactly the same way as they are actually on disk - not deleting any keys, no parsing, nothing. Just read everything as a string and write everything as a string again - this is very useful if someone for example just wants to filter or split a collection of spectra etc. and doesn't really want to perform many operations on them - so I think a feature like this would be very valuable, to be able to disable all metadata parsing and fancy handling. I think this would also need to be implemented directly in pickydict, not matchms @florian-huber ?

**Comment by hechth** [comment]
@florian-huber I think this is actually implemented by now anyways, or it is possible via ```matchms.Metadata.set_key_replacements({})```
