### ISSUE TITLE
Extend `MetadataMatch` to store difference (possibly `MetadataDifference` subclass?)

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#340]
**Is your feature request related to a problem? Please describe.**
Current `MetadataMatch` only stores a boolean whether the entries are equal or within a specified difference - it is not possible to actually store the difference, which could be of interest for creating a weighted score.

**Describe the solution you'd like**
Either extend the `MetadataMatch` class to also handle this case or create a subclass `MetadataDifference` which stores numerical scores in form of the difference and only works for numerical metadata.

**Comment by florian-huber** [comment]
Good suggestion, should be done!
