### ISSUE TITLE
Add `.cyjs` export to networking module

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#341]
**Is your feature request related to a problem? Please describe.**
Currently only `.graphml` output is supported, which is not supported by the cytoscape Galaxy plugin.

**Describe the solution you'd like**
Add the option to export to `.cyjs` using the networkx package to the Networking module.

**Any good starting points?**
[Do you know of any alternative solutions or do you have some helping code/links at hand?
](https://networkx.org/documentation/stable/reference/readwrite/json_graph.html)

**Comment by florian-huber** [comment]
That makes sense and should be easy to implement. We could still keep a flag at the default of `.graphml` but include other formats which are supported by networkx.

Do you have time for this @hechth ?

**Comment by hechth** [comment]
Actually @maximskorik will take care of this :)

**Comment by florian-huber** [comment]
Perfect!
