### ISSUE TITLE
Introduce order in writing metadata

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#342]
**Is your feature request related to a problem? Please describe.**
The Name assigned to the spectrum is often not the first entry written - some ordering of the canonical metadata names would actually be better to give some more structure to the metadata

**Describe the solution you'd like**
Create an ordered list in which the metadata is written (the one that is harmonized).

**Comment by florian-huber** [comment]
Do you mean that we imply a certain order for the different keys (e.g. starting with "name") ?

**Comment by hechth** [comment]
Yeah, I thought about it - maybe just starting with `compound_name` would actually be enough to make it a bit easier to find a spectrum - or how do you see this?
