### ISSUE TITLE
Allow appending to file in export functions

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#343]
**Is your feature request related to a problem? Please describe.**
When writing spectra to a file, it is currently only possible in `write` fashion, not in append - therefore appending spectral information to an already existing library is not so easy if one doesn't want to read the library into memory.

This could also be used for streaming output

**Describe the solution you'd like**
Add the flags for opening the file as read/write/append as parameter to the export function (write as default).

**Comment by florian-huber** [comment]
Good point. And should be easy to add (write as default and option to change to append). Is someone from your side working on it?

**Comment by hechth** [comment]
@florian-huber I'll start working on this today.

**Comment by florian-huber** [comment]
With PR #346 append/write is possible for msp files and append for mgf files. 
Not yet included for json export. Please re-open issue if this is a needed feature!
