### ISSUE TITLE
Empty `inchi` doesn't get removed but results in empty string -> remove invalid metadata after reading the spectrum

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#344]
**Describe the bug**
Currently, an `inchi` entry that is empty will result in a metadata entry that holds an empty string.
Ideally, if spectra are loaded with `harmonize_metadata` as true, _invalid_ or empty metadata values should be removed from the spectrum metadata.

**Comment by florian-huber** [comment]
Sounds good.
Empty values are easy to remove. Those could even be removed for *any* key in the underlying dictionary.

Invalid is more complicated because that must be defined.

**Comment by florian-huber** [comment]
I guess we could also start by simply removing empty string entries.
Plus, maybe, a list of synonyms for empty entries (`NA`, `N/A`, `NaN`, ...).

**Comment by florian-huber** [comment]
@hechth maybe this could already be taken care of by PickyDict?
For instance add a new flag `allow_empty_values: bool = False` such that the `__setitem__` method simply won't add empty entries `""`.

The other type of false/entry entries are maybe too specific for PickyDict though (NA, N/A, NaN, ...). I could add this to PickyDict as an optional `empty_entires` list, but that seems to be more on the matchms side of things to me. What do you think?

**Comment by hechth** [comment]
Maybe we can first have it in matchms and then if it stabilizes trickle it down into pickydict? I think this might be easier than the other way around if I am not mistaken.
