### ISSUE TITLE
[feature request] SIMILE support

### ISSUE THREAD

**Issue by Adafede** [matchms/matchms#347]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the newly [SIMILE](https://doi.org/10.1038/s41467-022-30118-9) distance to be available in matchms.

**Any good starting points?**
Repository  of SIMILE: https://github.com/biorack/simile/

**Additional context**
See [article](https://doi.org/10.1038/s41467-022-30118-9).

**Scientific reference**
See [article](https://doi.org/10.1038/s41467-022-30118-9).

**Comment by florian-huber** [comment]
Having SIMILE support would be great!

I see some options to include it:
- Making SIMILE a pypi package (ideally with tests/CI). Then we could either add a wrapper to matchms.
- Have an own version of SIMILE as part of matchms (that's more work but would allow to speed up some of the code through numba, I guess)
- Add a `BaseSimilarity` type of class to SIMILE that can be imported and used in matchms, e.g. `from SIMILE import SimileScore` ....
