### ISSUE TITLE
[feature request] Add exporting Scores to JSON

### ISSUE THREAD

**Issue by maximskorik** [matchms/matchms#351]
**Is your feature request related to a problem? Please describe.**
Currently, it's only possible to export [Spectrum](https://github.com/matchms/matchms/blob/master/matchms/Spectrum.py) objects. It would be nice if there was a functionality to also export [Scores](https://github.com/matchms/matchms/blob/master/matchms/Scores.py) objects to JSON files for later use, sharing, etc. The advantage of such an approach would be that the scores can be stored together with the individual spectra and related information.

**Describe the solution you'd like**
A custom JSON encoder akin to [`SpectrumJSONEncoder`](https://github.com/matchms/matchms/blob/922f5afaef123a793194bdd74391027477cbb844/matchms/exporting/save_as_json.py#L46) seems like an optimal solution.

**Comment by florian-huber** [comment]
That would indeed be nice to have!

Scores itself might soon change anyway to run on sparse arrays (https://github.com/matchms/matchms/tree/pipeline), so we could add an exporting method to scores.
Possible options could be json (as you suggested) or also pickle or hdf5...

**Comment by hechth** [comment]
@florian-huber we started with the JSON due to security reasons - a pickle might actually contain anything, so deserializing it might not be completely safe.

**Comment by maximskorik** [comment]
@florian-huber pickling Python objects seems simple, so it definitely could be added as another option. I'd just prioritize JSON due to Pickle's [security concerns](https://docs.python.org/3/library/pickle.html#module-pickle).
