### ISSUE TITLE
Spectrum.clone() fails 

### ISSUE THREAD

**Issue by brian8128** [matchms/matchms#352]
**Describe the bug**
Anytime I call the Spectrum.clone function I get the following error message. This happens whether I call clone myself or if it gets called under the hood, for example by the `normalize_intensities` function. 

```
  File "/home/ubuntu/anaconda3/envs/matchms/lib/python3.8/site-packages/matchms/Spectrum.py", line 139, in clone
    metadata=self._metadata.data,
AttributeError: 'dict' object has no attribute 'data'
```

This is my conda environment:
name: matchms
channels:
  - bioconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - boost=1.74.0=py38h2b96118_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.6.15=ha878542_0
  - cairo=1.16.0=ha61ee94_1011
  - certifi=2022.6.15=py38h578d9bd_0
  - cffi=1.15.0=py38h3931269_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=10.2.89=h713d32c_10
  - cycler=0.11.0=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3=hf484d3e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py38h0a891b7_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - greenlet=1.1.2=py38hfa26641_2
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.3=py38h43d8883_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=12_linux64_mkl
  - libdeflate=1.12=h166bdaf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.70.2=h174f98d_4
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - libllvm11=11.1.0=hf817b99_3
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=hc85c160_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_0
  - libxslt=1.1.35=h8affb1d_0
  - libzlib=1.2.12=h166bdaf_1
  - llvmlite=0.38.1=py38h38d86a4_0
  - lxml=4.9.0=py38h0a891b7_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matchms=0.16.0=pyh5e36f6f_0
  - matplotlib-base=3.5.2=py38h826bfd8_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - munkres=1.0.7=py_1
  - ncurses=6.3=h27087fc_1
  - nettle=3.6=he412f7d_0
  - networkx=2.8.4=pyhd8ed1ab_0
  - numba=0.55.2=py38hdc3674a_0
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.4=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py38h47df419_2
  - pcre=8.45=h9c3ff4c_0
  - pickydict=0.4.0=pyhd8ed1ab_0
  - pillow=9.1.1=py38h0ee0e06_1
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycairo=1.21.0=py38h9c00e7a_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py38h578d9bd_5
  - pyteomics=4.5.3=pyh5e36f6f_0
  - python=3.8.13=ha86cf86_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.11.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=pyhd8ed1ab_0
  - rdkit=2022.03.3=py38ha829ea6_0
  - readline=8.1.2=h0f457ee_0
  - reportlab=3.5.68=py38hadf75a6_1
  - requests=2.28.0=pyhd8ed1ab_0
  - scikit-learn=1.1.1=py38hf80bbf7_0
  - scipy=1.7.3=py38hc147768_0
  - setuptools=62.6.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.37=py38h0a891b7_0
  - sqlite=3.38.5=h4ff8645_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - torchaudio=0.11.0=py38_cu102
  - torchvision=0.12.0=py38_cu102
  - typing_extensions=4.2.0=pyha770c72_1
  - unicodedata2=14.0.0=py38h0a891b7_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py38h0a891b7_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.12=h166bdaf_1
  - zstd=1.5.2=h8a70e8d_1
  - pip:
    - absl-py==1.1.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - cachetools==5.2.0
    - click==8.1.3
    - contexttimer==0.3.3
    - docker-pycreds==0.4.0
    - frozenlist==1.3.0
    - fsspec==2022.5.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.46.3
    - importlib-metadata==4.11.4
    - markdown==3.3.7
    - multidict==6.0.2
    - numpy==1.22.4
    - oauthlib==3.2.0
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.4
    - psutil==5.9.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pytorch-lightning==1.6.4
    - pyyaml==6.0
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sentry-sdk==1.6.0
    - setproctitle==1.2.3
    - shortuuid==1.0.9
    - smmap==5.0.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - torchmetrics==0.9.1
    - tqdm==4.64.0
    - wandb==0.12.19
    - werkzeug==2.1.2
    - yarl==1.7.2
    - zipp==3.8.0
prefix: /home/ubuntu/anaconda3/envs/matchms

**Expected behavior**
clone() creates a copy of the spectrum without error. 

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by florian-huber** [comment]
This usually happens when the Spectrum objects were generated with an older version of matchms (<0.14.0) but are then used with an updated matchms package (for instance if Spectrum objects were pickled with an older version).

To move the Spectrum objects to the new version, maybe this will work:
```python
from matchms import Spectrum

spectrums_updated = []
for s in spectrums:
    spec_new = Spectrum(mz=s.mz,
                        intensitities=s.intensities,
                        metadata=s.metadata,
                        metadata_harmonization=False)
    spectrums_updated.append(spec_new)
```

Please let me know if this doesn't do the trick.

**Comment by brian8128** [comment]
Thanks for your help! I downgraded to 0.13.0 and that fixed the issue.
