### ISSUE TITLE
con't read file ,it's empty generator.

### ISSUE THREAD

**Issue by LXXiaogege** [matchms/matchms#358]
use Proteowizard MSconvert  convert raw file  to mzML/mgf ... ,but  use matchms package load has converted file is None.

**Comment by florian-huber** [comment]
Hi.
I would need more information to try reproducing this. How does the mzml or mgf file look like and how was it imported with matchms?

**Comment by LXXiaogege** [comment]
I load the converted MZML data by MATCHMS API load_MZML, and get an empty list, is  there are errors in my data?   but, these native RAW files can be opened directly by some software.

**Comment by florian-huber** [comment]
Can you copy+paste a part (say one spectrum) of the mzml file to see if I can reproduce the error?

**Comment by LXXiaogege** [comment]
<spectrum index="1" id="controllerType=0 controllerNumber=1 scan=2" defaultArrayLength="232"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000511" name="ms level" value="1"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000130" name="positive scan" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000127" name="centroid spectrum" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000504" name="base peak m/z" value="32.058734893799" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000505" name="base peak intensity" value="2.32692675e06" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000285" name="total ion current" value="3.13575719294e06"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000528" name="lowest observed m/z" value="29.210674285889" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000527" name="highest observed m/z" value="299.774932861328" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000796" name="spectrum title" value="100008009.2.2. File:&amp;quot;100008009.raw&amp;quot;, NativeID:&amp;quot;controllerType=0 controllerNumber=1 scan=2&amp;quot;"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <scanList count="1"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000795" name="no combination" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <scan&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="7.003861666667" unitCvRef="UO" unitAccession="UO:0000031" unitName="minute"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000512" name="filter string" value="+ c EI Full ms [29.00-300.00]"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000927" name="ion injection time" value="0.0" unitCvRef="UO" unitAccession="UO:0000028" unitName="millisecond"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <scanWindowList count="1"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <scanWindow&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000501" name="scan window lower limit" value="29.0" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000500" name="scan window upper limit" value="299.972986668348" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </scanWindow&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </scanWindowList&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </scan&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </scanList&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <binaryDataArrayList count="2"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <binaryDataArray encodedLength="1240"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000514" name="m/z array" value="" unitCvRef="MS" unitAccession="MS:1000040" unitName="m/z"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <binary&gt;eJwl0XtMVnUcx/EftYdLA4xWNm/thGFl2myLzRnZgeDhFohcukjCeUSIO8XMZrFxmDwPyc34QzMsO1qti2tqrAuXPRwUyie2CLtQI+zYVULRR1ib5aL5/v712ufz+/4uO0cpZc/GP6wrpcyvlm+8rioLoNUcpmNFK+pVkYnX1TrL0ToQlsS+uC50IqMexbE2se/GZOZ2dKKzIiKF/Zs70Ohxuelf34PWR+Gp9G80on1saRqu7UBj+uZ06b2oz4dl8F7/PjHpd7R/XJXJ/IoOVN23PYaLutAoDc/ivv7d4lhoNvtifWJO9CbeObp3k8yF5HDfA4lo/9SM2p/DYkvIZvp/01ErakGz9pTkj125WLAGzcV5aM81oTMRkPXZG/LI9yahNdGB6pOTqJ+PzMf6zHz53j60Jj9D+6+fUQUjC8gLyWJkK6pPe9EaDqL+fMbjfI8/htGZi3iC9QI3qlmv5NBhNFTUk5iajvaSFtQvn0InISh5zv0U+9K8aI8E0PTFbGF/Vhpa33eJ419LnxhRyPxUMmpnK1HP7UJnyXeoXgp9mlzrRit7t/jPkPSlEVs5J+V+dPyFaER1ovbboKy33FREX6OjE96KeuMgqrtiinl3fJ7Y/So6mdeK5T9EG/hgHGrVSWj1e6QvfFGcbkcn6z00zwzJ3OiU7Nt2CZVyefD03WgH3Gj2lKFx3ovaycOSPV+g3nBO+l7XNua/XY6aPwUdbxFagQbULxyWfp2NKjgu/eQvkn2qhPMvaOLBh8TmUjTf6kBrfQ+q42Oybs9IvidiO/nEUtSLM9DqNsTUXajd8ibabadlPjeklPNHF6PVtgHV0HY0YnfJuvcddKb6pa84h1rxNdnXt6yMvDMF1aI6dP5+WbL7KFoNE2iUXJScrT3De87sQetQNxpXhyXPz6LaG1vOeRc3oLY/B/WNpeKadulXv4vm7X1ol8xIbrijgrwvAVVBOTrpXunv60ej0pH+yILMTa6slO+UIH5QhU5es+TxD1GfvoL2pLuK++p96Fw+gppnAK2jOdXM+2vFF35FU7lq8FAS2oGmGvmvr0n+5n3UxqfQWX9Fel9mLfuqm1AfnEdr4c465uMq6uS9jZJHvkQ9JvpZzr/0CNr+HNTXbkHj1h2ozbRLHtgvcyMnpN/pl3zgBzlndRAd7T8089c9x3mr8tDwbEUzqxad+FfElcdQhfeidfBzmTs7KevLrkr/9vF67i0bqNf/B8/l3uY=</binary&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </binaryDataArray&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <binaryDataArray encodedLength="1468"&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000523" name="64-bit float" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000574" name="zlib compression" value=""/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <cvParam cvRef="MS" accession="MS:1000515" name="intensity array" value="" unitCvRef="MS" unitAccession="MS:1000131" unitName="number of detector counts"/&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <binary&gt;eJwllH9MVWUYx4+UgVbDjZZsCDuYoQubttoqW+0gExBBBBFI5XIulx/yS0gqFDRvQkCKSMVtaAgHIdkVkAxogCyPSmLkhGY64Lp1Wkog/CMCjQH9uJ/3r2fP+3yf7/t9vu9zjiRJ6l+N44okSXLIN/ecUS9saHNGtU8PCHCeH8zUqD+o0Z1RG534mHr1YKMzStfa6sjNK9qJWuIAuBS7q7Nfnyy948yNoYBBZ1T2p4/AV2SjrjSt6afvPXML9Z6pz9BhGrPSd8Kngth9pR5eT+9mZ7S62tGlVsWdh+9ibCF58p/oUl64eJtcsV0TuoZ7wNkOtpIHxp6Dx+xeQxz2yYM/9EExuOQszhXLwrfgHaXcp4/k2sjnzv5AX8yYHR9eaiHXglIu0d/ZiF79LfdPwPtZcqhfmfoU3uxTZeSbd34Bj3cpvlrng/FBXrlBzLf67+9E3UXkZRHw61V74VeLf8V/I9T/S3JTdAN6rjtOw/+HrRZ82wBzqSczUuA75PMV+X3H9+Aqy8W8G26I/rtR8CpGi/D96oCYc/QG/su/R1K3RtVWw2NLPEC+piQffP2z8Os3eyvp01JP0Pdqktib2ST06P96VJE3tJBLHV7g1acy9lD3z+dd5Ag3+LS+iQLmzU84TN1kE/z9PWeoK67lxOQccJrbLvZCznsO3w2HtRT8jiFwesACdWlZLfrU6E5x35IC5pHCZ9PwIdgDvNHXeYx8ebUZ3PiL3G/tbT0s+tcd5/yufhR8/LDY46VJ9MuOcfbbqmXzDkr9gXjykCx0GFMFm8hL1nOvbJ9gb9RXbon9Gf68iDypVfi59d0k+raU4rv8S4yF+tpA5pVverJfuq8n+6Z7dIk9H0uO5J7F0x8S7Qbn/ytiv/XHV4UvCxcOUfd9ehexyTcTXs9B5teaqz7i/oq8dOqrusUezMbtQMeP8xnUY4uzON9YHkPuVyT8D7ULn16/zVxab1g0vpydzAU/Pcdc0lr/KHBe7ehSKnzg0TrexCfVqwWdSpQFPWqWzhxyWe4H8CxfJnzxdKBDvrwJfVpC3W54ZwojuGcmPQ5dF34KgW/UTeCbHpZwrnQK3y9vxi/ry/H4rN2JZG7FZck+zretxC9NyuB+qd9GVBsrhc6EPUeoP37E+1mNnHDO1X+Yx/r2b+J/6tgu/jeZ608ST74j9ib8FvPrlimhc3XqdvgyjuC3vG7mGPeOPdxJvauY+a3t6fhoDU/ZD35gTLzL9Usm8K8tRY+ycTd69Ihz+KRscWcuNX9a7NvQCrGf56uoG/Np7JOcupgIz8/eQk+3As7YZ2PPtNZVgv/+FH4Yevb74Lse8Q7yvcmt5AnPi+9iJE30P9MBzjCZxf80uBkfpck69sPof2Mv/WHj8MtHF4PonznDvLLH9NfgY8PE920pZn7J3M65MefH/sohQaHMHfUkkHtqnmyj7mIKph6XiC7F+7if8h/MGvrn</binary&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </binaryDataArray&gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </binaryDataArrayList&gt;
&nbsp; &nbsp; &nbsp; &nbsp; </spectrum&gt;





This is one of the mass spectrometric messages，&nbsp;This is an XML file. Do you need any other information? Or how do I send you the whole file?
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Florian ***@***.***&gt;; 
发送时间: 2022年8月18日(星期四) 下午4:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [matchms/matchms] con&#39;t read file ,it&#39;s empty generator. (Issue #358)





 
Can you copy+paste a part (say one spectrum) of the mzml file to see if I can reproduce the error?

**Comment by LXXiaogege** [comment]
this is my raw file and have converted&nbsp; mzML file,thank&nbsp; u
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "matchms/matchms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 下午4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [matchms/matchms] con't read file ,it's empty generator. (Issue #358)





 
Can you copy+paste a part (say one spectrum) of the mzml file to see if I can reproduce the error?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;





从QQ邮箱发来的超大附件

100008009.rar (57.71M, 2022年09月17日 16:50 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=2336613910ae029e0c48e5181538544d0406500a520c51534c03565c5615520405574c010508024f0057070d025b0351590f500a33356653510651090b08565b4f44004b3305&code=a6a938fb

**Comment by janusson** [comment]
Sweet lord, close this

**Comment by janusson** [comment]
Dude, you need to explain your problem in a much more coherent way or no one can help you.

**Comment by LXXiaogege** [comment]
Okay, sorry, my problem is that I used the Matchms API to read my mzML file and returned an empty generator, which translates to a list and looks like this: [], but there was no error, so I was wondering, what is the file format MatchMs needs to input, and how can I convert my raw data into a format MatchMs can load?

My raw data is a.raw file and I am using MSConvert to convert it to .mzml file.

**Comment by janusson** [comment]
Just curious, have you read or opened the mzML file in another program (or a library other than matchms) to check the integrity of the file? Proteowizard should be fine for conversion but the conversion settings can also mess up the output mzML file for digestion by another program.

**Comment by LXXiaogege** [comment]
Thank you for your reply，I also think that's the key to this problem. I'm new to this field, so I don't know much about mass spectrometry. How do you usually convert RAW files to MGF, mzML files?

**Comment by janusson** [comment]
Depends on the vendor. Different manufacturers use different software so it can be tedious to convert files. I use my own conversion tool. Which mass spec are you using? How was the data stored and with what software (MassLynx, DataAnalysis)? Some vendors have great conversion tools built in.

**Comment by janusson** [comment]
I can't think of the mzML reader I used to use for checking file integrity (was it mMass? Can that read mzML?)

**Comment by LXXiaogege** [comment]
I see what you mean. I should have asked an environmental science professional what their instrument was before converting, but I've found a way to solve this problem by using OpenChrom to parse it into a CSV file and then generating each mass spectrum as a Specturm object, which can be slow. 
Thanks for your help. I learned a lot

**Comment by janusson** [comment]
all the best, hope it works out well

**Comment by florian-huber** [comment]
Thanks @janusson.
Outside matchms issue, so will be closed.
