### ISSUE TITLE
spectrum typing does not work with IDE's

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#362]
The Spectrum type object is not the same as setting the type to Spectrum. This results in IDE highlighting typing errors, when a Spectrum object is expected and a Spectrumtype object (also called Spectrum) is given. 
Also Spectrum type does not "know" the available methods, like get, which will therefore be highlighted by the IDE as a mistake. 

Suggested change: Remove SpectrumType and just use Spectrum for typing. 

Is there a benefit of using SpectrumType over Spectrum? @florian-huber

**Comment by florian-huber** [comment]
Thanks Niek!
If I remember correctly, the main reason for using the SpectrumType instead of Spectrum was to avoid circular imports. We could try again to see if this is still the case.

**Comment by niekdejonge** [comment]
Most cases do not have any circular import issues, I just change them now when I notice them, unless it gives circular import issues.
