### ISSUE TITLE
error: ms_network.create_network(scores)

### ISSUE THREAD

**Issue by guikool** [matchms/matchms#364]
Dear developers
I've followed the MS2deepscore short tuto to create a network from the GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf to compare results with the classical modified cosine.
Still, in both cases, I've obtained an error during network creation (all previous command in the script work well)
`ValueError: None cannot be a node`

Here is the drawbacks of
`ms_network.create_network(scores)`

ValueError Traceback (most recent call last)
Cell In [23], line 1
----> 1 ms_network.create_network(scores)

File d:\Docs\Logiciels\Anaconda3\envs\ms2deepscore\lib\site-packages\matchms\networking\SimilarityNetwork.py:123, in SimilarityNetwork.create_network(self, scores)
121 # Initialize network graph, add nodes
122 msnet = nx.Graph()
--> 123 msnet.add_nodes_from(unique_ids)
125 # Collect location and score of highest scoring candidates for queries and references
126 similars_idx, similars_scores = get_top_hits(scores, identifier_key=self.identifier_key,
127 top_n=self.top_n,
128 search_by="queries",
129 ignore_diagonal=True)

File d:\Docs\Logiciels\Anaconda3\envs\ms2deepscore\lib\site-packages\networkx\classes\graph.py:622, in Graph.add_nodes_from(self, nodes_for_adding, **attr)
620 if newnode:
621 if n is None:
--> 622 raise ValueError("None cannot be a node")
623 self._adj[n] = self.adjlist_inner_dict_factory()
624 self._node[n] = self.node_attr_dict_factory()

ValueError: None cannot be a node

**Comment by hechth** [comment]
Seems like some of the id's in your mgf are none - can you check the `unique_ids` vector if it contains `None` values? If so, these need to be removed or filtered it seems.

**Comment by guikool** [comment]
I don't understand, since I use the GNPS library from the tuto: GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf as starting material. All spectra are fully annotated. Where can I found the `unique_ids` vector. Is it in the `spectrum` object?

**Comment by florian-huber** [comment]
The method that makes a network/graph from your data needs to have a name for each node.
You can specify which metadata field to use for that by setting the `identifier_key`.

Examples would be:
```python
ms_network = SimilarityNetwork(identifier_key="name", ...)
ms_network.create_network(scores)
```
or
```python
ms_network = SimilarityNetwork(identifier_key=="spectrum_id", ...)  # or "spectrumid" ?
ms_network.create_network(scores)
```
Depending on what you have in your data.

In the past GNPS has also changed the way they call their own spectrum ID, so I guess it could be `spectrum_id` or `spectrumid`?

**Comment by guikool** [comment]
Ok, if I understand well, the identifier key may be one of the metadata from the source "msp" or "mgf" file?
Here is the metadata from the GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf

```
BEGIN IONS
PEPMASS=408.156
CHARGE=1
MSLEVEL=2
SOURCE_INSTRUMENT=LC-ESI-qTof
FILENAME=p1-A05_GA5_01_17878.mzXML
SEQ=*..*
IONMODE=Positive
ORGANISM=GNPS-NIH-NATURALPRODUCTSLIBRARY
NAME="MLS001141366-01!(2R)-2-[3-[(10aS)-1,3-dioxo-10,10a-dihydro-5H-imidazo[1,5-b]isoquinolin-2-yl]propanoylamino]-2-phenylacetic acid" M+H
PI=Dorrestein
DATACOLLECTOR=VVP/LMS
SMILES=OC(=O)[C@H](NC(=O)CCN1C(=O)[C@@H]2Cc3ccccc3CN2C1=O)c4ccccc4
INCHI=N/A
INCHIAUX=N/A
PUBMED=N/A
SUBMITUSER=vphelan
LIBRARYQUALITY=1
SPECTRUMID=CCMSLIB00000079350
SCANS=1865
```
I've tried:
`ms_network = SimilarityNetwork(identifier_key="SPECTRUMID", ...)`
but still get the same error as above

**Comment by florian-huber** [comment]
`SPECTRUMID` is only how it appears in the mgf file.
Better check the metadata inside matchms with
```python
spectrum.metadata
```
I would guess that it will be found there as `spectrumid` in lower letters (so then setting `identifier_key="spectrumid"` should work).

**Comment by guikool** [comment]
Dear Florian
I finally figure out what happens: the GNPS-NIH-NATURALPRODUCTSLIBRARY.mgf has a `spectrum_id `field whereas the same file in .msp version have not, only a `comment` field.
As you say, change the identifier key by "comment" solved the issue.
Thanks for your explanation, I close the issue

**Comment by guikool** [comment]
Since .msp or .mgf file are far to be normalized across database or software, I would suggest adding a`matchms_id` field of increasing number for each spectra, during msmatch import to the `spectrums` list.
