### ISSUE TITLE
Adduct correction masses

### ISSUE THREAD

**Issue by tharwood3** [matchms/matchms#374]
**Describe the bug**
I think that two of the adduct correction masses in `known_adducts_table.csv` are one electron mass different from what they should be. A table of the adducts and masses in question are below:

| adduct | current correction_mass | recalculated correction_mass | difference |
| ------------- | ------------- | ------------- | ------------- |
| [M+H+2Na]3+  | 15.662453  | 15.6619060 | 0.00055 |
| [M-H2O-H]-  | -19.01839  | -19.017841 | 0.00055 |

**Additional Information**
[M+H+2Na]3+ Calculation:
| proton mass | sodium ion mass |  mass_mult | result |
| ------------- | ------------- | ------------- | ------------- |
| 1.00727647  | 22.98922070 * 2  | 0.33 |15.6619060 |

[M-H2O-H]- Calculation:
| proton mass | H2O mass |  mass_mult | result |
| ------------- | ------------- | ------------- | ------------- |
| -1.00727647  | -18.01056468  | 1 |-19.017841 |

**Sources**

The atomic masses used for the recalculation are from the NIST Atomic Weights and Isotopic Compositions database. Electron and ion masses were also retrieved from NIST.

Coursey, J.S., Schwab, D.J., Tsai, J.J., and Dragoset, R.A. (2015), Atomic Weights and Isotopic Compositions (version 4.1). [Online] Available: http://physics.nist.gov/Comp [2022, 11, 16]. National Institute of Standards and Technology, Gaithersburg, MD.

**Comment by florian-huber** [comment]
Thanks for making this issue.
- First change looks fine to me, looks like electron mass difference was not accounted for.
- Second one, I am not sure. The second correction mass came from here: https://fiehnlab.ucdavis.edu/staff/kind/Metabolomics/MS-Adduct-Calculator

@justinjjvanderhooft can you quickly check?

**Comment by justinjjvanderhooft** [comment]
@florian-huber @tharwood3 regarding the second one, indeed, we took over the value from the list provided by the Fiehnlab, and that seems to be correct - in the calculation above, you did not include the mass of the electron as they did for the negative mode: m(1H+e-) = 1.00782504 u = mass of proton + mass of electron [which higher the proton mass with the difference you observed]

**Comment by tharwood3** [comment]
@justinjjvanderhooft I see. Thanks for double checking! In all other instances of negative mode adducts including a hydrogen loss ([M-H]-, [M+K-2H]-, etc.) the correction mass is calculated with just a proton mass, without the electron mass added back in. I wasn't aware that something else was going on with the H2O loss negative adduct.

**Comment by justinjjvanderhooft** [comment]
@tharwood3 no problem, but since you mentioned it, I made another check and it doesn't make sense that this is the only loss for which the electron is added in....so @florian-huber I would be tempted to make the correction to make them all logic. After all, we are looking at a neutral water loss and a proton loss - these are not necessarily related to each other.... 😎

**Comment by sdrogers** [comment]
I agree @justinjjvanderhooft -- this should be M, minus a (neutral) H2O, minus a proton. I remember finding errors in the Fiehn lab spreadsheet before so would be very careful trusting it.

i.e. I think @tharwood3's calculation for the second one is correct...

`M - H2O - proton = M - (H2O + proton) = M - (2 * 1.00782503214 + 15.9949146221 + 1.00727645199076) = M - 19.0178411`

**Comment by hechth** [comment]
The moment you realize that an electron is actually pretty heavy! 😄

**Comment by florian-huber** [comment]
Sorry, lost track of this.
I recalculated many adduct masses, but only found the two mentioned here to be different by one full electron mass. So I will change those values. A few other values were also off by a bit (e.g. mass of Na+), but that is a very small difference and I had not time to dig deeper.

I will close this issue with #386. Feel free to re-open (or start a new one) if more such things occur.
Thanks a lot @tharwood3 !

**Comment by florian-huber** [comment]
btw. the mentioned differences I saw between the fiehnlab sheet and https://mstools.epfl.ch/info/
