### ISSUE TITLE
Add pickle import/export function

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#375]
Pickle is not a safe format (see [here](https://docs.python.org/3/library/pickle.html)), but it is fast and convenient. At least when handling large datasets in various stages.

I would hence try to add an save and load option for pickle as well to the respective modules.

**Comment by hechth** [comment]
pickle import has been implemented in #396

I think pickle export is something where we don't really need a function for?

**Comment by florian-huber** [comment]
True, we can skip this.
