### ISSUE TITLE
Towards Pipeline and sparse implementation release

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#376]
We are about to add mayor changes to matchms!

- Pipeline --> ability to define a full matchms workflow via a Pipeline object, or via a yaml-script.
- Sparse implementation of `Scores` --> ability to handle much larger score calculations

A lot has been implemented already (#370). This issue is to track and discuss what's still missing.

First of all, this is how running a Pipeline would look like:
```python
from matchms import Pipeline

pipeline = Pipeline("my_config_file.yaml")
pipeline.run()
```
An [example yaml file](https://github.com/matchms/matchms/blob/be840309e7927343d4d69b2beb2d47d4d5a7b3f6/tests/test_pipeline.yaml) is used for testing.
An alternative way to use it:
```python
pipeline = Pipeline()
pipeline.query_files = "spectrums_file.msp"
pipeline.filter_steps_queries = [
    ["default_filters"],
    ["add_parent_mass"],
    ["normalize_intensities"],
    ["select_by_relative_intensity", {"intensity_from": 0.0, "intensity_to": 1.0}],
    ["select_by_mz", {"mz_from": 0, "mz_to": 1000}],
    ["require_minimum_number_of_peaks", {"n_required": 5}]
]
pipeline.score_computations = [["precursormzmatch",  {"tolerance": 120.0}],
                               ["cosinegreedy", {"tolerance": 1.0}]
                               ["filter_by_range", {"name": "CosineGreedy_score", "low": 0.3}],
                               ["filter_by_range", {"name": "CosineGreedy_matches", "low": 5}],
                               ["modifiedcosine", {"tolerance": 1.0}]]

pipeline.run()
```
It would be great to get some feedback on the API. Would it work as it is now or should we change the design?

Here is what we still have to do/implement/test

## Must haves/Fixes:
- [x]  Fill the **check_pipeline** method, something to check if all files exist and all named filters and scores exist before running the pipeline (to avoid running something for hours before discovering a stupid mistake).
- [ ] Add networking to Pipeline so that users can have a pipeline which also outputs a graph to be imported in Cytoscape or similar tools.
- [x] Test runs will full-sized datasets (I currently try a run comparing 280.000 x 280.000 spectra)
- [x] Pipeline needs to avoid any dense/numpy representation of scores (--> e.g. PrecursorMZMatch sparse)

## Nice to have
- [ ] Add option to input list of Spectrum objects (instead of only import from file) to better combine the pipeline with other workflows.
- [ ]  Pipelines can take a while to compute, so **add progress information**: progress bars, but possibly also ways to pass the progress to external tools that want to make use of matchms
- [ ]  Add a sparse output option to the `-matrix()` method. Right now many pipelines might start with a quick check like `PrecursorMzMatch` or `MetadataMatch` to quickly remove many pairs. Still, those methods currently start by initializing an empty numpy array which can get huge if we run a pipeline on many-vs-many spectra.

**Comment by florian-huber** [comment]
Brief update @hechth
I ran a few test pipelines. Performance wise that looks good (e.g. possible to handle 200.000 x 200.000 score computations).
But I also found a bug in the Pipeline (ignoring certain spectrum pairs which shouldn't be ignored) that I will fix asap.

**Comment by florian-huber** [comment]
Update. Bug was part of `sparsestack` and is fixed for version >= 0.4.1.

Additional tests in (`test_scoring_method_consistency.py`) now check consistency for most scoring methods across the different implementation (`pair()`, `matrix()`, `sparse_array()` as well as using `Pipeline`).

**Comment by florian-huber** [comment]
Update:
My tests were running fine even for large scale comparisons (as long as total number of stored scores fits into memory).

Current plan is to merge the PR very soon, which will **not be version 1.0** yet (but a proper release). For 1.0 I would give it a few more weeks and try to address more of the todo-list in this issue.

**Comment by florian-huber** [comment]
Current state is now released as **matchms 0.18.0**.

**Comment by hechth** [comment]
@florian-huber thanks for the great work - sorry, I've been struggling to find the time lately to look through things. I will try to run some more advanced use cases of the pipeline throughout the next week and get back on track with the todo for the release 1.0.

**Comment by hechth** [comment]
@florian-huber I found some issues while updating to the new Galaxy wrappers - I'll find some time to work on this and to fix some of the bugs related to the Pipeline and will also try to clean the code a bit.

**Comment by hechth** [comment]
@florian-huber I think the progress bar is implemented, right? I'd say let's create single issues for the remaining points and let's close this one?

**Comment by florian-huber** [comment]
@hechth Yes, single issues are better to handle at this point. Progress ars have partly been implemented, but they are not yet working/available for all similarity score computations. So that should remain an issue I think.
