### ISSUE TITLE
`reduce_to_number_of_peaks` will always raise a ValueError

### ISSUE THREAD

**Issue by anupriyatripathi** [matchms/matchms#377]
https://github.com/matchms/matchms/blob/1284caab52f948115b740b9dd1a73f6c5c5d1d21/matchms/filtering/reduce_to_number_of_peaks.py#L38

If I understand correctly, this needs to be under an `if` statement checking for the absence of `parent_mass`

**Comment by florian-huber** [comment]
(sorry, gave a too quick wrong reply first, here the edit)
The line is actually fine.
Whenever it reaches the line it will raise an exception, but that's intentional.
If there is either a parent mass or if `ratio_desired` is set to None (which is the default) the function will exit before this line with `return` (line 35 or 37).

**Comment by anupriyatripathi** [comment]
Thanks for clarifying the expected behavior. I'd change the `Post-process spectra - step 2`  (cell 10) [here](https://github.com/iomega/spec2vec_gnps_data_analysis/blob/master/notebooks/iomega-5-train-spec2vec-model.ipynb) to something like the following:
```
def post_process_step2(s):
    s = reduce_to_number_of_peaks(s, n_required=10, ratio_desired=0.5)
    return s

spectrums_processed2 = []
for s in spectrums:
    try:
        s_out = post_process_step2(s)
        spectrums_processed2.append(s_out)
    except:
        spectrums_processed2.append(None)
        continue
      
# omit spectrums that didn't qualify for analysis
spectrums = [s for s in spectrums_processed2 if s is not None]
```

Because it exits the following loop if there is no way to catch the exception 
```
# apply post processing steps to the data
spectrums = [post_process_step2(s) for s in spectrums]
```

**Comment by florian-huber** [comment]
Hi @anupriyatripathi , that looks like a good solution in this case.

Matchms also offers such an option with `require_precursor_mz()`.

This would look like
```python
def post_process_step2(s):
    s = require_precursor_mz(s)  # will return None if no proper precursor-m/z is found
    s = reduce_to_number_of_peaks(s, n_required=10, ratio_desired=0.5)
    return s

spectrums_processed2 = [post_process_step2(s) for s in spectrums]
spectrums_processed2 = [s for s in spectrums_processed2 if s is not None]
```
(should do the same thing as your code above)

**Comment by florian-huber** [comment]
I guess this can be closed now. If not please simply re-open!

**Comment by anupriyatripathi** [comment]
The above code block still gives the same error. `Cannot use ratio_desired for spectrum without parent_mass.`
I'm not sure if `require_precursor_mz(s)` is behaving as expected. 

(I don't think I have permissions to re-open this issue)
