### ISSUE TITLE
Fix reading of fingerprints

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#387]
**Describe the bug**
When a set of spectra containing fingerprints computed with `add_fingerprint` is saved to file and loaded again, the fingerprint is read as string instead of as numpy array of values.

**To Reproduce**
1. call the `add_fingerprint` filter on a set of spectra
2. call `save_to_msp`
3. call `load_from_msp`
4. calculate fingerprint similarity

**Expected behavior**
Fingerprints should be initialized correctly if they are correctly in the file.

```
Traceback (most recent call last):
  File "/tmp/tmpdjhh11sn/job_working_directory/000/6/configs/tmp78wek4nl", line 15, in <module>
    new_scores = scores.calculate(similarity, name="FingerprintSimilarity_jaccard", array_type="numpy")
  File "/home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/matchms/Scores.py", line 175, in calculate
    new_scores = similarity_function.matrix(self.references,
  File "/home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/matchms/similarity/FingerprintSimilarity.py", line 155, in matrix
    idx_fingerprints2)] = jaccard_similarity_matrix(fingerprints1,
  File "/home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1mNo implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(array([unichr x 17], 1d, C), Tuple(int64, slice<a:b>))
 
There are 22 candidate implementations:
[1m   - Of which 20 did not match due to:
   Overload of function 'getitem': File: <numerous>: Line N/A.
     With argument(s): '(array([unichr x 17], 1d, C), Tuple(int64, slice<a:b>))':[0m
[1m    No match.[0m
[1m   - Of which 2 did not match due to:
   Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 166.
     With argument(s): '(array([unichr x 17], 1d, C), Tuple(int64, slice<a:b>))':[0m
[1m    Rejected as the implementation raised a specific error:
      NumbaTypeError: [1mcannot index array([unichr x 17], 1d, C) with 2 indices: Tuple(int64, slice<a:b>)[0m[0m
  raised from /home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/numba/core/typing/arraydecl.py:88
[0m
[0m[1mDuring: typing of intrinsic-call at /home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/matchms/similarity/vector_similarity_functions.py (31)[0m
[1m
File "../../../../../../home/hechth/miniconda3/envs/__matchms@0.18.0/lib/python3.10/site-packages/matchms/similarity/vector_similarity_functions.py", line 31:[0m
[1mdef jaccard_similarity_matrix(references: np.ndarray, queries: np.ndarray) -> np.ndarray:
    <source elided>
        for j in range(size2):
[1m            scores[i, j] = jaccard_index(references[i, :], queries[j, :])
[0m            [1m^[0m[0m

```

**Comment by hechth** [comment]
@florian-huber I think there are two ways how to actually deal with this: either we actually load the fingerprint from the file or we decide to not deal with it, but then the fingerprint also should not be stored in the file I think.

**Comment by hechth** [comment]
@justinjjvanderhooft @sdrogers  are you maybe aware of other tools which use molecular fingerprints stored in MSP files?

**Comment by justinjjvanderhooft** [comment]
Not from the top of my head - but that may be true for tools that rely on the msp file as the main source of data input....(like the MS-DIAL toolkit, etc.)

**Comment by florian-huber** [comment]
Fingerprints can be quite large. We usually worked with 2048-bit fingerprints which already could take more space than the rest of a spectrum (peaks + metadata). In that sense, we could discuss if a fingerprint belongs into the file formats we offer (msp, but also mgf, mzxml ...).

I agree @hechth, if we leave it in, then the loading functions should be able to handle this properly. So, I see three options:

1. write fingerprints to files (as is done now) --> expand `load_from_msp` so that it imports fingerprints a np.array (and: also check for the other file formats as well!)
2. ignore fingerprint when spectrum is saved to file (but add a logger warning to make this clear)
3. Both: Fix (1) but make storing fingerprints optional, with default being set to `False`

If we know of use cases where people save and load spectra including fingerprints with `matchms`, I would prefer going to (3). Otherwise, for time/efficiency reasons I would go for (2).

PS:
Somewhat related is the question of neutral losses. Those we do not write to the files, because they can consume a lot of space an are cheap to compute.

**Comment by hechth** [comment]
I agree - but it seems like except for the fingerprint similarity there is not much going on. I think plenty of people use those for QSAR models etc. but there they usually use some specific fingerprints, so I'm not sure how useful it would be to serialize them, especially to a text file. Since they are binary, it is way more efficient to just store them as actual binary data.

So maybe I'd vote rather for not storing them and requiring them always to be computed. Or even just trying to compute them on the fly in the fingerprint similarity score ... so to have them completely outside of the filters. Then the fingerprint similarity scores would only require the InChI or SMILES to be present to actually compute the fingerprint.

**Comment by florian-huber** [comment]
Sounds good to me, let's then go for option (2), which means:
- don't write fingerprints to files (unless we add binary formats, pickle etc.)
- add a logger info or warning when fingerprints are found but not saved?
