### ISSUE TITLE
Inner join does not remove non-matching pairs

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#397]
**Describe the bug**
The `inner join` feature doesn't really work it seems - the output still contains elements where the second entry is NA after having 2 layers, so the initial data doesn't get reduced after realizing that the second layer is NA.

**Comment by florian-huber** [comment]
Can you give an example of where it fails?
Then I can look into it.

**Comment by hechth** [comment]
I think this has actually been solved and was related to the printing mechanism.
