### ISSUE TITLE
save_as_msp fails if "write_peak_comments" is true and peak comments are empty

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#407]
**To Reproduce**
1. Load spectra without peak comments
2. Save spextra to msp with "write_peak_comments" as true
3. Observe bug

**Expected behavior**
A warning should be written to the logfile and the program should just not write the peak comments.

**Comment by hechth** [comment]
@robinschmid do you know by any chance if it is possible to include peak annotations in mgf files, and which format is usually used for that?

**Comment by robinschmid** [comment]
Just saw this. 
I have seen people just adding a third column in the data block for annotations... But not sure if all parsers will recognize that.

**Comment by hechth** [comment]
@robinschmid there are some dedicated formats for proteomics, but currently this isn't supported. I would also wait until these things are more formalized before making an implementation.
