### ISSUE TITLE
Error when using MSP from NIST MS Search

### ISSUE THREAD

**Issue by brooklynnrm** [matchms/matchms#413]
An error is reported when trying to match query spectra from RamClustR in .msp format with ref spectra from NIST MS Search in .msp format.

**Examples of Errors:**
![image](https://github.com/matchms/matchms/assets/133389579/8cd4a112-deb0-4e94-80b9-f82c39306021)

![image](https://github.com/matchms/matchms/assets/133389579/a27318b9-856c-4598-893e-f6c6bc662be7)

**Example MSP Format**
Name: o-Nitroaniline
Instrument_type: GC Orbitrap
Instrument: Exactive GC Orbitrap
Sample_inlet: GC
Ionization: EI
Spectrum_type: in-source
Retention_index: 1406
Synon: 1-Amino-2-Nitrobenzene
Synon: 1-Nitro-2-aminobenzene
Synon: 2-Aminonitrobenzene
Synon: 2-Nitroaniline
Synon: 2-Nitrobenzenamine
Synon: 2-Nitro-benzeneamine
Synon: Aniline, o-nitro-
Synon: Azoene Fast Orange GR Base
Synon: Azoene Fast Orange GR Salt
Synon: Azofix Orange GR Salt
Synon: Azogene Fast Orange GR
Synon: Azoic Diazo Component 6
Synon: Benzenamine, 2-nitro-
Synon: Brentamine Fast Orange GR Base
Synon: Brentamine Fast Orange GR Salt
Synon: C.I. 37025
Synon: C.I. Azoic Diazo Component 6
Synon: Devol Orange B
Synon: Devol Orange Salt B
Synon: Diazo Fast Orange GR
Synon: Fast Orange Base GR
Synon: Fast Orange Base JR
Synon: Fast Orange GR Base
Synon: Fast Orange GR Salt
Synon: Fast Orange O Base
Synon: Fast Orange O Salt
Synon: Fast Orange Salt GR
Synon: Fast Orange Salt JR
Synon: Hiltonil Fast Orange GR Base
Synon: Hiltosal Fast Orange GR Salt
Synon: Hindasol Orange GR Salt
Synon: Natasol Fast Orange GR Salt
Synon: NSC 9796
Synon: o-Aminonitrobenzene
Synon: ONA
Synon: o-Nitranilin
Synon: o-Nitraniline
Synon: Orange Base Ciba II
Synon: Orange Base Irga II
Synon: Orange GRS Salt
Synon: Orange Salt Ciba II
Synon: Orange Salt Irga II
Synon: Orthonitroaniline
Synon: UN 1661 (Related)
Formula: C6H6N2O2
MW: 138
ExactMass: 138.042928
CAS#: 88-74-4
DB#: 1
Comments: Contributor="Thermo Fisher Scientific"
Num Peaks: 60
50.01519 3.19
51.02300 5.06
52.0182 8.58
52.03081 2.83
53.03861 11.71
54.03392 0.88
61.00728 6.91
62.01511 13.52
63.01040 1.49
63.01845 0.60
63.02299 48.81
64.01818 8.00
64.02635 2.66
64.03084 19.26
65.02602 12.25
65.03857 277.39
66.03385 7.14
66.04174 14.46
73.00735 1.46
74.01518 10.05
75.01034 4.85
75.02301 4.22
76.01817 12.38
77.02599 12.08
78.03389 7.50
78.04648 4.12
79.04170 7.36
80.01308 2.14
80.04945 241.36
81.05283 12.78
81.05730 1.99
87.01041 1.85
88.01820 2.58
89.02613 2.62
90.03390 32.92
91.03728 2.14
91.04155 51.44
92.04941 238.85
93.04648 0.65
93.05280 15.14
103.02902 2.67
104.03691 2.77
105.04482 4.14
106.05261 1.15
107.06049 2.49
108.04437 276.38
108.06818 9.71
109.04149 1.01
109.04815 18.08
110.06005 1.20
120.03183 13.83
121.03964 82.95
122.04298 5.10
122.04756 18.53
123.05090 1.35
137.03467 1.59
138.04233 999.00
139.03952 7.18
139.0457 64.83
140.0495 1.19

or

Name: 2-Propanone
Retention_index: User=455
InChIKey: CSCPPACGZOOCGX-UHFFFAOYSA-N
Synon: Acetone
Synon: Methyl ketone
Synon: (CH3)2CO
Synon: .beta.-Ketopropane
Synon: Aceton
Synon: Chevron acetone
Synon: Dimethyl ketone
Synon: Dimethylformaldehyde
Synon: Dimethylketal
Synon: Ketone propane
Synon: Ketone, dimethyl-
Synon: Propan-2-one
Synon: Propanone
Synon: Pyroacetic acid
Synon: Pyroacetic ether
Synon: Sasetone
Synon: AI3-01238
Synon: CASWELL NO. 004
Synon: CCRIS 5953
Synon: EINECS 200-662-2
Synon: EPA PESTICIDE CHEMICAL CODE 004101
Synon: FEMA NO. 3326
Synon: HSDB 41
Synon: NSC 135802
Synon: RCRA WASTE NO. U002
Synon: UN1090
Formula: C3H6O
MW: 58
ExactMass: 58.041865
CAS#: 67-64-1
DB#: 1
Comments: SpectrumID="1113868" Source="O-30-797-0" Classification="Ketones" QI="950" Note="Removed - expert review (acetone, no molecular ion )" SplashID="splash10-0006-9000000000-699f7b8f9f9e9a96c461"
Num Peaks: 9
26 50; 27 11; 29 37; 39 37; 40 1; 
42 75; 43 999; 44 23; 45 2;

**Comment by florian-huber** [comment]
@brooklynnrm 
To better understand the issue: Was this within a Galaxy workflow? Or did this also happen when using matchms directly?

**Comment by hechth** [comment]
@florian-huber I managed to replicate the issue within matchms < 0.19 - also, in matchms >= 0.19, the comments are not parsed correctly in this specific case, meaning that all text after the first <xzy>="..." is put into the xyz metadata field.
