### ISSUE TITLE
adding getitem to Spikes might avoid ugly indexing

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#43]
see https://github.com/matchms/matchms/pull/33#discussion_r429776938

https://github.com/matchms/matchms/blob/58c45ed4ef49c104372098def915750625d42f7a/matchms/filtering/reduce_to_number_of_peaks.py#L32-L35

**Comment by cwmeijer** [comment]
also see #54

**Comment by florian-huber** [comment]
That piece is purely internal to one filter function. I would skip optimizing this further and close the issue.
