### ISSUE TITLE
MGF import error due to pyteomics pepmass parsing

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#430]
I got an error when importing spectra from mgf files that contained `PEPMASS` entries like the following:
```
PEPMASS=281,2013306
```

Error was `PyteomicsError: Pyteomics error, message: 'MGF format error: cannot parse PEPMASS = 281,2013306'`

**Comment by hechth** [comment]
@florian-huber did you report this to pyteomics? And is it only since the latest version?

**Comment by hechth** [comment]
Possible duplicate: https://github.com/matchms/matchms/issues/452
