### ISSUE TITLE
Group filtering functions

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#432]
The matchms filtering functions are now all in one folder, which makes it hard to select the filtering functions needed for your issue.

Suggestion:
Group the filter functions by functionality. E.g.:
- Peak filtering
  - Removing peaks
  - Checking peak quality
- Metadata cleaning
  - Harmonizing metadata names
  - Adding missing metadata
  - Annotation cleaning (smiles, inchi key, inchi)

__init__.py in filtering should still contain all the links to the filter functions, to make it flexible to change the sub(folder) in which these functions are stored.

**Comment by florian-huber** [comment]
This underwent a few changes already with the latest PRs (#440, # 448), but we should revise this more carefully. Right now this produces issues with the Conda CI --> https://github.com/bioconda/bioconda-recipes/pull/41784#issuecomment-1615769099

I suggest the following:
- Add a `SpectrumProcessing` class that will take care of the different cleaning, filtering etc. steps in a more user-friendly way.
- In the back of this we will keep all the different filtering functions we have, but using them directly will be meant for developers mostly.
- We can also add a bit more structure (though not over-engineer this), e.g., a folder for `utils`, a folder for peak related actions (`peak_processing`) and a folder for metadata related functions (`metadata_processing`).

What do you think @hechth @niekdejonge ?

**Comment by florian-huber** [comment]
--> working on it in #454

**Comment by florian-huber** [comment]
--> and #455

**Comment by niekdejonge** [comment]
I agree that the effort needed for converting all functions to classes might not be worth it. And a SpectrumProcessing class might indeed be a lot easier to implement. 

How do you plan to let SpectrumProcessing differ from Pipeline? Would you like to separate the cleaning and the scores calculations into SpectrumProcessing and Pipeline? Or would SpectrumProcessing be part of Pipeline?

I have a few things that might reconsidering the Filter classes worth it would be: 
- How would you store which functions should be run before the other? With the Filter classes, I would like to add a method that returns required_filter_steps. This method can be called by Pipeline to check if the previous steps have already been performed/or to reorder the filter functions. For the SpectrumProcessing you might store the required order in SpectrumProcessing itself as a list of rules, but this might become confusing quickly. 
- We have different types of filter functions, with a different type of behavior. E.g. RequiredMetadata returns None or an unchanged spectrum or RepairSpectrum changes the spectrum or not but never sets to None. This standardization will make the code more robust and might adding future functionality in one go a lot easier. If we now think of adding some functionality for for instance the Pipeline class, we would need to add this to all filter functions one by one. If we have these classes we can easily add a method to the parent class without the need to add this to every Filter function. 
- For a processing report you would need to know if a spectrum was changed and how. A SpectrumProcessing class could of course at every point check if something was changed by a function, by comparing the spectrum before and after each filter, but this would be a lot of unnecessary o.verhead. Or maybe capture the Logging and convert this into a summary? By having a Filter class, this could do the counting within the class, by having a self.count_changes variable in the class. Which just adds one for each type of change. Which can easily be used by Pipeline to create a summary. 

I still agree that the amount of work needed to convert the filtering functions into classes might not be worth it, but it might give a lot more robust and future-proof structure for the filtering of matchms. Let me know what you think! @florian-huber

**Comment by niekdejonge** [comment]
I will make a PR to fix the bioconda issues

**Comment by florian-huber** [comment]
> I will make a PR to fix the bioconda issues

I think this should be fixed with #454

**Comment by florian-huber** [comment]
This has partly been solved (the grouping part which is in the title). We can continue the discussion in #467.

**Comment by florian-huber** [comment]
Niek and I had some more discussions in some of the recent PRs on `OOP` vs `functional` when it comes to the matchms filers. A few options we discussed where:

- Moving fully to classes, e.g. something a bit like
```python
class BaseSpectrumFilter:
    def __init__(self):
        pass

    def filter(self, spectrum_in: SpectrumType) -> SpectrumType:
        if spectrum_in is None:
            return None
        spectrum = spectrum_in.clone()
        return self.apply_filter(spectrum)

    def apply_filter(self, spectrum: SpectrumType) -> SpectrumType:
        """This method should be implemented by child classes."""
        raise NotImplementedError


class XYZFilter(BaseSpectrumFilter):
    def apply_filter(self, spectrum: SpectrumType) -> SpectrumType:
        # Do the specific filtering for XYZ here.
        # ...
        return spectrum
```

- or using functional but add decorators:
```python
def spectrum_filter_decorator(filter_function):
    def wrapper(spectrum_in: SpectrumType, **args) -> SpectrumType:
        if spectrum_in is None:
            return None
        spectrum = spectrum_in.clone()
        return filter_function(spectrum, **args)
    return wrapper

@spectrum_filter_decorator
def filter_xyz(spectrum: SpectrumType, **args) -> SpectrumType:
    # Do the specific XYZ filtering here.
    # ...
    return spectrum
```

- Or a hybrid thing with filters as classes and for each a wrapper function like:
```python
def apply_xyz_filter(spectrum_in: SpectrumType) -> SpectrumType:
    return XYZFilter().filter(spectrum_in)
```
