### ISSUE TITLE
Different Logging for Pipeline filtering

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#433]
The pipeline now prints logging for each matchms function, however, this is not really useful when cleaning libraries, since it is too detailed.
In addition to logging, it would be nice to get an overview of the effect of each filtering step.

So for instance: 
20.000 spectra were removed because they did not have enough peaks
100.000 spectra got the parent mass added by add_precursor_mz
etc.

This makes it a lot easier for the user to spot mistakes in the library cleaning. 

@florian-huber @hechth What do you think?

**Comment by niekdejonge** [comment]
If #434 is implemented. Any filtering object can just store a variable that increases by one everytime a spectrum is removed/adjusted. And a method of the class can determine what the pipeline logging method should be. For specific classes like Require() we could store the number of spectra checked and removed. And for Repair we can store the specific thing that was removed. For RepairAdducts() we could count each adduct type that was repaired separately

**Comment by hechth** [comment]
Yeah for the pipeline logging having some summary functions would be nice.

**Comment by niekdejonge** [comment]
This has been fixed by implementing the ProgressingReport.
