### ISSUE TITLE
Retire macOS python 3.7 support

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#445]
**Describe the bug**
Seems like macOS with Python 3.7 lacks some core libraries which have become mandatory by now in matchms (bzip) which are not available on the macOS runners with python 3.7

Maybe it is time to retire python 3.7 from the CI?

**Comment by niekdejonge** [comment]
I noticed this too for MS2Query. It might be just an issue with running setup-python for running actions on GitHub https://github.com/actions/setup-python/issues/682 So it might be fixed soon and it might actually still work for normal users.
Still retiring 3.7 might be okay to do at some point

**Comment by florian-huber** [comment]
Fine with me, I will remove it from the CI pipeline!
