### ISSUE TITLE
Warning interpret_pepmass

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#446]
Even when the precursor_mz is (almost) the same as interpret_pepmass a warning is given by matchms. 

2023-06-22 19:23:00,537:WARNING:matchms:interpret_pepmass:Overwriting existing precursor_mz 458.8559 with new one: 458.8559

There is already a check, but this check is best replaced with checking if it is close up to 3 decimals. To reduce the overload of warnings.

**Comment by florian-huber** [comment]
Working on it in #460
