### ISSUE TITLE
_interpret_pepmass error

### ISSUE THREAD

**Issue by ADablanc** [matchms/matchms#452]
Hello !

There is a bug with the function _get_mz_intensity_charge of _interpret_pepmass.

**BUG:**

File "C:\Users\Axel\Documents\PYTHON\MSP_V3\msp_v3\scripts\MAIN.py", line 58, in <module>
    spectrum_list = list(load_from_msp(msp_path))
  File "C:\Users\Axel\Documents\PYTHON\MSP_V3\venv\lib\site-packages\matchms\importing\load_from_msp.py", line 52, in load_from_msp
    yield Spectrum(mz=mz,
  File "C:\Users\Axel\Documents\PYTHON\MSP_V3\venv\lib\site-packages\matchms\Spectrum.py", line 91, in __init__
    self._apply_metadata_harmonization()
  File "C:\Users\Axel\Documents\PYTHON\MSP_V3\venv\lib\site-packages\matchms\Spectrum.py", line 102, in _apply_metadata_harmonization
    metadata_filtered = _interpret_pepmass_metadata(self.metadata)
  File "C:\Users\Axel\Documents\PYTHON\MSP_V3\venv\lib\site-packages\matchms\filtering\interpret_pepmass.py", line 33, in _interpret_pepmass_metadata
    mz, intensity, charge = _get_mz_intensity_charge(pepmass)
  File "C:\Users\Axel\Documents\PYTHON\MSP_V3\venv\lib\site-packages\matchms\filtering\interpret_pepmass.py", line 67, in _get_mz_intensity_charge
    values[i] = pepmass[i]
IndexError: list assignment index out of range

**PROBLEMATIC SPECTRUM:**

Name: 1-Kestose
Synon: $:00in-source
DB#: MoNA001675
InChIKey: VAWYEUIPHLMNNF-OESPXIITSA-N
Spectrum_type: MS2
Ion_mode: P
Formula: C18H32O16
MW: 504
ExactMass: 504.169034944
Comments: "computed [M+Cl]-=539.622034944" "InChI=InChI=1S/C18H32O16/c19-1-6-9(23)12(26)13(27)16(31-6)34-18(15(29)11(25)8(3-21)33-18)5-30-17(4-22)14(28)10(24)7(2-20)32-17/h6-16,19-29H,1-5H2/t6-,7-,8-,9-,10-,11-,12+,13-,14+,15+,16-,17-,18+/m1/s1" "computed SMILES=OCC1OC(OC2(OC(CO)C(O)C2O)COC3(OC(CO)C(O)C3O)CO)C(O)C(O)C1O" "computed [2M+H-H2O]+=991.3306998879999" "computed [2M+K]+=1047.436369888" "computed [M+H]+=505.177004944" "computed [2M+Na]+=1031.327839888" "computed [2M+Cl]-=1043.791069888" "computed [2M+HAc-H]-=1067.3820998879999" "computed [M-H20-H]-=485.15064494399996" "computed [M-H]-=503.161758944" "computed [2M-H]-=1007.3307938879999" "computed [M+Na]+=527.1588049439999" "computed [M+H-H2O]+=487.161664944" "computed [2M+NH4]+=1026.376649888" "computed [M+NH4]+=522.2076149439999" "computed [M+K]+=543.267334944" "computed [2M+H]+=1009.346039888" "computed [M+HAc-H]-=563.2130649439999" "rtinseconds=0.005" "pepmass=505.0" "sample introduction=Direct Infusion (DI)" "ionization=Electrospray Ionization (ESI)" "author=Biswapriya B. Misra" "computed spectral entropy=1.0397207708399179" "computed normalized entropy=0.946394630357186" "SPLASH=splash10-0a4i-0003090000-d95999e0141df8aa4d9e" "submitter=submitter = Biswapriya Misra (Wake Forest School of Medicine)" "MoNA Rating=2.5"
Num Peaks: 5
387.3 50.000000
387.4 0.000000
505 0.000000
505.1 50.000000
505.2 100.000000

**Comment by hechth** [comment]
@ADablanc is this still there is the newest matchms version?

**Comment by ADablanc** [comment]
Hi @hechth ! Yes this bug still there in matchms 0.21.1

**Comment by florian-huber** [comment]
@hechth should we include the above spectrum into our tests?
Or was this already done with the update to 0.21.2 ?

**Comment by ADablanc** [comment]
Hi!  This issue still there with matchms 0.22.0

**Comment by hechth** [comment]
@ADablanc can you check if the error is still there with the development version of matchms or 0.23.1? Thanks!

**Comment by ADablanc** [comment]
Hello @hechth. 

I check with the previous spectrum, with 0.23.1:

Name: 1-Kestose
Synon: $:00in-source
DB#: MoNA001675
InChIKey: VAWYEUIPHLMNNF-OESPXIITSA-N
Spectrum_type: MS2
Ion_mode: P
Formula: C18H32O16
MW: 504
ExactMass: 504.169034944
Comments: "computed [M+Cl]-=539.622034944" "InChI=InChI=1S/C18H32O16/c19-1-6-9(23)12(26)13(27)16(31-6)34-18(15(29)11(25)8(3-21)33-18)5-30-17(4-22)14(28)10(24)7(2-20)32-17/h6-16,19-29H,1-5H2/t6-,7-,8-,9-,10-,11-,12+,13-,14+,15+,16-,17-,18+/m1/s1" "computed SMILES=OCC1OC(OC2(OC(CO)C(O)C2O)COC3(OC(CO)C(O)C3O)CO)C(O)C(O)C1O" "computed [2M+H-H2O]+=991.3306998879999" "computed [2M+K]+=1047.436369888" "computed [M+H]+=505.177004944" "computed [2M+Na]+=1031.327839888" "computed [2M+Cl]-=1043.791069888" "computed [2M+HAc-H]-=1067.3820998879999" "computed [M-H20-H]-=485.15064494399996" "computed [M-H]-=503.161758944" "computed [2M-H]-=1007.3307938879999" "computed [M+Na]+=527.1588049439999" "computed [M+H-H2O]+=487.161664944" "computed [2M+NH4]+=1026.376649888" "computed [M+NH4]+=522.2076149439999" "computed [M+K]+=543.267334944" "computed [2M+H]+=1009.346039888" "computed [M+HAc-H]-=563.2130649439999" "rtinseconds=0.005" "pepmass=505.0" "sample introduction=Direct Infusion (DI)" "ionization=Electrospray Ionization (ESI)" "author=Biswapriya B. Misra" "computed spectral entropy=1.0397207708399179" "computed normalized entropy=0.946394630357186" "SPLASH=splash10-0a4i-0003090000-d95999e0141df8aa4d9e" "submitter=submitter = Biswapriya Misra (Wake Forest School of Medicine)" "MoNA Rating=2.5"
Num Peaks: 5
387.3 50.000000
387.4 0.000000
505 0.000000
505.1 50.000000
505.2 100.000000

Unfortunately the bug still there. but not the same error message: 

Traceback (most recent call last):
  File "C:\Users\Axel\PycharmProjects\msp_v3\scripts\MAIN.py", line 65, in <module>
    spectrum_list = list(load_from_msp(msp_path))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axel\PycharmProjects\msp_v3\venv\Lib\site-packages\matchms\importing\load_from_msp.py", line 52, in load_from_msp
    yield Spectrum(mz=mz,
          ^^^^^^^^^^^^^^^
  File "C:\Users\Axel\PycharmProjects\msp_v3\venv\Lib\site-packages\matchms\Spectrum.py", line 90, in __init__
    self._metadata.harmonize_values()
  File "C:\Users\Axel\PycharmProjects\msp_v3\venv\Lib\site-packages\matchms\Metadata.py", line 102, in harmonize_values
    metadata_filtered = _interpret_pepmass_metadata(self.data)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axel\PycharmProjects\msp_v3\venv\Lib\site-packages\matchms\filtering\metadata_processing\interpret_pepmass.py", line 35, in _interpret_pepmass_metadata
    mz, intensity, charge = _get_mz_intensity_charge(pepmass)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Axel\PycharmProjects\msp_v3\venv\Lib\site-packages\matchms\filtering\metadata_processing\interpret_pepmass.py", line 73, in _get_mz_intensity_charge
    pepmass = matches[0].split(",")
              ~~~~~~~^^^
IndexError: list index out of range

**Comment by niekdejonge** [comment]
I think #584 should fix the issue @ADablanc 
Sorry for the long time it took to fixing this issue...
