### ISSUE TITLE
Improve function name and documentation

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#457]
It is not fully clear what this function actually does. What does it mean "mass of the adduct"? Mass of the ion that is attached to the main molecule or how should this be understood?

https://github.com/matchms/matchms/blob/1f52ba0ecfe34ff153ec9b29420dc8f5a1d2332e/matchms/filtering/filter_utils/interpret_unknown_adduct.py#L31-L56

**Comment by niekdejonge** [comment]
I noticed you added additional docstrings to these functions already, thanks! Sorry for the lacking docstrings, was a bit in a hurry to finish everything before my holidays. I will do a check and improve the docstrings where needed.

**Comment by niekdejonge** [comment]
Will be fixed with #469
