### ISSUE TITLE
Unclear why isort test is failing

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#46]
In PR #45 half of the tests fail because of isort complaining about ``Imports are incorrectly sorted.``.
Even when running isort on one of the named files (``add_fingerprint()``) that didn't disappear.

I am now not sure if there is something going wrong with the isort test, or whether import must be in one very particular order and format (in which case that should be specified to avoid unlimited trial&error).

**Comment by jspaaks** [comment]
probably run isort and then commit the changes

**Comment by fdiblen** [comment]
also make sure that you have the right environment(correct dependencies installed) etc.

**Comment by jspaaks** [comment]
looks solved, https://github.com/matchms/matchms/pull/45#issuecomment-635939939

**Comment by florian-huber** [comment]
Unfortunately it still fails with the same error even after running ``isort``.

**Comment by jspaaks** [comment]
should be fixed by https://github.com/matchms/matchms/pull/56

**Comment by florian-huber** [comment]
Great, thanks! I will check again once #56 is merged.

**Comment by florian-huber** [comment]
#56 fixed my issues during PR #45 . Thanks!
