### ISSUE TITLE
Consider switching to black as a formatter

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#465]
matchms currently doesn't seem to have a default code formatter configured - I think black would be a good choice, as it is commonly used, fast and gives a reasonable format without much configuration.

**Comment by florian-huber** [comment]
We now use pylint for linting, but could of course also switch to black.
Or do you mean using both a linter and a formatter?

I probably wouldn't call black on purpose, but rather implement it the way we did with isort, or what do you think?

**Comment by florian-huber** [comment]
I played around with `black`. While it generally does a good job, I am not happy with all changes. Problem with black is, that it is not configurable, so either we accept all changes black does, or we don't use it.

One example I was not happy with (wasn't matchms code, but anyway):
```python
assert test_generator.reference_scores_df.shape == (6, 6), "Expected different reduced shape of labels"
```
became:
```python
assert test_generator.reference_scores_df.shape == (
    6,
    6,
), "Expected different reduced shape of labels"
```
