### ISSUE TITLE
SpectrumProcessor class

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#467]
(related to past discussions e.g. in #432)

The goal of a `SpectrumProcessor` class would be:
- it will take care of the different cleaning, filtering etc. steps in a more user-friendly way.
- it allows to get an accumulated report of the main changes (in addition to the many details that end up in the logging file)
- in the back of this we can keep all the different filtering functions we have, but using them directly will be meant for developers mostly.

Can be closed with #455

**Comment by florian-huber** [comment]
I am working on a this in #455. Currently what's possible is this:
```python
from matchms import SpectrumProcessor

processor = SpectrumProcessor("default")
processor.add_filter((
    "require_minimum_number_of_peaks",
    {"n_required":  5}
    ))
processor.add_filter("require_valid_annotation")
spectrum_processed, report = processor.process_spectrum(spectrum, create_report=True)
```

The report comes as a small own class (`ProcessingReport`) which currently can best be read using `print(report)` or `report.to_dataframe()`. That could be changed/improved if needed.
With print you would get something like
```
----- Spectrum Processing Report -----
Number of spectrums processed: 2
Number of spectrums removed: 0
Changes during processing:
              number of changes  number of additions
field                                               
charge                        2                    0
precursor_mz                  0                    2
ionmode                       0                    2
smiles                        0                    2
```
Currently included in the report are ["precursor_mz", "parent_mass", "ionmode", "charge", "smiles", "inchikey", "inchi"], but that can easily be changed (by us, not the user).

@niekdejonge would this cover the functionalities you had in mind?

**Comment by niekdejonge** [comment]
Great work! This would certainly be useful! I had in mind to keep track of which filtering step is actually making the change. So for instance make_charge_int made changes 100 times and add_parent_mass made changes 10 times. This would give a bit more detailed overview, which I think would be useful. But I think this could be implemented still with your approach with a few tweaks. I will leave some comments on the pull request.

**Comment by florian-huber** [comment]
Thanks @niekdejonge !
I meanwhile also added the SpectrumProcessor class to the `Pipeline` class --> #470
I think this makes sense, because otherwise we will always have two "pipelines" for the spectrum processing, which is confusing and hard to maintain.
Another benefit is that now users can list any filter they want in the Pipeline (e.g. the yaml file) and the `SpectrumProcessor` class will take care that the filters come in a correct order.

However, this would currently change the design of the pipeline and break old code because I now have two filter fields in the yaml file, one for the predefined pipeline (None, "basic", "default" ...) and one for the list of any other filter user would like to add.

**Comment by niekdejonge** [comment]
Great! I don't think backward compatibility will yet be a large issue. Until a few months ago there was still a small bug in Pipeline, so I don't think since than a lot of users have picked this up. It will probably mostly be my own pipeline files that can quickly be updated. 

A downside of specifying None, basic, default etc in the yaml file, is that this would make it less reproducible. Since I can imagine that we change what is default at some point. An alternative approach could be to create a yaml file by specifying "default", but creating a Yaml file that contains a list with all the filter steps and settings. What do you think?

**Comment by niekdejonge** [comment]
To clarify the report type I would have in mind would be:

----- Spectrum Processing Report -----
Number of spectrums processed: 3
Number of spectrums removed: 0
Changes during processing:
                   removed spectra  changes  additions
filter                                                
make_charge_int                  0        2          0
interpret_pepmass                0        0          3
derive_ionmode                   0        0          3

I have implemented this now and will make a PR after I fixed the tests

**Comment by niekdejonge** [comment]
@florian-huber I have implemented this in #472 Let me know if you agree with these changes

**Comment by florian-huber** [comment]
Thanks @niekdejonge ! Looks like meaningful changes to me. I will go through the code again and merge it into #455 .

**Comment by florian-huber** [comment]
> A downside of specifying None, basic, default etc in the yaml file, is that this would make it less reproducible. Since I can imagine that we change what is default at some point. An alternative approach could be to create a yaml file by specifying "default", but creating a Yaml file that contains a list with all the filter steps and settings. What do you think?

Good point.  
`Pipeline` already has a `create_workflow_config_file` method which we could simply use for that.

**Comment by florian-huber** [comment]
Done with #455
