### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#488]
In https://github.com/matchms/matchms/actions/runs/5900898046 some tests don't pass.

The test pypi build fails due to   `long_description` has syntax errors in markup and would not be rendered on PyPI. 
On windows python 3.8 one of the plotting tests fails with the warning: This probably means that tk wasn't installed properly.

These failing test do not seam to be due to this PR. 
Do you know what is causing these tests to fail @florian-huber

**Comment by florian-huber** [comment]
I recently started to see the tk issues frequently. This usually disappears upon re-runs of the tests, but that is of course no proper solution.

I will try to look a bit into the long_description one.

**Comment by florian-huber** [comment]
I did minor edits to `README.rst` since I am not sure what else should be the `long_description`.

--> https://github.com/matchms/matchms/actions/runs/5902451126/job/16010510821

**Comment by florian-huber** [comment]
Reason for `long_description` (for poetry simply the `README.rst) failure was a syntax error in the file which I found using https://github.com/rstcheck/rstcheck. Should be fixed with #489 

`tkinter` based issues only occur occasionally, so let's deal with this elsewhere, another time...
