### ISSUE TITLE
Actual implementation on GNPS

### ISSUE THREAD

**Issue by fdiblen** [matchms/matchms#5]
Actual implementation on GNPS as a workflow. GNPS is in Conda and has an API.
- [ ] Check what we need to do for GNPS implementation.

**Comment by mwang87** [comment]
I just got all the code up and running for matchms, happy to integrate into a workflow! Let me play a bit more and show you what I put together!

**Comment by florian-huber** [comment]
@mwang87 Fantastic! 
Let us know if you come across any issues, or if something is blocking an integration. Also let me know if you can use any help for integrating matchms .
Looking forward!

**Comment by florian-huber** [comment]
Spec2Vec has been added to GNPS (release 27)!
--> https://github.com/CCMS-UCSD/GNPS_Workflows/releases
