### ISSUE TITLE
Skipping spectra breaking pipeline

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#511]
In the process of finalizing the Pipeline and running on the entire GNPS library a few small unique bugs happen. The first 100.000 spectra process well and one spectrum has something unique that breaks one of the filter funcions. 
Currently, the entire pipeline breaks, making me have to rerun the entire pipeline (which takes >20h). I am of course fixing these bugs when they occur, but there might be a few unique cases that we will still miss.

I would like to brainstorm here on what the best structure is to prevent the pipeline from breaking completely, reducing the risk of long runs breaking half way. 

One option is just skipping and removing spectra if an error occurs (for instance with a maximum of 1% of all spectra).
Another option is in between backups. Now the filtered spectra are saved after running the pipeline. We could add continuous saving. In that case, spectra are appended to the spectrum file. This might cause a bit of overhead but could also reduce the required amount of memory. If it is easy to rerun with partly processed spectra this would make it easier to run the pipeline on large datasets. 

@hechth and @florian-huber what do you think?

**Comment by florian-huber** [comment]
To me both options make sense.
However, the backup option seems more robust and clean to me.
For cases such as the one you describe (>20h) all kinds of things can go wrong, including things beyond the reach of try-except constructions (crashes, Windows updates, etc.).

The text-based file formats are not great for fast reading/writing, but they do work well for continuous appending. So, we could simply add an option to keep a temporary mgf or msp file and add each processed spectrum at a time.

What is more tricky, though, is to allow continuation from such a file!
For this, we would also need to keep well-readable log information I think. In an extra file or in the header of the temporary storage file.

**Comment by niekdejonge** [comment]
Yes, this restarting is always a bit difficult. 
Brainstorming a bit:
Just checking the number of already processed spectra would not work, since spectra can be removed during filtering. 
We could do something as simple as loading the last spectrum in the already processed file and searching in the input spectra until the correct spectrum id was found (if there is a standard format for this).
You could start at the number of spectra already processed and continue until you find that spectrum. Since you will have processed at least that number already. You could than check for spectrum_id as mentioned above, but you could also just rerun the filtering until spectrum == last_spectrum_already_stored, which would not require such a field. 

This setup could just check if the output file already exists, in that case, the pipeline will continue from the state in which it stopped, if it is an empty file it will just start from scratch as normal. The nice thing about this is that there is no need for changing your script instead you can just run exactly the same script. 

An alternative could be removing spectra that are already processed from the input file and storing them in the output file. But, this feels a bit tricky.

**Comment by niekdejonge** [comment]
The logging that you mention could also be a good option. I like the idea of storing it in the header of the temporary spectrum file. This would directly be a nice check, that this file is intended to be a starting point and not someone accidentally pointing to the wrong output file. We could just store the number of spectra processed in the header of the file, use this as a starting point and just do a quick check that the last spectrum stored indeed matches the spectrum at that position in the input file. 
Once a run is finished this header can be removed. 

If the reading and writing is too slow it might be an alternative to set a batch size.
