### ISSUE TITLE
Reconsider filter warnings and flow

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#519]
I think that we created many of the filters and their executions with (mostly) annotated datasets in mind.
However, in practice, people will often run our default/basic processing pipelines on any kind of data, often data that is entirely non-annotated. 

Since our processing pipeline is currently strictly linear, our code will always run all the added filters independent of the quality/degree of available metadata.
For now, the easiest solution seems to be:

- Check again that we aim to quickly return spectra from a filter when it becomes clear that this filter can do nothing about a certain spectrum. 
For instance, return the spectrum rather than trying to repair its SMILES if it has not SMILES at all.

- In the long run, we might also consider building more "intelligent" processing pipelines. Say, if a spectrum has no compound name, no smiles, no inchi and no inchikey, then skip all filters that aim to correct/check/add those fields.

**Comment by niekdejonge** [comment]
Yes, I noticed this issue as well. You would actually like to have more of a tree-like structure of filters. 

One of the cases this was the case was running many repair functions to repair a mismatch between parent mass and smiles. If one of the filters fixes the issue, the rest of the filters do not have to be run. My solution now was to make a wrapper that just ran all of them until it was able to repair the issue, followed by skipping the remaining filter functions. https://github.com/matchms/matchms/blob/master/matchms/filtering/metadata_processing/repair_parent_mass_match_smiles_wrapper.py 

However, I am not sure how much overhead it costs to just do the check if the necessary fields are None, and if None just skip. So it might not even be that big of an issue to run some useless filters. For most of the filters, we already have this kind of checks included. 

My experience was that mostly the cloning of spectra was costing time, therefore doing these checks before cloning spectra, might already resolve any speed issues.
