### ISSUE TITLE
Pepmass overwritten

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#537]
In #533 we solved #532. 
To summarize: Interpret_pepmass uses the pepmass field to fill the precursor_mz. This overwrites the precursor_mz field if it was already filled. The issue is that we have other functions that can correct the precursor_mz. When loading in a stored spectrum these fields will be overwritten by the pepmass again. We have fixed this by after reading in the pepmass it is removed from the metadata, to prevent storing multiple input values that have the same meaning and thereby risking a discrepancy between the different keys. 

However, this means the metadata is stored as PRECURSOR_MZ in the mgf file as well (I wasn't aware of that before), which might give issues for other tools. We actually diversify the standards of ways of storing data even more than was already the case. Which is something we should not want. 

There are multiple solutions possible.
- When saving, convert back to the standard naming for this file type. So in save_as_mgf convert precursor mz back to pepmass before saving. If I understand correctly the difficulty with this solution would be that the metadata fields are not dependend on the file type right? But on the platform preference, so mgf could have pepmass, PRECURSORMZ and PrecursorMZ for instance? 
- Store the initial name and when making any changes to a metadata field, automatically update all possible fields that contain the same information. So any field updating precursor_mz, should also update pepmass (and PRECURSORMZ and PrecursorMZ). We could use the already existing https://github.com/matchms/matchms/blob/master/matchms/data/export_key_conversions.csv 

I think it is good to discuss this here, since I think that this is a more general problem. How do we handle multiple ways of naming metadata. The same goes for instance for retention_time, adduct, ionmode etc. 

@hechth @florian-huber what do you think?

**Comment by niekdejonge** [comment]
It will be very important to think this through well, because I think we currently are increasing the diversity of metadata formatting, while one of the goals of matchms is to actually solve this issue. 

A more complex way of solving the issue (but also better) would be the following: Instead of changing key_names to a matchms specific name, make matchms use multiple keys when searching for a value. Leave the metadata_keys as is and when processing use the export_key_conversions.csv to search for a value in the metadata. In this way keeping the key_name formatting as is in the file. e.g. when searching for precursor_mz, search for PRECURSORMZ, PrecursorMZ and PRECURSORMZ in the metadata, but do not change the field name internally to precursor_mz, instead the original field name is kept. 

In addition you could have a filter function called make_key_name_uniform(spectrum, key_type, preferred_key_name) which will convert all the key names to one format, which could be useful for a library combined from multiple sources.

**Comment by hechth** [comment]
@niekdejonge what do you mean with metadata is stored under `precursor_mz`?

I think the metadata parsing system should get some overhaul with the metadata harmonization maybe being removed and a clear distinction between metadata conversion and simple export.

I agree on the multiple key mappings - some R and python packages actually support this and I had already looked into this at some point.

> In addition you could have a filter function called make_key_name_uniform(spectrum, key_type, preferred_key_name) which will convert all the key names to one format, which could be useful for a library combined from multiple sources.

This should and is already part of the exporter with the different styles.

I think this is also in line with what @mobiusklein implemented in mzSpecLib

**Comment by florian-huber** [comment]
I would clearly take the first option you mention @niekdejonge!
Within matchms we make some choices in how we name the metadata fields. So do other databases or software packages.
We only have to make sure that the export options align well with the respective standards. In this case this means (as Helge mentioned) that we have to parse the field back to `PEPMASS` if a user selected this mgf-style.

The table that you mention is exactly made for this, for `gnps` style it should write the `precursor_mz` into a `PEPMASS` field (in the exporting file, not in the Spectrum object).

**Comment by florian-huber** [comment]
Currently the `style` parameter is only used in the `save_as_msp` function.
--> New issue: #556

**Comment by florian-huber** [comment]
See changes in #557.
