### ISSUE TITLE
MetadataMatch with "sparse" flag still allocates whole matrix

### ISSUE THREAD

**Issue by hechth** [matchms/matchms#544]
**Describe the bug**
If the user passes the `sparse` flag, it does maybe not make sense to allocate the whole matrix but to compute each entry separate and then add them to the sparse array.

**Comment by florian-huber** [comment]
That is also what the `sparse_array` method, for instance in `BaseSimilarity`, does.
(or at least, what it should do)
Can you point out where this occurs?

**Comment by hechth** [comment]
This occurs in the Metadata match at line 153.

The `equal match` will always allocate the whole matrix independent of whether the flag is set to sparse or dense. If it is set to sparse, it should only store the indices that are true, similar to how the `number_matching` function only stores those positions where the value is below a certain tolerance.

https://github.com/matchms/matchms/blob/1ba681524c2adff5e41e5df8399955a2e71164dc/matchms/similarity/MetadataMatch.py#L114-L174
