### ISSUE TITLE
Rdkit is not abe to load some smiles

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#549]
Some of the annotations found on pubchem, can not be loaded by RDkit.
For example: C[N+](C)(C)CCOS(=O)(=O)[O-] GIves a error of Valence =8 for the Sulfur. 

I will dive into this later to check if it is common that smiles cannot be loaded by rdkit.

**Comment by florian-huber** [comment]
Is this an error on the RDkit side, or is this an incorrect SMILES?

**Comment by niekdejonge** [comment]
Hmm, I now notice that the example I gave here is just not valid. (the N+ should be [N+]). And when trying again I did not get the valence error, but instead a cannot parse error. Not sure how I mixed this up...

I will get back to this. However, regardless of what type of mistake it is, I think we don't want them in our annotations, since they cannot be used for machine learning training if they are not RDkit interpretable. In #559 this has been fixed, so this does not happen anymore.
