### ISSUE TITLE
Cosine Greedy and Cosine Hungarian duplicate code

### ISSUE THREAD

**Issue by cwmeijer** [matchms/matchms#55]
They both define and implement the functions get_peaks_arrays() and get_matching_pairs() and the same line of code to normalize the score at the end of the calculation.
To solve this we could:
- [ ] Create an abstract base class that already implements these 3 blocks of code.
- [ ] Put the shared code blocks in some util file so it can be imported by the two similarity modules
- [ ] ..,. (Other suggestions?)

**Comment by florian-huber** [comment]
in PR #86 I moved the duplicates function to a utils collection ``spectrum_similarity_functions.py``.
