### ISSUE TITLE
add option to Scores.calculate and Scores.calculate_parallel for symmetrical problems

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#59]
For problems such as _library grouping_, ``Scores.scores`` is symmetric (for most similarity functions). We could add an option ``is_symmetric`` or ``triu_only`` (triangular upper part only) and ``tril_only`` (triangular lower part only) for a 2x performance gain.

**Comment by florian-huber** [comment]
I would like to work on this next.
Adding the ``is_symmetric`` flag seems pretty straightforward, and it probably good to do first.

Now I was wondering if there is also a more general alternative.
Would it be feasible and useful to add an option that will check for duplicates based on hashes/IDs (if we can implement this well enough --> #106 ) ?

**Comment by sverhoeven** [comment]
Instead of adding is_symmetric argument we could also add another function like `calculate_symmetric_scores(spectrums, Cosine())`. Having a boolean as an argument can be code smell.

**Comment by florian-huber** [comment]
In principle that's fine for me as well. My only worry then is that we might get too many methods:
``calculate()``, ``calculate_parallel()``, ``calculate_symmetric_scores()`` and ``calculate_symmetric_scores_parallel()``.
To me it feels like this could make it difficult for the user to know which one to pick.

**Comment by jspaaks** [comment]
>  Having a boolean as an argument can be code smell.

Just curious, I assume the thinking behind this is that if you have a boolean argument, the function body likely has branching, and if you have that, then you should have split the function in two?

If so, maybe make the four functions ``calculate()``, ``calculate_parallel()``, ``calculate_symmetric_scores()`` and ``calculate_symmetric_scores_parallel()`` private, then create a new public function ``calculate()``, with two flags, ``is_parallel`` and ``is_symmetric``. That way you can have the best of both worlds ...maybe.

**Comment by sverhoeven** [comment]
Forgot about the parallel version and an unimplemented distributed version (#8), indeed this will give many permutations of the calculate method. ~~But I still think having a method you give a single list of spectrums is easier to pick by a user then an argument that might not work if user gives 2 different lists~~ Nevermind, you can have 2 different lists where you can skip half.

Coding best practices advises to have a function that does one thing. Having a single calculate would make sense if the arguments are treated the same in each boolean combo, but in matchms the parallel methods need a different flavor of similarity function so putting that behind a single method would give a hard to read description.

**Comment by florian-huber** [comment]
From a user perspective your suggestion, Jurriaan, indeed looks nice.
Although it also seems like it's become a somewhat bigger change to matchms, I believe it's a good point to discuss!

Currently, a user has to import a similarity score (and here should already know about a possible parallel version). 
Then the user also needs to know which ``calculate()`` method to call.

I think it would indeed be nice to make this choice *for* the user. If the reference/query input is a list/array of spectrums (instead of two single spectrum), and if a parallel method exist, then this should be used to calculate the scores.

Probably that would make it necessary to refactor the similarity score classes a bit (maybe even break things, but better now than later?). For all similarity methods that do provide an optimized parallel implementation, that should then come within the same class. Maybe we can split the ``__call__`` method using a flag (guess that's not ideal), or provide classes that have two different methods, say ``compute_scores`` and ``compute_scores_parallel``. And only if the later is indeed provided and the input is arrays/lists, then this will be called by default?

**Comment by jspaaks** [comment]
If you choose automated switching between sequential and parallel similarity methods, I would simply do that by inheriting from two abstract similarity classes, one sequential, the other parallel. The parent could add two boolean members, ``is_parallel`` and ``is_sequential``, always each other's opposites.

That way, when the user supplies a method that has ``is_parallel`` ``True``, you know you should call ``_calculate_parallel()``.

But I'm not sure automated switching is the way to go

**Comment by jspaaks** [comment]
``calculate``'s signature could be something like

```python
calculate(references, queries, include_triu=True, include_diag=False, include_tril=True, is_parallel=None, is_distributed=None)
```

**Comment by florian-huber** [comment]
My main point is, that many users will only care about the type of score, not about which implementation is running under the hood (as long as the resulting scores are identical of course).

Currently we already have 4 options:
```python
from matchms import Scores, Spectrum
from matchms.similarity import FingerprintSimilarity, FingerprintSimilarityParallel

scores1 = Scores(references, queries, FingerprintSimilarity()).calculate().scores  # correct one if you want sequential
scores2 = Scores(references, queries, FingerprintSimilarityParallel()).calculate().scores  # will fail
scores3 = Scores(references, queries, FingerprintSimilarityParallel()).calculate_parallel().scores  # correct one if you want parallel
scores4 = Scores(references, queries, FingerprintSimilarity()).calculate_parallel().scores  # will fail
```
When adding symmetric case, we will get even more possible combinations.

**Comment by florian-huber** [comment]
I was just playing and protopying a bit. Would something along the following lines work for you:

```python
class Scores:
   ...

    def _chose_parallel_implementation(self):
        """
        Chose implementation for calculating the scores based on input dimensions and
        available score implementations (e.g. parallel or only sequential).
        """
        # Check if parallel implementation exists
        similarity_methods = dict((name, func) for name, func in inspect.getmembers(self.similarity_function))
        if "compute_scores_parallel" not in similarity_methods:
            return False

        # Check if input is likely to benefit from parallel implementation 
        if len(references) > 1 and len(queries) > 1:
            return True
        return False
    
    def calculate(self) -> Scores:
        """
        Calculate the similarity between all reference objects v all query objects using
        the most suitable available implementation of the given similarity_function.
        """
        if self._chose_parallel_implementation():
            return self.calculate_parallel()
        return self.calculate_sequential()
    
    def calculate_sequential(self) -> Scores:
        """
        Calculate the similarity between all reference objects v all query objects using a
        naive implementation (i.e. a double for-loop). Similarity functions should expect
        one reference and one query object as its input arguments.
        """
        for i_ref, reference in enumerate(self.references[:self.n_rows, 0]):
            if self.is_symmetric:
                for i_query, query in enumerate(self.queries[0, i_ref:self.n_cols], start=i_ref):
                    self._scores[i_ref][i_query] = self.similarity_function(reference, query)
                    self._scores[i_query][i_ref] = self._scores[i_ref][i_query]
            else:
                for i_query, query in enumerate(self.queries[0, :self.n_cols]):
                    self._scores[i_ref][i_query] = self.similarity_function(reference, query)
        return self
    
    def calculate_parallel(self) -> Scores:
        """
        Calculate the similarity between all reference objects v all query objects using a
        vectorized implementation.  Similarity functions should expect a Numpy array of
        all reference objects and a Numpy array of all query objects as its input arguments.
        """
        signature = inspect.signature(self.similarity_function)
        if "is_symmetric" in str(signature):
            self._scores = self.similarity_function(self.references[:, 0], self.queries[0, :],
                                                    is_parallel=True, is_symmetric=self.is_symmetric)
        else:
            self._scores = self.similarity_function(self.references[:, 0], self.queries[0, :],
                                                    is_parallel=True)
        return self

**Comment by florian-huber** [comment]
Score functions would then have to be adapted, which mostly means here combining the sequential and parallel ones into one class.
```python
class DummySimilarityFunctionNew:
    def __init__(self):
        """constructor"""

    def __call__(self, reference, query, is_parallel=False):
        """call method"""
        if is_parallel:
            return self.compute_scores_parallel(reference, query)
        return self.compute_scores(reference, query)

    def compute_scores(self, reference, query):
        """basic method, always provided for similarity scores"""
        s = reference + query
        return s, len(s)

    def compute_scores_parallel(self, reference, query):
        """parallel method, only provided for some similarity scores"""
        shape = len(references), len(queries)
        s = numpy.empty(shape, dtype="object")
        for index_reference, reference in enumerate(references):
            for index_query, query in enumerate(queries):
                rq = reference + query
                s[index_reference, index_query] = rq, len(rq)
        return s
```

**Comment by sverhoeven** [comment]
Besides your listed options, you can also have user call the sim function directly with:

```python
scores5 = [(q,r,FingerprintSimilarity(q,r)) for q in queries for r in references]
scores6 = FingerprintSimilarityParallel(queries, references)
```

In your prototype I like the idea of combining the sequential and parallel version in a single class.
I really don't like having a `__call__` where you can either have a pair of spectrums or a pair of lists of spectrums so I would like to keep those separate. So in your prototype  `self.similarity_function(reference, query)` would run the sequential version and `self.similarity_function.compute_scores_parallel(references, queries)` would run the parallel version. When you do that you can still have implementation using a simple function `my_sim(reference: Spectrum, query: Spectrum) -> float` and a combined sequential/parallel implementations with a Class.

**Comment by florian-huber** [comment]
Nice suggestion, thanks Stefan. That would be a very good solution to me as well.

**Comment by florian-huber** [comment]
Sorry, Stefan, now that I read your comment a 2nd time, I am not so sure I fully understand it.
Did you mean to have ``__call__`` as the basic sequential function and than ``.compute_scores_parallel`` as additional method?
```python
class DummySimilarityFunctionNew:
    def __init__(self):
        """constructor"""

    def __call__(self, reference, query):
        """basic method, always provided for similarity scores"""
        s = reference + query
        return s, len(s)

    def compute_scores_parallel(self, reference, query):
        """parallel method, only provided for some similarity scores"""
        shape = len(references), len(queries)
        s = numpy.empty(shape, dtype="object")
        for index_reference, reference in enumerate(references):
            for index_query, query in enumerate(queries):
                rq = reference + query
                s[index_reference, index_query] = rq, len(rq)
        return s
```
Or omitting the ``__call__`` entirely and use two methods instead?

**Comment by sverhoeven** [comment]
Had a look at existing similarity functions and they all use a class `__init__` to configure and `__call__` to run in calculate_scores. I thought we had a pure `my_sim(reference: Spectrum, query: Spectrum)` funcs, but I was incorrect. 

Using `compute_scores` and `compute_scores_parallel` seems the way to go. All the similarity function could derive from an abstract base classlike

```python
from abs import ABC

class AbstractSimilarityFunction(ABC):

  def compute_scores(self, reference: SpectrumType, query: SpectrumType) -> float:
    raise NotImplementedError

  def compute_scores_parallel(self, reference: List[SpectrumType], query: List[SpectrumType]) -> numpy.ndarray:
    raise NotImplementedError

class DummySimilarityFunctionNew(AbstractSimilarityFunction):
    def __init__(self):
        """constructor"""

    def compute_scores(self, reference, query):
        """basic method, always provided for similarity scores"""
        s = reference + query
        return s, len(s)

    def compute_scores_parallel(self, reference, query):
        """parallel method, only provided for some similarity scores"""
        shape = len(references), len(queries)
        s = numpy.empty(shape, dtype="object")
        for index_reference, reference in enumerate(references):
            for index_query, query in enumerate(queries):
                rq = reference + query
                s[index_reference, index_query] = rq, len(rq)
        return s
```

**Comment by florian-huber** [comment]
After today's discussion with @sverhoeven and @jspaaks, I think we will -for now- not look further into using hashed/IDs to avoid double computations.

Hashes must reflect all relevant information from metadata and peaks. And hashes (probably due to rounding) are not always the same when derived from the same input.

**Comment by florian-huber** [comment]
Hi Stefan, I like your code suggestion above. I realized thought, that when I implement this in ``Scores`` it would be nice to also a simple way to see if a given class provided a parallel method. Maybe we could add such key characteristics as a class attribute?
Say, like this:
```python
from typing import List
from matchms.typing import SpectrumType


class AbstractSimilarityFunction:
    """Similarity function base class..."""
    # Set key characteristics as class attributes
    is_commutative = True
    has_parallel = False
    
    def compute_scores(self, reference: SpectrumType, query: SpectrumType) -> float:
        raise NotImplementedError
      
    def compute_scores_parallel(self, reference: List[SpectrumType], query: List[SpectrumType]) -> numpy.ndarray:
        raise NotImplementedError

class DummySimilarityFunctionNew(AbstractSimilarityFunction):
    # Set key characteristics as class attributes
    has_parallel = True
    
    def __init__(self):
        """constructor"""

    def compute_scores(self, reference, query):
        """basic method, always provided for similarity scores"""
        s = len(reference.peaks) + len(query.peaks)
        return s

    def compute_scores_parallel(self, reference, query):
        """parallel method, only provided for some similarity scores"""
        shape = len(references), len(queries)
        s = numpy.empty(shape, dtype="object")
        for i_ref, reference in enumerate(references):
            for i_query, query in enumerate(queries):
                rq = len(reference.peaks) + len(query.peaks)
                s[i_ref, i_query] = rq
        return s
```

**Comment by florian-huber** [comment]
Then ``Scores`` could be changed by adding:
```python
class Scores:
    ...
    def _chose_parallel_implementation(self):
        """
        Chose implementation for calculating the scores based on input dimensions and
        available score implementations (e.g. parallel or only sequential).
        """
        if not self.similarity_function.has_parallel:
            return False

        # Check if input is likely to benefit from parallel implementation 
        if len(references) > 1 and len(queries) > 1:
            return True
        return False
    
    def calculate(self) -> Scores:
        """
        Calculate the similarity between all reference objects v all query objects using
        the most suitable available implementation of the given similarity_function.
        """
        if self._chose_parallel_implementation:
            return self.calculate_parallel()
        return self.calculate_sequential()
    
    def calculate_sequential(self) -> Scores:
        """
        Calculate the similarity between all reference objects v all query objects using a
        naive implementation (i.e. a double for-loop). Similarity functions should expect
        one reference and one query object as its input arguments.
        """
        for i_ref, reference in enumerate(self.references[:self.n_rows, 0]):
            if self.is_symmetric:
                for i_query, query in enumerate(self.queries[0, i_ref:self.n_cols], start=i_ref):
                    self._scores[i_ref][i_query] = self.similarity_function.compute_scores(reference, query)
                    self._scores[i_query][i_ref] = self._scores[i_ref][i_query]
            else:
                for i_query, query in enumerate(self.queries[0, :self.n_cols]):
                    self._scores[i_ref][i_query] = self.similarity_function.compute_scores(reference, query)
        return self
    
    def calculate_parallel(self) -> Scores:
        """
        Calculate the similarity between all reference objects v all query objects using a
        vectorized implementation.  Similarity functions should expect a Numpy array of
        all reference objects and a Numpy array of all query objects as its input arguments.
        """
        signature = inspect.signature(self.similarity_function.compute_scores_parallel)
        if "is_symmetric" in str(signature):
            self._scores = self.similarity_function.compute_scores_parallel(
                self.references[:, 0], self.queries[0, :], is_symmetric=self.is_symmetric)
        else:
            self._scores = self.similarity_function.compute_scores_parallel(
                self.references[:, 0], self.queries[0, :])
        return self
```

With the class attributes we could also add checks like ``if self.is_symmetric: assert self.similarity_function.is_commutative``

**Comment by sverhoeven** [comment]
Using OOP, you would use a `isinstance()` check to find out where the class inherited from. For example:

```python
class AbstractSimilarityFunction:
    """Similarity function base class..."""
    # Set key characteristics as class attributes
    is_commutative = True

class  AbstractSequentialSimilarityFunction(AbstractSimilarityFunction):
    def compute_scores(self, reference: SpectrumType, query: SpectrumType) -> float:
        raise NotImplementedError
      
class  AbstractParallellSimilarityFunction(AbstractSimilarityFunction):
    def compute_scores_parallel(self, reference: List[SpectrumType], query: List[SpectrumType]) -> numpy.ndarray:
        raise NotImplementedError

class DummySimilarityFunctionNew(AbstractParallellSimilarityFunction, AbstractSequentialSimilarityFunction):
   # class has both functions
   pass

obj = DummySimilarityFunctionNew()
has_parallel = isinstance(obj, AbstractParallellSimilarityFunction)
```

Using properties also works and keeps the inheritance tree nice and simple.

**Comment by florian-huber** [comment]
Ok, thanks!

That will work I think. Only we will have to provide a good enough "recipe" in the docstring to guide people how to build their own scores and make sure they inherit from the right classes.

**Comment by florian-huber** [comment]
Started working on it --> #133

**Comment by florian-huber** [comment]
Still working on in in #133. I now implemented ``CosineGreedy``, ``ParentmassMatch`` and ``IntersectMZ`` in the "new way".

In the current implementation I did, we have the following.
If a user wants to get a Score matrix, then that's possible:
- via similarity function directly
```python
from matchms.similarity import ParentmassMatch

similarity_measure = ParentmassMatch(tolerance=1.0)
score, n_matches = similarity_measure.compute_scores(references, queries)

# or:
score, n_matches = similarity_measure.compute_scores_parallel(references, queries)

# or:
score, n_matches = similarity_measure.compute_scores_parallel(references, references, is_symmetric=True)
```
- via ```Scores```
```python
from matchms import Scores
from matchms.similarity import ParentmassMatch

similarity_measure = ParentmassMatch(tolerance=1.0)
scores = Scores(references, queries, similarity_measure).calculate()

# or:
scores = Scores(references, references, similarity_measure,
                is_symmetric=True).calculate()
```
In the above example, the user still has to know and decide which one to pick. That could be avoided by moving the "decision" which implementation to use from ``Scores`` down to the similarity score, e.g. having a ``compute_scores`` method that will call ``compute_scores_parallel`` or ``compute_scores_sequential`` ?

**Comment by florian-huber** [comment]
This issue was very useful, at least for me :)
But has grown a bit out of hand. So I will close it so that **we can continue discussing the design again in a followup-issue --> #135**
