### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5: invalid continuation byte

### ISSUE THREAD

**Issue by LiuBurger** [matchms/matchms#608]
When loading the msp file “MoNA-export-Experimental_Spectra.msp”，it corrupt.
<img width="749" alt="屏幕截图 2024-04-01 204000" src="https://github.com/matchms/matchms/assets/68485539/d0b65e6b-8c23-4c11-b6a1-70c82cf3d381">

**Comment by niekdejonge** [comment]
This seems to have to do with characters that are not utf-8 not being recognized. I would not expect any none utf-8 characters for the Mona datasets, but if they just occur in some comment of one spectrum, it might be best to just ignore them. 

So we could maybe change: 
```with open(filename, 'r', encoding='utf-8') as f:``` 
in line 58 to 
```with open(filename, 'r', encoding='utf-8', errors="ignore") as f:``` 
to just remove these characters.

**Comment by LiuBurger** [comment]
Thank you very much！
