### ISSUE TITLE
RuntimeError: Wrong peak format detected!

### ISSUE THREAD

**Issue by LiuBurger** [matchms/matchms#609]
When loading the MoNA-export-Experimental_Spectra.msp
<img width="569" alt="屏幕截图 2024-04-01 214940" src="https://github.com/matchms/matchms/assets/68485539/2a7e9934-e999-4f05-abf3-af259e112ab9">

**Comment by niekdejonge** [comment]
There seems to be something wrong with this file. This error happens if more or less than 2 values are given on a line that should denote the mz and intensity. Did you manually change anything in the file?

**Comment by niekdejonge** [comment]
Could you share an example spectrum from the file, which is not able to load?  Could it be the same issue as #604?

**Comment by LiuBurger** [comment]
> There seems to be something wrong with this file. This error happens if more or less than 2 values are given on a line that should denote the mz and intensity. Did you manually change anything in the file?

Thank you for answering.
I didn't change anything in the file, I just download the zip file on windows and transfer it to linux and unzip it. It seems that something goes wrong during the unzipping. The wrong peak format is like below:
 1.198198
25.5994 1.006006
25.9397 1.426426
26.2973 1.045045
25.5055
