### ISSUE TITLE
Make Spikes immutable to limit the performance penalty of copying mz and intensities

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#61]

**Comment by sverhoeven** [comment]
See https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html how to mark numpy arrays as read only.

**Comment by sverhoeven** [comment]
The Spikes.clone() should still copy, but Spikes.peaks and Spikes.losses should return a read only array.

**Comment by jspaaks** [comment]
Currently, I have this https://github.com/matchms/matchms/blob/db4206039bc33cbcae70b3bef9234e62a454d4cc/matchms/Spikes.py, but I'm not convinced it is what we want.

**Comment by florian-huber** [comment]
Outdated. Please re-open or create new issue if this becomes an issue.
