### ISSUE TITLE
Predefined top=n argument on Scores.calculate() could save memory

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#62]
As an alternative to #60, we could give the user the option to only store the top x results and discard the rest.

**Comment by sverhoeven** [comment]
So if x=10 then each query would have the 10 best scoring references. Or the 10 best scoring query/reference pairs.

**Comment by sverhoeven** [comment]
This moves the sorting of scores back into the mathms library which was difficult because we don't know what a similarity function returns.

**Comment by florian-huber** [comment]
In PR #153 we now include a way to sort the scores. So in principle this could make it possible to only keep the highest n scores.

**Comment by florian-huber** [comment]
Outdated. Please re-open or create new issue if this becomes an issue.
