### ISSUE TITLE
Pipeline should be able to take in custum filters

### ISSUE THREAD

**Issue by niekdejonge** [matchms/matchms#626]
SpectrumProcessor is able to handle custom filters, however, pipeline is not. 
This is the case because create_workflow converts the filters to string representations. This works for the matchms filters, but does not work for the custom filters.

**Comment by Adafede** [comment]
Example request from workshop: filter spectra within RT

**Comment by niekdejonge** [comment]
@Adafede Now I know why I thought the rt filter was already there, there was a PR open, but we did not merge yet. But now we added the rt filter.
