### ISSUE TITLE
Readthedocs is not being updated

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms#65]
Documentation was improved in #53, but https://matchms.readthedocs.io/en/latest/ has not been updated.

**Comment by sverhoeven** [comment]
Added webhook to GH settings, saw test ping was received on readthedocs.

Manually triggered build on readthedocs. 

Also added myself as maintainer of matchms and spec2vec projects on readthedocs.

**Comment by sverhoeven** [comment]
Build failed with `no module named 'numba'`.

**Comment by sverhoeven** [comment]
Wait for readthedocs to be updated.

**Comment by florian-huber** [comment]
I guess this is outdated?

**Comment by sverhoeven** [comment]
Yep
