### ISSUE TITLE
Install instructions on anaconda don't work

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms#66]
The install instructions on https://anaconda.org/nlesc/matchms don't work.

Trying

```shell
conda install -c nlesc matchms
```

It is unable to find the dependencies.

The install command `conda install --channel nlesc --channel bioconda --channel conda-forge matchms` in the README.md does work.

We should somehow make sure the install instructions on https://anaconda.org/nlesc/matchms work or are corrected in the description.

**Comment by florian-huber** [comment]
With the addition of matchms to Bioconda (#178 ), the following will work:
```
conda install -c bioconda matchms
```

**Comment by florian-huber** [comment]
We will then have matchms in `bioconda` and in the `nlesc` channel... should we then remove the 2nd?

**Comment by sverhoeven** [comment]
Doh, Instructions on https://anaconda.org/bioconda/matchms also don't because rdkit must come from conda-forge channel.

Yes, lets drop nlesc channel
1. Remove all the anaconda build stuff from CI workflows and docs as building anaconda package is now handled by external bioconda recipe.
2. Add CI workflow where just rdkit is installed with conda and runs inchi/smiles tests
2. Only mention `pip` or `conda install -c conda-forge -c bioconda matchms` as installation methods.
3. Keep old versions of matchms in Anaconda NLeSC channel so spec2vec can gradually switch to bioconda.

**Comment by florian-huber** [comment]
Sounds like a plan!
(and I guess you meant `conda install -c conda-forge -c bioconda matchms`)
