### ISSUE TITLE
load_from_mgf leads to corrupt of vscode

### ISSUE THREAD

**Issue by LiuBurger** [matchms/matchms#679]
**Describe the bug**
When loading a mgf file which contains about 119k spectrums，it leads to a corrupt of vscode that I can not even close it！

**Expected behavior**
An old version which does not check precursor_mz and print out seems to work well，looking forward to a set up that do not print out the warning.

**Screenshots**
<img width="1280" alt="屏幕截图 2024-06-19 211454" src="https://github.com/matchms/matchms/assets/68485539/1c4d497d-5913-48e9-84c9-dc3b7bf62d51">

VScode version：1.88.0

**Comment by hechth** [comment]
Hi, you can set the logger level to error using the following line:
```
from matchms import set_matchms_logger_level
set_matchms_logger_level("ERROR")
```

This should remove the printouts which cause vscode to freeze.

**Comment by LiuBurger** [comment]
> Hi, you can set the logger level to error using the following line:
> 
> ```
> from matchms import set_matchms_logger_level
> set_matchms_logger_level("ERROR")
> ```
> 
> This should remove the printouts which cause vscode to freeze.

Thank you very much，it works！
