### ISSUE TITLE
Align talking and coding: `spectrums` --> `spectra`

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#687]
Long long ago we had settled on using `spectrums` as the plural of spectrum in our code.
Except that virtually everyone uses `spectra` for that, which frequently confuses.

In matchms, but also in many libraries build on top of matchms we now see mixed use of both terms, which is probably even worse.

Time to consistently switch to `spectra`.

**Comment by florian-huber** [comment]
For the records:
- `spectrum` will refer to a single `Spectrum` object in matchms
- `spectra` means one or many `Spectrum` objects in a list or array form.

In the future, we might want to also consider an own `Spectra` (or differently named) dataset class with more functionality than the simple lists we now use. --> #688

**Comment by florian-huber** [comment]
This issues will give a very good tour through all parts of matchms @julianpollmann  ;)

**Comment by julianpollmann** [comment]
Merged with PR #690
