### ISSUE TITLE
Updated numpy version will fail comparisons

### ISSUE THREAD

**Issue by julianpollmann** [matchms/matchms#693]
There are several occurences of numpy comparisons, which will fail with more recent numpy versions (e.g. 1.26). Previous versions raise a warning. E.g:

Python 1.24:
```
/matchms/networking/SimilarityNetwork.py:110: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
    assert np.all(scores.queries == scores.references), \
```

Python 1.26:
`test_SimilarityNetwork.py::test_create_network_symmetric_wrong_input - ValueError: operands could not be broadcast together with shapes (3,) (5,)`

This effects PR #640

**Comment by julianpollmann** [comment]
Should be fixed with 4e7f6c6 and ee22492

**Comment by hechth** [comment]
@julianpollmann I assume this can be closed as completed? I didn't see any warnings in the test cases.

**Comment by julianpollmann** [comment]
Yes, can be closed!
