### ISSUE TITLE
Move lookup related functionality to its own directory

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#7]
Any function that mentions:

- library
- inchikey
- SMILES
- pubchem
- fingerprint
- rdkit
- openbabel

is likely part of looking up what is known about a compound, so you can interpret a match with a measured spectrum. This is completely separate from the similarity calculation, and (optionally) happens after. We should therefore move it to a new directory, ``/lookup`` to be created in the root of the module.

**Comment by fdiblen** [comment]
@florian-huber any updates on this?

**Comment by florian-huber** [comment]
Some of the things mentioned in the list above are implemented now, but nothing that is actually doing "lookups" as in checking with an external database or such.
- Smiles, Inchi, Inchikey conversions are now part of filtering and done using `` rdkit``.
- Fingerprints are also done using ``rdkit`` (PR #45 )
- Much more extensive cleaning of the compound-name is done within PR #34 and can be seen as preparation for later lookups.
- The actual lookup that I did was still using "custom scripts" not part of matchms. They can be found here: https://github.com/matchms/matchms/blob/iomega-development/custom_functions/pubchem_lookup.py
--> To be implemented in matchms they would require extra refactoring.
--> Not sure if we __want__ those functions to become part of matchms?

**Comment by florian-huber** [comment]
The current code for the PubChem lookup procedure is now part of https://github.com/iomega/spec2vec_gnps_data_analysis
I will hence close this issue here (lookups could always be added later, but they are not our main focus for now).
