### ISSUE TITLE
Store losses as part of spectra object

### ISSUE THREAD

**Issue by rtlortega** [matchms/matchms#704]
**Is your feature request related to a problem? Please describe.**
We are working in a project called MS2LDA that relies on the ability to store losses in the Spectrum object. It does so, because it tries to find patterns (combinations of fragments and losses)  across several spectra. 
We store those patterns as Spectrum objects, where we **add the losses manually**.  It is important to know that losses can't be calculated in this step since there is no existing precursor mz for a pattern.

Following you can see our function to create a Spectrum object based on a found pattern:
---------------------------------------------------------------------------------------------------
def create_spectrum(motif_k_features, k, frag_tag="frag@", loss_tag="loss@", significant_digits=2, charge=1, motifset="unknown"):
    """creates a spectrum from fragments and losses text representations like frag@123.45 or fragment_67.89
    
    ARGS:
        motif_k_features (list): for motif number k all features in a unified representation
        k (int): motif id
        frag_tag (str): unified pre-fragments tag
        loss_tag (str): unified pre-loss tag
        significant_digits (int): number of significant digits that should be used for each fragment and loss
        
    RETURNS:
        spectrum: matchms spectrum object
    """

    # identify slicing start
    frag_start = len(frag_tag)
    loss_start = len(loss_tag)

    # extract fragments and losses
    **fragments = [ ( round(float(feature[frag_start:]),significant_digits), float(importance) ) for feature, importance in motif_k_features if feature.startswith(frag_tag) ]
    losses = [ ( round(float(feature[loss_start:]),significant_digits), float(importance) ) for feature, importance in motif_k_features if feature.startswith(loss_tag) ]**

    # sort features based on mz value
    sorted_fragments, sorted_fragments_intensities = zip(*sorted(fragments)) if fragments else (np.array([]), np.array([]))
    sorted_losses, sorted_losses_intensities = zip(*sorted(losses)) if losses else (np.array([]), np.array([]))

    # normalize intensity over fragments and losses
    intensities = list(sorted_fragments_intensities) + list(sorted_losses_intensities)
    max_intensity = np.max(intensities)
    normalized_intensities = np.array(intensities) / max_intensity

    # split fragments and losses
    normalized_frag_intensities = normalized_intensities[:len(sorted_fragments)]
    normalized_loss_intensities = normalized_intensities[len(sorted_fragments):]

    # create spectrum object
    spectrum = Spectrum(
        mz=np.array(sorted_fragments),
        intensities=np.array(normalized_frag_intensities),
        metadata={
            "id": f"motif_{k}".strip(),
            "charge": charge,
            "ms2accuracy": (1 / (10 ** significant_digits)) / 2 ,
            "motifset": motifset,
        }
    )
    **spectrum.losses = Fragments(mz=np.array(sorted_losses),** **intensities=np.array(normalized_loss_intensities))**

    return spectrum
-----------------------------------------------------------------------------------------------

**Describe the solution you'd like**
The previous versions of match supported the functionality of adding losses manually, but from 0.27 version the functionality was removed

**Any good starting points?**
Could you please take back / add this functionality

-Link for our repository:
https://github.com/vdhooftcompmet/MS2LDA

-Publication to the previous version of the tool we are working on:
(https://www.pnas.org/doi/full/10.1073/pnas.1608041113)

**Comment by niekdejonge** [comment]
The easiest solution is likely to just add losses to the general metadata. I think you can just use spectrum.set("losses", [10, 20, 30, 40]) and spectrum.set("loss_intensities", [0.1, 0.3, 0.4, 0.5]) and retrieving by spectrum.get("losses") and spectrum.get("loss_intensities"). Would that work for you? Or are there other missing functionalities for you?

**Comment by j-a-dietrich** [comment]
Not sure if this would solve the problem, since we use Spec2Vec for the annotation which retrieves the losses from the spectrum.losses object and not the metadata. In the future it will probably then try to calculate the losses in-time (that would lead to a bad/wrong prediction). I could use your suggestion, but only if I would make a clone of the Spec2Vec library and change the source code. But maybe I overlook another solution to this. Let me know if you have any.

**Comment by niekdejonge** [comment]
After discussing in person, @j-a-dietrich and @rtlortega will try if passing a Mass2Motif object they implement (instead of Spectrum) to Spec2vec. They can overwrite the losses method, with one appropriate for mass2motifs. If this does give issues (e.g. if we check the input is a Spectrum object), we can check if their are modifications needed in Spec2Vec to enable that. 

Feel free to reopen again at that point.
