### ISSUE TITLE
Use IntersectMZ score as template/example (add docstring)

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#75]
That score was used as an example/template in the beginning, but I don't expect it to be actually used.

**Comment by jspaaks** [comment]
I think there's value to keeping it, as a first example of a tutorial. The order could be:
1. introduce spectrum data
1. introduce ``Spectrum`` class, and instantiate it with the given data
1. ``spectrum1.plot()``
1. introduce concept of a similarity measure, exemplify by calculating ``IntersectMz`` similarity between ``spectrum1`` and a copy ``spectrum2 = spectrum1.clone()``
1. show how that breaks down if the peaks are not perfectly aligned, by perturbing the ``mz`` values of ``spectrum2``
1. this will set you up nicely for concepts that follow later, such as shifting peaks by some value, pair-finding within in a tolerance, rounding mz values to a certain precision.

**Comment by florian-huber** [comment]
Valid point!
Let's then keep it, but add to the docstring that it's meant as a template/example.

**Comment by florian-huber** [comment]
--> PR #86
