### ISSUE TITLE
Add methods to "Scores" object to better query and sort matches

### ISSUE THREAD

**Issue by florian-huber** [matchms/matchms#78]
Scores currently allows to either access the underlying similarity score array by ``scores.scores``, or to loop through the scores, for instance:
```python
for (ref, query, score, nmatch) in scores:
    print(ref.get("spectrumid"), query.get("spectrumid"), score, nmatch)
```
That is fine for the test examples so far. But when handling a lot of queries and references I realized that it is rather unintuitive. 

For example: 
If I have 10 query spectrums that I want to compare with a large database of -say- 10,000 spectrums, I typically would like to get the best matching reference spectrums per query spectrum.

Maybe we could add a class method ``sort_per_query``?
E.g. using ``numpy.argpartition(scores.scores, -top_n, axis=0)[-top_n:, :]``, with ``top_n`` the number of best matches to display per query...

**Comment by sverhoeven** [comment]
Because the score value type depends on what the score function returns we (me and @jspaaks ) did not want to do any sorting in the Scores class. 

So I am not in favor of a `sort_per_query` function, but maybe `scores.scores_of_query()` could work. It could return an iterator of (reference_spectrum, score object) tuples.

```python
q1 = <Spectrum class>
scores_of_q1 = scores.scores_of_query(q1)
sorted(scores_of_q1, key=lambda s: s[0][0])[10:]
[(<Spectrum class>, (0,32,))]
```

**Comment by florian-huber** [comment]
True, the different score types (score vs score+matches etc.) would indeed make it cumbersome to add it the way I suggested.
However, your suggestion seems perfectly fine for my purposes as well, so let's go for a ``scores_of_query()``.

Maybe something to keep in mind here as well:  I recently had some discussions regarding #81. It seems that the functions you describe could also be ``scores.sort_per_spectrum()`` as it could return all scores for one spectrum independent of whether it is a ``reference`` or ``query`` spectrum, right?

**Comment by sverhoeven** [comment]
Yes, scores is a matrix so `scores_of_reference()` to get the other dimension seems also useful to have, 

The `Scores.scores` should be more explicit in whether the queries/references are columns/rows or rows/columns.

**Comment by florian-huber** [comment]
--> PR #142
