### ISSUE TITLE
mzXML import/export

### ISSUE THREAD

**Issue by sverhoeven** [matchms/matchms#80]
[mzXML](https://en.wikipedia.org/wiki/Mass_spectrometry_data_format) is a file format used for ms/ms data. Matchms should have support to import and export the mzXML format.

It's cousin mzML should also be supported.

Both formats can be read by [pyteomics](https://pyteomics.readthedocs.io/en/latest/data.html#xml-formats).

**Comment by florian-huber** [comment]
Good idea!
We should then also look at mzML I guess.

**Comment by florian-huber** [comment]
Work in progress in PR #110

**Comment by florian-huber** [comment]
Import was added in PR #110.
Export is now separate issue #114
