### ISSUE TITLE
add equivalent filter of merge_ppm

### ISSUE THREAD

**Issue by jspaaks** [matchms/matchms#9]
https://github.com/matchms/matchms/blob/61602e744be587be98122d5964d5ed75cca2ecba/matchms/old/ms_functions.py#L74-L75

**Comment by florian-huber** [comment]
This is a bit outdated. I will close it for now as it is currently not needed. If potential users want such a feature we can consider this again.

**Comment by bachi55** [comment]
Hei,

from the discussion above I did not fully understand whether matchms implements a pre-processing function to merge, for example, spectra of the same compound with different collision energies. @florian-huber your code-snipped above looks to me like a simple merging approach. Is this one somewhere in your library? At least, I could not find it in the documentation. 

Best regards,
Eric

**Comment by florian-huber** [comment]
Hi @bachi55 ,
matchms currently does not provide such an option (the code above comes from prior prototyping).
If it would be a useful feature to have in your case, best to add a new issue describing what exactly would be necessary (maybe link to this issue as well).
Cheers,
Florian
