### ISSUE TITLE
Regular expression for molecular formulas is ambiguous

### ISSUE THREAD

**Issue by kaibioinfo** [matchms/matchms#94]
The current regular expression for molecular formulas is ambiguous.
`regexp = r"^[C][0-9][0-9A-Z]{4,}$"`
This will match against e.g. Kegg IDs like C01902. Furthermore it won't match any molecular formula that contains lowercases, like C6H4Cl.

I suggest to use
`^(?:[A-Z][a-z]?(?:[1-9][0-9]*)?){2,}$`
instead.

**Comment by florian-huber** [comment]
Many thanks @kaibioinfo ! We added the improved regex that you suggested --> #97
